### ISSUE TITLE
Form Creation does not work in WordPress 5.6

### ISSUE THREAD

**Issue by martin-neumann-gurus** [CalderaWP/Caldera-Forms#3642] opened 2020-12-10 18:34 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab
WordPress Version: 5.6PHP Version: 7.3.25MySQL Version: 5.7.26Caldera Forms Version: 1.9.2WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.
I tried on several sites, when I update to WordPress 5.6, I cannot create new forms, even though it worked fine before the WordPress update.
I choose a name, but the create button does not work.

**Comment by Renewrmk** [comment] 2020-12-10 19:42
Install the Plugin "Enable jQuery Migrate Helper" and use older jquery Version will help.

**Comment by KilakwaBT** [comment] 2020-12-11 16:02
I am seeing this issue and we are not able to clone or export a form. I installed "Enable jQuery Migrate Helper". If I leave the settings as "Default from WordPress" and set to "Allow website visitors to trigger an automatic downgrading to legacy jQuery, when a failure is detected" the issue remains. If I set the jQuery version to "Legacy 1.12.4-wp" I can clone and create forms. My concern is this causes other issues.

**Comment by Renewrmk** [comment] 2020-12-11 16:05
"The Caldera Forms team has been working on the updates for the WordPress 5.6 upgrade to jQuery 3. We have the fixes but haven’t completed migrating and testing them in the codebase.
For the time being, please revert WordPress to a 5.5.x version and we will let you know as soon as we get our update out.
Thank you for your patience."

https://wordpress.org/support/topic/conflict-with-wordpress-version-5-6/

**Comment by New0** [comment] 2020-12-15 11:43
Partial notes while debugging this issue:

- Loading the Caldera Forms -> Forms page using jQuery 3.5.1 . The id ( normally set as 'id="baldrick_trigger_1608031375178"' ) of the "Create Form" button in the "Create New Form" Modal Form is not being set.
![Screenshot_2020-12-15 Caldera Forms Admin ‹ VSLAN — WordPress](https://user-images.githubusercontent.com/16348693/102209027-7d39ed00-3ed0-11eb-9e0d-cd9e14d15677.png)

- Setting a breakpoint in wp-baldrick-full.js l4104 I realized that "this" object is empty when clicking the "New Form" button that opens the "Create New Form" Modal form when using jQuery 3.5.1 while it returned an object for a button element in jQuery 1.12.4
![Screenshot_2020-12-15 Caldera Forms Admin ‹ VSLAN — WordPress(1)](https://user-images.githubusercontent.com/16348693/102210494-8af07200-3ed2-11eb-8bd4-0f107769367d.png)
`<button class="cf-create-form-button ajax-trigger _tisBound" type="button" data-action="create_form" data-active-class="disabled" data-load-class="disabled" data-callback="new_form_redirect" data-before="serialize_modal_form" data-modal-autoclose="new_form" data-nonce="d0d5a9ea13">
wp-baldrick-full.js:4105:15`

**Comment by agileware-justin** [comment] 2020-12-15 21:37
Related https://github.com/CalderaWP/Caldera-Forms/issues/3639

**Comment by New0** [comment] 2020-12-16 13:47
@agileware-justin thanks for joining the issues, #3639  and #3642 are related in the way that the difference in the "this" object in `$.fn.baldrick` (wp-baldrick-full.js l3998 ) between version 1.12.4 and 3.5.1 seems to be the cause of the issues.

Using jQuery 3.5.1 :
- during pageload "this" is not set wit a .selector and .context ( as opposed to the "this" object in 1.12.4 )
- "this" is empty when the baldricj function is called during a click event ( as opposed to version 1.12.4 which ahd a this object declared with a new element that was used in modal form ).

@Shelob9 I am still not sure which jQuery change is causing this behaviour I also noticed that in admin.js l19 the "clicked" var declared using $(el) is not set with a .selector and .context ( as opposed to clicked var declared in 1.12.4 )

**Comment by shaneonabike** [comment] 2020-12-17 14:44
Would it be possible to add something on your plugin page referring to this issue... It's pretty huge and I had no idea until I came across this on github. I can't wait for this to be fixed so I can continue to develop :)

**Comment by New0** [comment] 2020-12-18 15:15
Test zip - https://github.com/CalderaWP/Caldera-Forms/releases/download/1.9.3-b4/1.9.3-b4.zip -

This should be closed via - https://github.com/CalderaWP/Caldera-Forms/commit/1c1c4607c41df287c192f36734c45c56ef121d5b -

An official update will be pushed as soon as possible. Don't hesitate to reopen this if the test zip is not working ( making sure all assets are refreshed in the browser ).

Thank you all for opening this issue and sharing details.

**Closed by New0** 2020-12-18 15:15 UTC
Labels: Has PR
