### ISSUE TITLE
JS error while loading default style of Caldera Forms

### ISSUE THREAD

**Issue by sushmak02** [CalderaWP/Caldera-Forms#3053] opened 2019-03-06 09:36 UTC
Hello, I am from Ultimate Addons for Elementor team. We create different widgets for Elementor page builder. Refer - https://uaelementor.com/

We have created a widget called "Caldera Form Styler" to style the default Caldera Form in Elementor.
We fetch the forms list from database. But to load the default style from Caldera Forms we have added below code - 
if ( class_exists( 'Caldera_Forms_Render_Assets' ) && class_exists( 'Caldera_Forms' ) ) {
	\Caldera_Forms_Render_Assets::register();
	\Caldera_Forms_Render_Assets::optional_style_includes();
	\Caldera_Forms_Render_Assets::enqueue_all_fields();
}

## What Is The Unexpected Behaviour?
Using above lines of code the Caldera Forms style was loading correctly. But, after Caldera v1.8.0 update I am getting this JS error in my console - Uncaught TypeError: a(...).baldrick is not a function
You can see this error on this page - http://uael-sushma.sharkz.in/caldera-form/

It seems like the error I am getting is from this line - \Caldera_Forms_Render_Assets::enqueue_all_fields();
Also, this error occurs only when the caldera form is not added on page. I am facing this issue after v1.8.0 update.

Am I missing something? Is there any other way to load the default style of Caldera Forms or I need to make any changes in above code?

## What JavaScript Errors Have You Seen While Reproducing This Bug?
Uncaught TypeError: a(...).baldrick is not a function
Refer this - http://tinyurl.com/y4omfhfg

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera Forms Version: 1.8.1
WordPress Version: 5.1
PHP Version: 7.2.3

**Comment by Shelob9** [comment] 2019-03-06 11:54
@sushmak02 Thanks for the report. I wanted to point out that we really want to help you and your users fix this bug very much. If during your development and testing you could test with and without the `caldera_forms_render_assets_minify` filter set to prevent minification of JavaScript and CSS that would really help. The error you're seeing it's hard to make sense of because it's coming from minified JavaScript. If you sent us errors with and without the assets minfied, that would help us a ton.

https://calderaforms.com/doc/caldera_forms_render_assets_minify/

Two questions:

1) Is this a different issue then #3042?

2) I do not see any forms on the page, is this only an issue with

**Comment by Shelob9** [comment] 2019-03-06 11:54
@sushmak02 Thanks for the report - 

I do not see any forms on the page, is this only an issue when there are no forms on the page? In which case this can be fixed via #3047 

Possibly a duplicate of #3042

**Comment by Shelob9** [comment] 2019-03-06 11:55
@sushmak02 I want to add that we really want to help you and your users fix this bug very much. If during your development and testing you could test with and without the `caldera_forms_render_assets_minify` filter set to prevent minification of JavaScript and CSS that would really help. The error you're seeing it's hard to make sense of because it's coming from minified JavaScript. If you sent us errors with and without the assets minfied, that would help us a ton.

https://calderaforms.com/doc/caldera_forms_render_assets_minify/

**Comment by sushmak02** [comment] 2019-03-06 13:48
@Shelob9 Thanks for looking into our issue.

This JS error appears all over the site and due to this any JS event on my site are not working.

After adding the `caldera_forms_render_assets_minify` filter it fixes the existing issue. But, while first time page is opened in Elementor editor this new issue appears in the console of the page - http://tinyurl.com/y2eweh8q

**Comment by Shelob9** [comment] 2019-03-06 13:54
Thanks. Did you do that test on a page with forms or a page without? There
were no forms on the URL you sent.

After we push out 1.8.2, I can look more into this, but I'd love to know
the answer to that.

**Comment by sushmak02** [comment] 2019-03-06 13:59
@Shelob9 This error appears even after adding the caldera form on the page. I have sent you details of my site by mail. Can you please login to the site and check the issue?

**Comment by sushmak02** [comment] 2019-03-07 04:52
@Shelob9 I have sent you the details on the above email. Please check. 
This is just a test site so you can make any changes on it.

**Comment by Shelob9** [comment] 2019-03-07 17:59
@sushmak02 I do not see any emails from you. If you attached a zip file, Gmail doesn't deliver it. That might explain. Can you try again please or dm me in WordPress slack - @shelob9

**Comment by Shelob9** [comment] 2019-03-07 20:24
@sushmak02  Are you still getting this error with 1.8.2 ?

**Comment by sushmak02** [comment] 2019-03-08 05:22
@Shelob9 I have sent you the details on WordPress slack.
I am still facing the issue even after the 1.8.2 update. Now, this error appears while editing the page with Elementor - http://tinyurl.com/y62czana

**Comment by swapnilmanjrekar** [comment] 2019-03-13 15:13
@Shelob9 @New0  @sushmak02 
-  **According to my testing & findings, I don't see this as a bug as I didn't encounter any JavaScript errors while testing this issue with default Caldera Forms styler widget by Ultimate Add-On for Elementor plugin, Elementor plugin & CF plugin installed on my local Lando WordPress test site**   


**I checked this Issue  using the following steps:**

- I created a  WordPress test site on my desktop locally using Lando.
- I installed & activated Caldera Forms plugin on my WordPress test site.
- I tested this on the latest dev branch of Caldera Forms.
- I installed & activated the Elementor plugin on my WordPress test site.
- I installed & activated Ultimate Add-On for Elementor plugin on my WordPress test site
- Next, under templates tab of Elementor, I selected page and named it test page and created the template.
- On the created template page from the list of available widget under Elementor Customizer Tab, I dragged & added the Caldera Forms Styler Widget by Ultimate Add-On for Elementor plugin 
- I opened the console of my browser and I expected to see no JavaScript Errors in the console of my browser
- I was not able to see any JavaScript errors when I checked the console of my browser and it was as per my expectations.
- I tested this on Google Chrome, Mozilla Firefox, and Microsoft Edge Browsers.


**PHP Errors:**

- When I checked the debug.log file of my local WordPress test site I didn't see any PHP errors. 

**JavaScript Errors:**

- When I checked the console of my browser I didn't see any JavaScript errors.





WordPress Version: 5.1.1PHP Version: 7.1.26MySQL Version: 5.7.25Caldera Forms Version: 1.8.2WP_DEBUG: 1

**Comment by sushmak02** [comment] 2019-03-16 05:19
Hey @swapnilmanjrekar  
Thanks for debugging the issue. 

This issue happens when the caldera form is not added on the Elementor page and with UAE 1.9.2.
We have added a fix for this issue in UAE with the help of @Shelob9

**Comment by Shelob9** [comment] 2019-03-28 14:15
This was fixed in 1.8.3

**Closed by Shelob9** 2019-03-28 14:15 UTC
Labels: Bug
