### ISSUE TITLE
Weird looking code / text in submission for clicking drop box

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1428] opened 2017-03-22 08:16 UTC
Hey

This is an older issue that was fixed but it is showing up in recent minor versions of CF again.
The following is a checkbox in an older form.

WP backend submission page:

![screen shot 2017-03-22 at 09 17 19](https://cloud.githubusercontent.com/assets/5323259/24188118/607e1e80-0ee0-11e7-8f1b-2727f2eacc03.png)

Received admin e-mail submission:

![screen shot 2017-03-22 at 09 10 21](https://cloud.githubusercontent.com/assets/5323259/24188110/5428fc4a-0ee0-11e7-9203-00e64047066c.png)

Josh do you need anything else?
It is probably a good idea to rename the title..:)

**Comment by Shelob9** [comment] 2017-03-22 14:48
Closing as duplicate of #1410

**Closed by Shelob9** 2017-03-22 14:48 UTC
