### ISSUE TITLE
Easier access to using Caldera Forms shortcode

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#581] opened 2016-05-06 17:02 UTC
Hey

I have a client who needs easy access to the Caldera Forms shortcode. The way I know of today is to go to a page/post and add a Caldera Form. Then go to text view and copy/cut the shortcode.
It would be nice to have easier access to shortcodes for the various forms.

**Comment by Desertsnowman** [comment] 2016-05-06 17:07
Why is this needed? Where are they using the shortcode?

**Comment by Shelob9** [comment] 2016-05-06 17:15
@paaljoachim This is planned for 1.3.6

@Desertsnowman  It was explained to me the the Visual Composer plugin, which is VERY popular makes our shortocde button invisible.

Closing as a duplicate of #565

**Closed by Shelob9** 2016-05-06 17:15 UTC

**Comment by Desertsnowman** [comment] 2016-05-06 17:16
Oh right that one. Got it.

**Comment by paaljoachim** [comment] 2016-05-06 18:35
Ok. Good.
My client uses Optimizepress where the shortcode is needed to show Caldera Forms.
