### ISSUE TITLE
500 Error on website until Caldera plugin is deactivated

### ISSUE THREAD

**Issue by KeyesNA** [CalderaWP/Caldera-Forms#2587] opened 2018-06-06 14:23 UTC
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by Shelob9** [comment] 2018-06-06 14:52
This is a duplicate of #2574

Can you please leave a list of plugins you have active and your theme as comment on that issue?

**Comment by KeyesNA** [comment] 2018-06-06 15:11
Theme: INOVADO
Plugins Currently Running: (Caldera Forms and Authorize.net for Caldera Forms are currently deactivated)
* Askimet Anti-Spam
* All In One SEO Pack
* Black Studio TinyMCE Widget
* Contact Form 7
* FlexSlider
* Google Analytics
* Google Analytics Dashboard for WP
* HubSpot Marketing Plugin
* HubSpot Tracking Code for Wordpress
* JS & CSS Script Optimizer
* Photo Gallery
* Popup Builder Exit intent
* Popup Builder PRO
* Really Simple CAPTCHA
* Really Simple SSL
* Revolution Slider
* SMK Sidebar Generator
* Smush
* Spam Free Wordpress
* Tawk.to Live Chat
* Ultimate Member
* UpdraftPlus - Backup/Restore
* WP Edit
* WP Fastest Cache (and Premium)
* WP Mail SMTP
* WP Minify
* WP SendGrid SMTP
 
Ian R. Wood
Marketing
459 Watertown Street
Newton, MA  02460-1451
(617) 964-6180 ext. 133
ian.wood@keyesweb.com

**Comment by Shelob9** [comment] 2018-06-07 18:10
Please see: https://github.com/CalderaWP/Caldera-Forms/issues/2574#issuecomment-395513798

Duplicate of #2594 (reverse timeline)

**Closed by Shelob9** 2018-06-07 18:10 UTC
Labels: duplicate

**Comment by KeyesNA** [comment] 2018-06-08 15:56
New (related) Issue: Yesterday morning I turned back our version of WordPress to 4.9.5 and it fixed the 500 error with both Caldera Forms and Ultimate Member activated and all seemed fine... However, when someone submits a Caldera Form it acts as though it is working with the faded screen, but the "wheel" keeps spinning and the successful submission message never pops up. The form, however, is submitted and I receive an email.
 
Ian R. Wood
Marketing
459 Watertown Street
Newton, MA  02460-1451
(617) 964-6180 ext. 133
ian.wood@keyesweb.com
