### ISSUE TITLE
JS events on site are not working

### ISSUE THREAD

**Issue by sushmak02** [CalderaWP/Caldera-Forms#3029] opened 2019-02-28 06:02 UTC
The JS events on my site are not working. Below is the JS error that I can see in the console - 
caldera-forms-front.min.js?ver=1.8.0:1 Uncaught TypeError: a(...).baldrick is not a function

**Comment by Shelob9** [comment] 2019-02-28 12:03
Closing as a duplicate of 
#3021

**Closed by Shelob9** 2019-02-28 12:03 UTC

**Comment by sushmak02** [comment] 2019-03-01 05:39
I am still facing the same issue after updating to the latest version.
Refer this screenshot - http://tinyurl.com/y5fbakqa

We need to fix this on high priority. Can you please check this?

We will be very grateful for your any help.

**Comment by sushmak02** [comment] 2019-03-04 04:47
@Shelob9 I am facing the above issue from version 1.8.0 update. And this issue is not only related to form submission. It has broken all my site. The JS events and forms on my site are not working.

About this error-  http://tinyurl.com/y5fbakqa
It's constantly appearing on my site.
