### ISSUE TITLE
PDF is not being attached if a file was uploaded to the form

### ISSUE THREAD

**Issue by evolluti0n** [CalderaWP/Caldera-Forms#3258] opened 2019-06-07 18:00 UTC
## Do You Need Immediate Help?
https://secure.helpscout.net/conversation/872745265/21460?folderId=832038

## Is This A Feature Request?
No. I think is a bug

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.2.1
PHP Version: 7.3.6
MySQL Version: 5.7.26
Caldera Forms Version: 1.8.5

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
I created a layout in Caldera Forms Pro. In my form, I am using it for both, email and PDF. In Pro tab, I activated the option 'Attach PDF to Main Mailer'. If no file is uploaded at the time of filling out the form, the PDF is generated correctly and attached to the message that is received by electronic mail.

If a file is uploaded, then, in the message sent by mail, only the uploaded file arrives attached and not the PDF.

## What PHP Errors Have You Logged While Reproducing This Bug?
No errors. 

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No errors. 

[demo-file-uploader-export.zip](https://github.com/CalderaWP/Caldera-Forms/files/3267108/demo-file-uploader-export.zip)

**Comment by New0** [comment] 2019-07-10 14:37
Hello @evolluti0n , thank you for sharing, I could reproduce the issue. 

My first tests indicate that when files loaded in the form are attached to the email, the pro enhanced delivery is not working and the email is sent via regular WordPress mailer. ( Which don't create the pdf file )

**Comment by Shelob9** [comment] 2019-07-10 14:45
@New0 We had issues where you could only have one file attached, that we fixed in 1.8.5. Right? That also effected the attachment of PDF -- there could only be one attachment in the array of attachments. 

I __assume__ the issue is related to that. That assumption is based on the assumption that PDF generation works, in general. If you turn off attaching PDF and turn on showing the download link, does the download link work?

**Comment by New0** [comment] 2019-07-11 14:31
Note for state of research: when a file is attached, the request to pro ( `$request = wp_remote_request($url, $args);` ) at l55 from includes/cf-pro-client/api/api.php returns a 500 error

**Comment by New0** [comment] 2019-07-17 10:30
Note for state of research: in my local app the error happened only when the option to attach a PDF to the email was enabled, with or without a file from files field attached to the email.
I found the error happening at app/message.php l75 ( $snappy->getOutputFromHtml() returned an exception ).

@Shelob9 : Although I'm not using vagrant, I solved the issue locally using the method described at https://github.com/barryvdh/laravel-snappy#attention-vagrant-users 
 
Steps to solve \:
ssh in environment
( `lando ssh` locally )

then
````
cp vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64 /usr/local/bin/
cp vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 /usr/local/bin/
chmod +x /usr/local/bin/wkhtmltoimage-amd64 
chmod +x /usr/local/bin/wkhtmltopdf-amd64
````

**Comment by New0** [comment] 2019-07-17 10:38
Note: the error described only happen when multiple files from the files field are attached to the email. In the case that the files field attach one file and the pdf attachment option is enabled, the email is correctly delivered through pro enhanced delivery with both files attached.

**Comment by New0** [comment] 2019-07-17 12:39
This has been worked on at https://gitlab.com/caldera-labs/caldera-forms-pro-app/merge_requests/40

**Comment by New0** [comment] 2019-07-22 08:41
@evolluti0n could you test that issue again please ? This should be fixed.

**Comment by New0** [comment] 2019-07-23 12:05
https://gitlab.com/caldera-labs/caldera-forms-pro-app/merge_requests/40

**Closed by New0** 2019-07-23 12:05 UTC
Labels: Bug, Priority Support, bug:major
