### ISSUE TITLE
Star rating fields don't have a default setting or respect default when rendered

### ISSUE THREAD

**Issue by cicichirinos** [CalderaWP/Caldera-Forms#1345] opened 2017-03-03 03:00 UTC
https://wordpress.org/support/topic/star-ratings-defaulting-to-2-stars/#post-8868429 - reported here, not replicated by me sorry

**Comment by beachgrrrl** [comment] 2017-03-26 18:21
Having the same problem - WordPress 4.7.3, Caldera 1.5.0.6

**Comment by Shelob9** [comment] 2017-04-23 00:31
Closing as dupe of #1520 - even though that's backwards, but that one has a PR.

**Closed by Shelob9** 2017-04-23 00:31 UTC
