### ISSUE TITLE
Invalid argument supplied for foreach() inclasses/forms.php on line 421

### ISSUE THREAD

**Issue by mzfgit** [CalderaWP/Caldera-Forms#2575] opened 2018-06-03 10:52 UTC
This A Feature Request.

Version Of Caldera Forms: 1.7.0 Active
Version Of WordPress: 4.9.6
Version Of PHP Are You Using: 7.0.30

**The Unexpected Behaviour**

supplied for foreach() in /home/domainname/public_html/wp-content/plugins/caldera-forms/classes/forms.php on line 421

![image 2018-06-03 at 6 50 57 pm](https://user-images.githubusercontent.com/22757786/40885751-1e5401ea-675f-11e8-93e7-4a996269b1a3.png)

**Comment by Shelob9** [comment] 2018-06-04 16:09
@mzfgit Thanks for reporting this. It should go away once there are saved forms.

1df8a54 fixes this issue.

**Comment by Shelob9** [comment] 2018-06-04 16:10
Also duplicate of #2569

**Closed** 2018-06-06 21:53 UTC
Labels: Bug, duplicate

**Comment by tariq55** [comment] 2019-03-20 08:29
Warning: file_get_contents(http://www.youpload.co/api/dizibox/pcount): failed to open stream: Connection refused in /srv/disk8/2994429/www/zaracova.atwebpages.com/wp-content/plugins/YoupBot/index.php on line 99

Warning: file_get_contents(http://www.youpload.co/api/dizibox/): failed to open stream: Connection refused in /srv/disk8/2994429/www/zaracova.atwebpages.com/wp-content/plugins/YoupBot/index.php on line 120

Warning: Invalid argument supplied for foreach() in /srv/disk8/2994429/www/zaracova.atwebpages.com/wp-content/plugins/YoupBot/index.php on line 125
