### ISSUE TITLE
Only first letter of data is shown & exported IF PHP VERSION IS OUT OF DATE

### ISSUE THREAD

**Issue by wouterke** [CalderaWP/Caldera-Forms#2159] opened 2017-12-19 16:55 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?

WordPress Version: 4.9.1PHP Version: 5.3.29MySQL Version: 5.7.18Caldera Forms Version: 1.5.7.1WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?

Yes

## What Is The Unexpected Behaviour?

I only see the first letter of any data in the entry view + in the exports: 

![image](https://user-images.githubusercontent.com/34688008/34168688-76957a20-e4e5-11e7-976b-5875fea63d67.png)

![image](https://user-images.githubusercontent.com/34688008/34168733-994af586-e4e5-11e7-8de3-fc60dc5078c6.png)

## What PHP Errors Have You Logged While Reproducing This Bug?

Did not check. 

## What JavaScript Errors Have You Seen While Reproducing This Bug?

None

**Comment by Shelob9** [comment] 2017-12-20 19:43
@wouterke  Thanks for using Caldera Forms and reporting this bug. I will have to build an environment with PHP5.3 to test this.

I suspect this is specific to your -- very out of date -- version of PHP. Can you try updating to PHP 5.6 or PHP7? You want to do that anyway as your version has reached end of life.

**Comment by Shelob9** [comment] 2017-12-21 17:56
@wouterke I can confirm this is an issue in PHP 5.3 or lower. Please upgrade to PHP 5.6 or later and you should be fine.

This will get fixed in 1.5.9 unless, we are going to drop PHP 5.5 or lower support for 2018 as I want to.

**Comment by wouterke** [comment] 2017-12-22 09:11
Thanks Josh for checking!

I indeed need to upgrade my PHP version.

Have a great day

W.

**Comment by Shelob9** [comment] 2017-12-26 19:09
This is a regression of what was fixed here: 
8db855e #1027

**Comment by donikatz** [comment] 2018-01-24 23:15
Didn't make it into 1.5.9. Any idea yet whether it will be in 1.5.9.x or 1.6.0, or whether PHP 5.3 support will be dropped? Thanks

**Comment by Shelob9** [comment] 2018-04-19 00:27
I am closing this since PHP 5.3 support is no longer provided #2390

**Closed by Shelob9** 2018-04-19 00:27 UTC
Labels: Bug, Needs Research
