### ISSUE TITLE
1.6.2  input masks do not work anymore

### ISSUE THREAD

**Issue by knireis** [CalderaWP/Caldera-Forms#2499] opened 2018-05-15 10:27 UTC
from 1.6.2  input masks don't work anymore, tested on chrome and firefox

**Comment by Shelob9** [comment] 2018-05-15 14:05
@knireis Thanks for the report. I am working on this now.

Closing as duplicate of #2500

**Closed by Shelob9** 2018-05-15 14:05 UTC
Labels: duplicate

**Comment by Shelob9** [comment] 2018-05-15 14:26
Fixed via e7cc6bd

Thanks again for reporting!
