### ISSUE TITLE
Conditionals not showing correct calculation values

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#3040] opened 2019-03-01 15:25 UTC
The following is a calculator using a lot of conditionals.

Live site:
https://celias.no/bestilling/

<img width="354" alt="screen shot 2019-03-01 at 16 12 23" src="https://user-images.githubusercontent.com/5323259/53647526-091c4f80-3c3e-11e9-8d87-17bd799b6dc1.png">

Dev site:
https://celias.no/dev/bestilling/

<img width="356" alt="screen shot 2019-03-01 at 16 12 36" src="https://user-images.githubusercontent.com/5323259/53647581-26511e00-3c3e-11e9-93e0-716edee5203e.png">

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.8PHP Version: 7.0.33MySQL Version: 5.5.5Caldera Forms Version: 1.8.1WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No errors seen in the console or turning on wp bug to true.

It starts out looking ok. Upon moving the sliders the number become distorted. Upon refresh of the page the calculator resets back to original values.
![conditionals-caldera-forms](https://user-images.githubusercontent.com/5323259/53647665-4e408180-3c3e-11e9-8c40-c95ae5f84b3c.gif)

Json export of the calculator.
https://www.dropbox.com/s/v0e9ti77cd2y3cp/dugnadskalkulator-2018-export.json?dl=0

**Comment by swapnilmanjrekar** [comment] 2019-03-01 17:55
-  **According to my testing & findings, I think this is a bug as I was not able to see a range number after moving the range slider in each of range slider field of the imported form.**


**I checked this bug using the following steps:**

- I created a  WordPress test site on my desktop locally using Lando.
- I installed Caldera Forms plugin on my test site.
- Using the Caldera Forms plugin, I imported the form provided by @paaljoachim 
- I saved and loaded the imported form.
- In the range slider field of the imported from, I expected to see a set range interval number after moving the range slider in each of the range slider fields of the imported form.
-  But when I moved the scale in each of  range slider field, instead of showing a range number it was showing me field id in front of the range slider field of the imported form and it was not as per my expectations.
-  I tested this on Google Chrome, Mozilla Firefox and Microsoft Edge Browser in Windows 10.

![test 3040](https://user-images.githubusercontent.com/43219826/53656275-d2840c00-3c20-11e9-9e6b-95936ac227aa.gif)






**Javascript Errors:**

- When I checked the console of my web browser I didn’t see any javascript errors.


**PHP Errors:**

- When I checked the debug.log file of my WordPress test site I did not see any PHP errors.


WordPress Version: 5.1PHP Version: 7.1.26MySQL Version: 5.7.25Caldera Forms Version: 1.8.1WP_DEBUG: 1

**Comment by paaljoachim** [comment] 2019-03-02 11:39
Thank you for confirming @swapnilmanjrekar

**Comment by mn4mac** [comment] 2019-03-02 22:42
I do have the same problems with my contact form. Using 4 different sliders and start moving them, they all show the field-id instead of the value. Hope, this bug will be fixed soon!!!
<img width="1680" alt="bildschirmfoto 2019-03-02 um 23 19 00" src="https://user-images.githubusercontent.com/48165647/53688474-cb561e80-3d44-11e9-8729-56022abb0392.png">

**Comment by Shelob9** [comment] 2019-03-06 16:48
#3043 is proabably a duplicate of this. @New0 is describing the root cause of the issue and I am seeing this issue when there are sliders with develop branch and it is resolved with PR #3045

**Comment by Shelob9** [comment] 2019-03-06 16:55
This is probably fixed via #3043 I am moving to 1.8.3 milestone.

If I'm right, updating to 1.8.2 fixes this. If I'm wrong, we look harder next week.

**Comment by paaljoachim** [comment] 2019-03-06 21:58
Josh when it is ready please share a link to a dev version I can test. Thanks.

**Comment by Shelob9** [comment] 2019-03-06 22:16
@paaljoachim Thanks for offering to test. I just added a rc build for 1.8.3 here -> https://github.com/CalderaWP/Caldera-Forms/pull/3052#issuecomment-470297981

**Comment by Shelob9** [comment] 2019-03-07 19:25
close via #3043

**Closed by Shelob9** 2019-03-07 19:25 UTC
Labels: Bug
