### ISSUE TITLE
Calculation fields not updated on first click - sample form attached

### ISSUE THREAD

**Issue by hahntech** [CalderaWP/Caldera-Forms#1979] opened 2017-09-29 19:09 UTC
## Do You Need Immediate Help?
no

## Is This A Feature Request?
no

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8.2PHP Version: 5.6.30MySQL Version: 5.6.32Caldera Forms Version: 1.5.6.1

The issue has been observed on Mac Safari and Chrome as well as Windows Edge and Chrome. Oh, and iPad Safari too. 

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
yes, tested on brand new WP install with no other plugins added.

## What Is The Unexpected Behaviour?
values for hidden fields are not properly handled in calculation fields when conditions are met. You must click the checkbox, un-check and then re-check before the values of the hidden fields are properly handled. In the attached sample form, you should be able to check the first and second boxes and immediately see the discount of 10 applied. But it does not. Instead you must check the first and second box, un-check the second box, then re-check it. A summary field is included in the form so that you can observe the values being assigned to the hidden fields.

Expected behavior:
If item 1 is checked, no discount. If items 1 and 2 are checked, 10 dollar discount. If items 1, 2, and 3 are checked, discount is 10 + 20. We should not have to click a box 3 times to get the form to calculate.

Replication:
Built a form that calculates prices and discounts based on selection of a checkbox element. Added sub total, discount and grand total calculated fields. Added hidden fields to contain the discount amounts. created conditions set to 'show' each hidden field based on user selection. Example form is attached. You can easily import this into Caldera and test it yourself. 

## What PHP Errors Have You Logged While Reproducing This Bug?
absolutely no PHP errors appeared while WP_DEBUG set to true

## What JavaScript Errors Have You Seen While Reproducing This Bug?
absolutely no javaScript errors were observed in the developer tools console

[bug-report-export.json.zip](https://github.com/CalderaWP/Caldera-Forms/files/1345399/bug-report-export.json.zip)

**Comment by hahntech** [comment] 2017-10-05 20:44
Any chance this issue has been addressed already? I checked the conditinals.js code against what I have in my current version. I see some changes dealing with the hidden fields. And at the top of conditionals.js I see a note about [#1918](https://github.com/CalderaWP/Caldera-Forms/issues/1918) That issue seems similar to mine, but lacks much detail. Just trying to save some time.

**Comment by Shelob9** [comment] 2017-10-05 21:04
@hahntech Have you tested with 1.5.6.2 -- ie the latest from Github? I think this is fixed via #1962 but will test. If you could do the same, I'd appreciate.

**Comment by hahntech** [comment] 2017-10-05 21:09
I would love to give it a test on 1.5.6.2, but not sure the details of how to go about doing that. Is just as simple as clicking the "clone or download" button, saving as .zip, then loading that zip into WordPress just like any plugin?

**Comment by Shelob9** [comment] 2017-10-05 21:10
Yes, you can do that. Just make sure you don't end up with two copies installed at once.

I really recommend using the plugin WP Pusher for installing and updating plugins from Github.

**Comment by hahntech** [comment] 2017-10-05 21:13
I can do this on a local WP installation and make sure I uninstall the current version of the plugin before loading the new one. Should I google "WP Pusher"? Never heard of that before.

**Comment by Shelob9** [comment] 2017-10-05 21:19
https://wppusher.com/

**Comment by hahntech** [comment] 2017-10-05 23:22
Tested and confirmed this behavior is exactly the same in version 1.5.6.2-b. Sorry.

**Comment by Shelob9** [comment] 2017-10-06 00:20
Ok, thanks for trying that. Do you know what version it last worked in? If so, you can use WP Rollback to rollback to that version and that would also be very helpful to me to know when testing your form.

https://wordpress.org/plugins/wp-rollback/

**Comment by hahntech** [comment] 2017-10-06 00:38
Rollback, what an awesome tool. Just took me a few minutes to determine this last worked correctly in Caldera Forms Version: 1.5.5

**Comment by 101010f** [comment] 2017-10-06 12:57
Was just about to post same bug. Even though it outputs an initial 0, conditions won't work. Funny enough the condition works after a second condition is met. 
Nice plugin suggestion for wp-rollback btw. Is it safe database wise?

**Comment by Shelob9** [comment] 2017-10-06 22:32
@hahntech I'd do a DB backup first to be safe, but it should be fine. Ask @mathetos if you have WP Rollback questions.

**Comment by Shelob9** [comment] 2017-10-06 22:33
@hahntech Also, thanks for letting me know what version worked. I am setting up a regression test verus 1.5.5 with your form right now.

**Comment by mathetos** [comment] 2017-10-06 23:02
@hahntech -- we put warning all over Rollback about DB backups because Rollback does NOT touch the database at all. So if your plugin makes changes to the DB structure between versions, those aren't going to be changed and that might result in wackiness. WooCommerce is a prime example, they often have DB changes between versions. 

Think of Rollback like finding a branch or release ZIP on Github and just swapping out the files. That's essentially what it does, but with SVN via wordpress.org

Thanks!

**Comment by Shelob9** [comment] 2017-10-06 23:07
@mathetos - Thanks for the info. Fun fact, Caldera Forms database changes for storing forms are major -- options table vs custom table. Right now, we're still updating both places, but only reading from the new way. I did it this way so if their were issue with that conversion, people could roll back with WP Rollback.

**Comment by mathetos** [comment] 2017-10-06 23:16
Nice! I wish more plugin authors would take Rollback into account between versions. There's some hooks in place that you could even include a rollback routine if you wanted. We keep saying we want to create docs for that but never got around to it.

**Comment by Shelob9** [comment] 2017-10-06 23:18
I need those delicious Matt  docs.

**Comment by Shelob9** [comment] 2017-10-07 01:25
Test https://app.ghostinspector.com/tests/59d828c430e3b074c50ccf39 reproduces this bug.
Test shows that when you start discount is 0, but when clicking checkbox option 2, the discount does not become 10, which it should. Test also asserts that unchecking option 2 and rechecking also gets the result of 10, and tests adding option 3 to get a discount of 30.

All assertions in this test pass at version 1.5.5. Assertion `#3
 .last_col > .form-group:nth-of-type(1) > div > h3.total-line > span contains text 10.00 TEXT NOT CONTAINED` does not pass at 1.5.6.1

Must make all assertions pass to know this is fixed.

**Comment by Shelob9** [comment] 2017-10-07 01:54
Why is the initial value wrong -- because state is initialized with the wrong value -
![screenshot from 2017-10-06 21-39-14](https://user-images.githubusercontent.com/1994311/31303672-9f62f5a8-aadf-11e7-82f4-6004e494135b.png)

Why are all of those values null? The answer to that probably == the solution to this bug, possibly ===.

Those get set in [`Caldera_Forms_Field_JS::map_field()`](https://github.com/CalderaWP/Caldera-Forms/blob/f43c3502a3960ba26be9240ddbe8f9fab547ef8f/classes/field/js.php#L699) Which is not where the problem is. The problem is `Caldera_Forms_Field_Util::get_default_calc_value()` the function I added, in this milestone. That leads us to this fellow:

![screenshot from 2017-10-06 21-40-41](https://user-images.githubusercontent.com/1994311/31303706-2192588e-aae0-11e7-9115-5903d92e13e3.png)

Yes, meet the source of our problem, because hidden fields don't have an index `calc_val` in the array I'm searching in, the return value is `null`. My defensive coding caused a valid structure for a field to be treated as invalid. So, minus 1 point me, but I'm about to fix it, and I just created a repeatable and automated process for testing that this bug is fixed and doesn't come unfixed and I think created a narrative I can edit to be more generic and then function as documentation on troubleshooting. I blame @cicichirinos

**Comment by Shelob9** [comment] 2017-10-07 02:28
359275c is in intentionally bad fix. I want to test that this new acceptance testing can catch a regression. It can, but does the test I devised, which I think this will pass based on behavior of the discount total calculation field, which this issue was about. But this commit makes the other two fields all wrong, so before I commit, let me deploy this branch and confirm that this test would fail. Also, let the dog out.

**Comment by Shelob9** [comment] 2017-10-07 02:33
Nice, my test caught that the other ones were wrong. Lesson: design test to see if other uses of same field type get negatively effected, but assert main functionality.
![screenshot from 2017-10-06 22-32-13](https://user-images.githubusercontent.com/1994311/31304015-40fac4ee-aae6-11e7-9bd6-43ae9a615847.png)

Ok, now really let the dog out.

**Comment by Shelob9** [comment] 2017-10-07 03:40
I totally reverted d33a521 and redid fix so I think it worked and didn't break the other calculators in ea0f0be will update site and retest. BTW I'm not sure I'm in love with this fix. Will start a code review in PR if this passes tests.

Aside, very happy with Ghost Inspector's role in this. Need to script the testing/ branch switching. Tomorrow, I will add tests for other calculation issues we had in 1.5.6.x and also figure out how to automate this, Ghost Inspector does work with Github CI, so that should all be doable.

**Comment by Shelob9** [comment] 2017-10-07 03:44
And it passes 
![screenshot from 2017-10-06 23-43-11](https://user-images.githubusercontent.com/1994311/31304493-24fe11ce-aaf0-11e7-9e56-9ff4867a96df.png)

[You can even watch a video of it](https://ghostinspector-prod.s3.amazonaws.com/videos/dce48ad0-f539-4805-b1de-b551d2948219.mp4)!!

**Comment by hahntech** [comment] 2017-10-07 04:00
Sweet! Well done @Shelob9

**Comment by Shelob9** [comment] 2017-10-12 01:39
Close via 
7164eba

**Closed** 2017-10-12 01:39 UTC
Labels: Bug, bug:major
