### ISSUE TITLE
"Name" field not displaying

### ISSUE THREAD

**Issue by WilliamUnsung** [CalderaWP/Caldera-Forms#2630] opened 2018-06-21 15:49 UTC
## Do You Need Immediate Help?
No, just can't get past this little bug...

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
all current and up-to-date

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
- Disable all my plugins!? I'm not doing that lol
- I believe I'm using the default theme

## What Is The Unexpected Behaviour?
https://unsungstudio.com/contact/#request-a-quote
The final text field doesn't display the "Name" or instructions I have here that says, "Please provide as much information and detail as possible."

## What PHP Errors Have You Logged While Reproducing This Bug?
I don't know PHP :(

## What JavaScript Errors Have You Seen While Reproducing This Bug?
I don't know JavaScript :(

**Comment by Shelob9** [comment] 2018-06-26 18:14
Thanks for using Caldera Forms.

I tested this with just Caldera Forms and was unable to reproduce the problem. This suggests it is a site-specific issue, not a bug with Caldera Forms.  I am closing this issue.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support

**Closed by Shelob9** 2018-06-26 18:14 UTC
