### ISSUE TITLE
PHP errors in v1.5.8.1 in "Pro"-Tab in edit mode

### ISSUE THREAD

**Issue by doffine** [CalderaWP/Caldera-Forms#2180] opened 2017-12-22 11:40 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.1PHP Version: 7.1.12MySQL Version: 5.5.58Caldera Forms Version: 1.5.8.1WP_DEBUG: 

## What Is The Unexpected Behaviour?
Hello,

we just updated Caldera Forms in some of our Wordpresses from v1.5.7.1 to v1.5.8.1. After this we find a new tab in edit mode of a form right next to the Responsive-Tab called "Pro" (for "Caldera Forms Pro Settings For This Form"). Clicking on this tab produces just ugly PHP error messages / warnings but no content page:

Warning: include(/home/USERNAME/DOMAINNAME/wp-content/plugins/caldera-forms/includes/cf-pro-client/build/tab.php): failed to open stream: No such file or directory in /home/USERNAME/DOMAINNAME/wp-content/plugins/caldera-forms/ui/edit.php on line 932

Warning: include(): Failed opening '/home/USERNAME/DOMAINNAME/wp-content/plugins/caldera-forms/includes/cf-pro-client/build/tab.php' for inclusion (include_path='.:/usr/local/pd-admin2/php-7.1.12/lib/php') in /home/USERNAME/DOMAINNAME/wp-content/plugins/caldera-forms/ui/edit.php on line 932

As stated above this error occurs on more than one individual Wordpress on different servers, with different themes and plugins co-installed.

Many greetings,
Matthias Scholz

## What PHP Errors Have You Logged While Reproducing This Bug?
Warning: include(/home/USERNAME/DOMAINNAME/wp-content/plugins/caldera-forms/includes/cf-pro-client/build/tab.php): failed to open stream: No such file or directory in /home/USERNAME/DOMAINNAME/wp-content/plugins/caldera-forms/ui/edit.php on line 932

Warning: include(): Failed opening '/home/USERNAME/DOMAINNAME/wp-content/plugins/caldera-forms/includes/cf-pro-client/build/tab.php' for inclusion (include_path='.:/usr/local/pd-admin2/php-7.1.12/lib/php') in /home/USERNAME/DOMAINNAME/wp-content/plugins/caldera-forms/ui/edit.php on line 932

## What JavaScript Errors Have You Seen While Reproducing This Bug?
no JavaScript errors

**Comment by Shelob9** [comment] 2017-12-22 13:46
Thanks for using Caldera Forms, sorry about this bug.


Here: https://github.com/CalderaWP/Caldera-Forms/blob/master/includes/cf-pro-client/bootstrap-cf-pro.php#L35 tab is included, but it's coming from build dir for client UI, which is not included in WordPress.org version : https://github.com/CalderaWP/Caldera-Forms/blob/master/Gruntfile.js#L36 

Solution is either to have webpack copy tab to dist dir, or in file list include that path (should override the exclude).

**Comment by Shelob9** [comment] 2017-12-22 14:03
Close via 
36611bd

**Comment by doffine** [comment] 2017-12-22 14:57
You write "Solution is either to have webpack copy tab to dist dir, or in file list include that path (should override the exclude)." - but I don't understand what you mean how to solve the problem.
Is it that you will solve this bug in a (nearer) future version of the plugin?

**Comment by Shelob9** [comment] 2017-12-22 15:02
@doffine Sorry if that was confusing, that was me explaining the root cause of the issue. I do that to help me or who ever else is doing the fix understand the issue and to create a record of what the reason for changing code was. 

This is now fixed via 36611bd which is included in version 1.5.8.2. Version 1.5.8.2 will be released on WordPress.org shortly -- I'm committing the new version now.

**Comment by Shelob9** [comment] 2017-12-22 15:53
1.5.8.2 is now out.

**Closed by Shelob9** 2017-12-22 15:53 UTC
Labels: Bug, bug:major
