### ISSUE TITLE
Not passing vars from select fields to calculate

### ISSUE THREAD

**Issue by quornik** [CalderaWP/Caldera-Forms#1950] opened 2017-09-14 13:27 UTC
I have a whole lot of forms which are pretty much based on showing calculated vars to user. I upgraded the plugin this morning and the caltulating process stopped working at all. I change values in select fields, and it does not respond. All the calculated fields remain showing 0.00 ... 
The issue looks to be linked to the select's and dropdowns. They are nto passing calculated values. The sliders and number fields work correctly.
I work on PHP 7 server, and the latest caldera plugin version.

**Comment by Shelob9** [comment] 2017-09-14 17:25
@quornik 
Thanks for using Caldera Forms. We can not accept bug reports that do not follow our template.

This is probably a duplicate of #1951 - if not, please open a new issue with all of the request information. Also, you probably should use the plugin to rollback to 1.5.5 until this is fixed.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support

**Closed by Shelob9** 2017-09-14 17:25 UTC
Labels: duplicate

**Comment by Shelob9** [comment] 2017-09-14 18:42
#1953 is probably root issue of all calculation problems
