### ISSUE TITLE
Error when hitting RESEND FORM

### ISSUE THREAD

**Issue by nexgraphics** [CalderaWP/Caldera-Forms#2263] opened 2018-01-27 23:52 UTC
We are getting this bug message when we hit RESEND FORMS

Catchable fatal error: Argument 2 passed to Caldera_Forms_Field_Util::has_field_type() must be of the type array, null given, called in /home/ipxins/public_html/wp-content/plugins/caldera-forms/classes/magic.php on line 46 and defined in /home/ipxins/public_html/wp-content/plugins/caldera-forms/classes/field/util.php on line 361

**Comment by Shelob9** [comment] 2018-01-29 20:09
@nexgraphics Thanks for using Caldera Forms. What version are you using? This looks like #1864 which was fixed in 1.5.6. I just tested to make sure it's working in 1.5.9.1 and could not reproduce this.

**Comment by Shelob9** [comment] 2018-02-19 19:33
We have not heard back in 21 days, closing issue.

**Closed by Shelob9** 2018-02-19 19:33 UTC
Labels: Bug, Needs Feedback From User, Needs Research

**Comment by nexgraphics** [comment] 2018-02-19 23:14
I did respond.  I asked HOW do I update to the new one?????
There is no OBVIOUS update to the plugin.  I don’t 2want to delete then reinstall as we will lose our forms.

Sincerely,

Lee Levy
Nex Graphics
www.nexgraphics.com<http://www.nexgraphics.com>
lee@nexgraphics.com
818.888.8235
