### ISSUE TITLE
Frontend entry list

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1070] opened 2016-12-21 20:17 UTC
The frontend entry list using a shortcode on the same page as the form it belongs to looks like this:

![screen shot 2016-12-21 at 21 14 45](https://cloud.githubusercontent.com/assets/5323259/21404673/abc9b17a-c7c2-11e6-8cf5-d4a0207ed5e1.png)

It disregards the right sidebar.

Placing the same shortcode on its own page looks like this:

![screen shot 2016-12-21 at 21 16 42](https://cloud.githubusercontent.com/assets/5323259/21404711/cc3aa3f6-c7c2-11e6-96f7-195ccd3edbf0.png)

**Comment by Shelob9** [comment] 2016-12-21 20:39
@paaljoachim Two issues here, right?
1) Table is escaping the container.
2) Entry viewer isn't rendering.

In regards to second issue, are you testing while logged in or not? It's not going to work when not logged in, yet which is #1049

**Comment by paaljoachim** [comment] 2016-12-21 22:29
Yeah. I should have made two issues of this.

I am testing a local dev site while I am logged in.

**Comment by Shelob9** [comment] 2017-01-07 02:29
I'm closing this as either a theme issue or related to css which has been changed, beacuse I can't reproduce. @paaljoachim If you can still see this now (or when we get to beta 2) please let me know.

**Closed by Shelob9** 2017-01-07 02:29 UTC

**Comment by paaljoachim** [comment] 2017-01-09 15:42
@Shelob9 
Let me know (along with the url to it) when the next version is out.
Thanks.
