### ISSUE TITLE
Console errors

### ISSUE THREAD

**Issue by teamtacho** [CalderaWP/Caldera-Forms#3117] opened 2019-03-25 07:54 UTC
# PLEASE READ THIS LINE & Then Delete - We need this information to best understand your issue, please answer all questions!

## Is This A Feature Request?
no

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
V 1.8.3

## What Is The Unexpected Behaviour?
no unexpected behaviour so far

## What JavaScript Errors Have You Seen While Reproducing This Bug?
see attachment
![CF console errors 183](https://user-images.githubusercontent.com/35842021/54903200-9f5d3180-4edb-11e9-9f33-13aa558a6e4e.JPG)

**Comment by teamtacho** [comment] 2019-03-25 07:56
Hi you can check with
[https://teamtacho.de/kontakt/](url)

**Comment by New0** [comment] 2019-03-25 13:55
@teamtacho thank you for reporting. Please include the versions you are using when opening an issue. ( WordPress and PHP at least )
In the case you confirm you are using a WordPress version previous to 5.0, this issue is a duplicate of #3103

**Comment by teamtacho** [comment] 2019-03-25 14:40
Sorry for not posting my version data. WordPress Version: 4.9.8 and PHP Version: 7.2.15
I'm looking forward to the next version.

**Comment by Shelob9** [comment] 2019-03-28 14:22
The block script is loaded in the front end, that's wrong and causing the error.
![Screen Shot 2019-03-28 at 10 20 26 AM](https://user-images.githubusercontent.com/1994311/55165155-41cb1e00-5143-11e9-9e02-fb234cdbe4ba.png)

**Comment by Shelob9** [comment] 2019-03-28 15:11
Close via #3126

**Closed by Shelob9** 2019-03-28 15:11 UTC
Labels: Has PR, duplicate
