### ISSUE TITLE
Error 500 after updating 1.7.6

### ISSUE THREAD

**Issue by jeroenrotty** [CalderaWP/Caldera-Forms#2897] opened 2019-01-11 14:31 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.0.3PHP Version: 7.2.14MySQL Version: 5.5.5Caldera Forms Version: 1.7.6

## What Is The Unexpected Behaviour?
Error 500 when adding product in cart... (combined with bPost plugin - probably using a same library?)

## What PHP Errors Have You Logged While Reproducing This Bug?
`Fri Jan 11 15:15:03.397025 2019] [proxy_fcgi:error] [pid 25601:tid 139626341353216] [client 178.119.134.233:57578] AH01071: Got error 'PHP message: PHP Warning:  include(/public_html/wp-content/plugins/caldera-forms/vendor/composer/../monolog/monolog/src/Monolog/ResettableInterface.php): failed to open stream: No such file or directory in /public_html/wp-content/plugins/bpost-shipping/vendor/composer/ClassLoader.php on line 412\nPHP message: PHP Warning:  include(): Failed opening public_html/wp-content/plugins/caldera-forms/vendor/composer/../monolog/monolog/src/Monolog/ResettableInterface.php' for inclusion (include_path='.:/usr/local/php72/lib/php') in public_html/wp-content/plugins/bpost-shipping/vendor/composer/ClassLoader.php on line 412\nPHP message: PHP Fatal error:  Interface 'Monolog\\ResettableInterface' not found in /public_html/wp-content/plugins/caldera-forms/vendor/monolog/monolog/src/Monolog/Handler/AbstractHandler.php on line 24\n', referer: e/webshop/papa-luna-2015/`

This started after the latest update today.

**Comment by Shelob9** [comment] 2019-01-11 15:33
Closing as duplicate of #2896 - TL;DR delete and reinstall. See: https://github.com/CalderaWP/Caldera-Forms/issues/2896#issuecomment-453555311

**Closed by Shelob9** 2019-01-11 15:33 UTC

**Comment by jeroenrotty** [comment] 2019-01-29 12:37
Can you please look into this again Josh?. I've tried reinstalling couple of times, still having this issue when this Caldera is activated and when I add a product in the basket.. (ERR500) - with same error log as before.

**Comment by Shelob9** [comment] 2019-01-29 14:32
@jeronrotty I'm not sure what to tell you here. 

I do not know how you are getting a version of Caldera Forms different then I am. I don't know what you are asking me to do here. We are aware of the issue with the dependency and will avoid it in 1.8.0.


I also do not know what "add a product in the basket" means. Are you saying that you are getting this error only when adding an item to the cart with a eCommerce plugin?

**Comment by jeroenrotty** [comment] 2019-01-29 14:43
Hey Josh,
Still strange then. I'll wait until 1.8 then. Yes, I was referring to when I add a product in the cart (with WooCommerce), only then it happens. Still has something to do with CF together with the other plugin, but I have confidence you'll fix it in 1.8.0.
Thanks again Josh!

**Comment by jeroenrotty** [comment] 2019-01-30 18:20
Hey Josh,

Here I am again. There was an update from the bPost plugin again today which fixes this....
[https://wordpress.org/plugins/bpost-shipping/#developers](url)

Thanks again for your patience and understanding. Looking forward to 1.8 too. Thanks!
