### ISSUE TITLE
Use a placeholder in a Dropdown Select field when hiding the name

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#1726] opened 2017-07-04 09:12 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8PHP Version: 7.0.10MySQL Version: 5.7.14Caldera Forms Version: 1.5.2WP_DEBUG: 1

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Beahviour?
I would like to use a placeholder in a Dropdown Select field when hiding the name.

- when I check the option "Hide name" nothing appears as a placeholder if the placeholder option field is left empty and if I add a value to the placeholder option field, both values of name and placeholder option fields appear in the dropdown select field

**Comment by New0** [comment] 2017-07-04 10:35
Complement of info for #1724

**Comment by Shelob9** [comment] 2017-07-05 21:53
Closing as duplicate of #1724

**Closed by Shelob9** 2017-07-05 21:53 UTC
