### ISSUE TITLE
Form Entries > Resend button results in PHP errors

### ISSUE THREAD

**Issue by ianskate** [CalderaWP/Caldera-Forms#1909] opened 2017-09-04 14:55 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8.1
PHP Version: 7.0.22
MySQL Version: 10.0.31
Caldera Forms Version: 1.5.5

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
Clicking the "resend" button from within a forms Entries panel results in the following errors

`Fatal error: Uncaught TypeError: Argument 2 passed to Caldera_Forms_Field_Util::has_field_type() must be of the type array, null given, called in /home/user/public_html/site.com/wp-content/plugins/caldera-forms/classes/magic.php on line 46 and defined in /home/user/public_html/site.com/wp-content/plugins/caldera-forms/classes/field/util.php:361 Stack trace: #0 /home/user/public_html/site.com/wp-content/plugins/caldera-forms/classes/magic.php(46): Caldera_Forms_Field_Util::has_field_type('credit_card_exp', NULL) #1 /home/user/public_html/site.com/wp-includes/class-wp-hook.php(298): Caldera_Forms_Magic->field_magic(NULL, 'From: %first_na...', Array, NULL, NULL) #2 /home/user/public_html/esite.com/wp-includes/plugin.php(203): WP_Hook->apply_filters(NULL, Array) #3 /home/user/public_html/site.com/wp-content/plugins/caldera-forms/classes/magic/doer.php(57): apply_filters('caldera_forms_p...', NULL, 'From: %first_na...', Array, NULL, NULL) #4 /home/user/ in /home/user/public_html/site.com/wp-content/plugins/caldera-forms/classes/field/util.php on line 361`

**Comment by Shelob9** [comment] 2017-09-04 18:32
Thanks for using Caldera Forms. I'm sorry you are having this bug.

This issue is a duplicate of #1864 which is already fixed. You can download the latest version from Github or wait until 1.5.6 is released on WordPress.org in a week or two.

**Closed by Shelob9** 2017-09-04 18:32 UTC
Labels: duplicate

**Comment by ianskate** [comment] 2017-09-04 19:21
Whoops, sorry about the duplicate submission. Wasn't able to find a relevant result through search. Thanks for the update, will check that out now. Cheers!
