### ISSUE TITLE
Can not add Caldera Forms block to post

### ISSUE THREAD

**Issue by swapnilmanjrekar** [CalderaWP/Caldera-Forms#2860] opened 2018-12-14 20:54 UTC
## Is This A Feature Request?
* No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* WordPress Version: 5.0.1PHP Version: 7.1.25MySQL Version: 5.7.24Caldera Forms Version: 1.7.4WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
* Yes

## What Is The Unexpected Behaviour?
* When I tried to add a Caldera Forms block to a post, using WordPress 5.0.1, in the block editor it is not showing me the option of Caldera Form so I can enter my form into the page which I expected to see.

## What PHP Errors Have You Logged While Reproducing This Bug?
*  "PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /app/wp-content/plugins/caldera-forms/classes/forms.php on line 274".

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* None.

**Comment by Shelob9** [comment] 2018-12-20 17:09
I can confirm that it's not an option. Also, it looks like the JavaScript file for the block is not being loaded, which would explain the issue.

![screen shot 2018-12-20 at 12 06 40 pm](https://user-images.githubusercontent.com/1994311/50299601-03410b80-0450-11e9-901b-c2c2b7118935.png)

**Comment by Shelob9** [comment] 2019-01-03 18:30
@New0 Here is where I was when I gave up. Can you look at this and see if anything jumps out at you? This should not be a mega bug, but like, fuck I can't figure it out https://pastebin.com/pvcRR6V8

**Comment by New0** [comment] 2019-01-04 10:10
@Shelob9 I can't reproduce this issue on the last version stored on WordPress repo. On CF 1.7.5.1 the gutenberg block is working.

**Comment by swapnilmanjrekar** [comment] 2019-01-04 17:59
@New0 I am still not able to see the Caldera Forms Block!

![cf block](https://user-images.githubusercontent.com/43219826/50702324-99635d00-101e-11e9-9e0d-5e6c3c750f63.PNG)


WordPress Version: 5.0.2 PHP Version: 7.1.25 MySQL Version: 5.7.24 Caldera Forms Version: 1.7.5.1 WP_DEBUG: 1

**Comment by New0** [comment] 2019-01-04 19:05
Thank you @swapnilmanjrekar
I'm going to investigate again, could you let me know:
- do you have 'caldera_forms_render_assets_minify' returning false ?
- do you have the Gutenberg plugin installed ? If yes, is it activated?

**Comment by swapnilmanjrekar** [comment] 2019-01-04 19:11
@New0 Yes Caldera Forms block is showing now after activating Gutenberg plugin!

**Comment by New0** [comment] 2019-01-04 19:15
@swapnilmanjrekar that's a good clue, thank you.
Could you uninstall the Gutenberg plugin and try again ?

**Comment by swapnilmanjrekar** [comment] 2019-01-04 19:22
@New0 After uninstalling the Gutenberg plugin, the Caldera Forms block is not showing up!
![cf block ns](https://user-images.githubusercontent.com/43219826/50706538-2365f280-102c-11e9-9bb7-d384c725b0df.PNG)

**Comment by Shelob9** [comment] 2019-01-04 19:57
This is great info -- that it works when Gutenberg is installed. 

I made the mistake of not disabling Gutenberg in my dev environment, which I did update to 5.0. When I started debugging this issue yesterday, I deleted Gutenberg plugin from test site to avoid it being a factor.

**Comment by Shelob9** [comment] 2019-01-04 20:00
@swapnilmanjrekar What version of Gutenberg are you using? I'm about to install 4.6.1 - from end of November. https://github.com/WordPress/gutenberg/releases/tag/v4.6.1

**Comment by swapnilmanjrekar** [comment] 2019-01-04 20:05
@Shelob9 I am using the latest  Version 4.7.1 of Gutenberg.

**Comment by Shelob9** [comment] 2019-01-04 20:08
With CF 1.7.5.1 from WordPress.org,  WP  5.0.2 and Gutenberg 4.7.1, `caldera_forms_register_block()` is called, then `caldera_forms_enqueue_block_assets()` is called, and blocks shows. Same load order with plugin deactivated, but no joy.

**Comment by Shelob9** [comment] 2019-01-04 20:13
In Gutenberg 4.7.1, `enqueue_block_editor_assets` is called in `gutenberg_editor_scripts_and_styles()` and in the main plugin file, it has `add_action( 'admin_enqueue_scripts', 'gutenberg_editor_scripts_and_styles' );`

In WordPress 5.0.2 - the action is doed in `wp-admin/edit-form-blocks.php`

**Comment by Shelob9** [comment] 2019-01-04 21:08
Should be fixed in #2889

**Comment by Shelob9** [comment] 2019-01-08 18:01
Close via  dcf5ac0 #2890

**Closed by Shelob9** 2019-01-08 18:01 UTC
Labels: bug:major
