### ISSUE TITLE
Cloning a form does not clone the 'email' tab settings.

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1420] opened 2017-03-20 10:52 UTC
Cloning a form using the 'clone' button inside the Caldera Forms settings page clones everything except the email tab data. 

This reverts to default settings.

**Comment by Shelob9** [comment] 2018-08-07 17:52
Duplicate of #1282 fixed via 5fe42b8650696ce1852070482debce08c174bdec

**Closed by Shelob9** 2018-08-07 17:52 UTC
Labels: duplicate
