### ISSUE TITLE
The correct approach to send one form to multiple users.

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#2817] opened 2018-11-21 12:18 UTC
I have a reserve a ticket form located here:
https://spirituellfilm.no/pamelding-til-film/

Up to 4 tickets can be reserved.
For each ticket an e-mail is listed.

What I did was the following:
I went to the form and then Email (epost) section.
Filled out the From Email like so.
Reply to Email: %person_1_epost%, %person_2_epost%, %person_3_epost%, %person_4_epost%
It sends out to person 1 but not to person 2,3 or 4 if these are filled out.

EDIT: I then also added person (navn) names and (epost) e-mails to the Auto response section.
Recipient Name: %person_1_navn%, %person_2_navn%, %person_3_navn%, %person_4_navn%
and
Recipient Email:  %person_1_epost%, %person_2_epost%, %person_3_epost%, %person_4_epost%

That seems to work.
What is the correct approach?

## Do You Need Immediate Help?
No.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.8PHP Version: 7.1.23MySQL Version: 10.1.36Caldera Forms Version: 1.7.3WP_DEBUG:

Thanks!

Have a great Thanksgiving Josh!

**Comment by Shelob9** [comment] 2018-11-21 18:10
@paaljoachim happy thanksgiving. This is not a bug, I am closing it. Probably multiple auto-responders is the best way to go.

**Closed by Shelob9** 2018-11-21 18:10 UTC
Labels: Support Request
