### ISSUE TITLE
Caldera Forms auto add empty options in dropdown

### ISSUE THREAD

**Issue by ducminhn** [CalderaWP/Caldera-Forms#1687] opened 2017-06-21 17:47 UTC
##Short Debug Information
WordPress Version: 4.8PHP Version: 5.6.30MySQL Version: 5.6.35Caldera Forms Version: 1.5.1WP_DEBUG: 1

## What Is The Unexpected Beahviour?
* Please explain what you did, what you expected to happen, and what happened instead.

## What PHP Errors Have You Logged While Reproducing This Bug?
The Dropdown Select field is behaving unexpectedly. I just add a simple dropdown with 3 options like the screenshot below:
![screenshot_062117_103938_am](https://user-images.githubusercontent.com/7876935/27398223-ee06edb6-566d-11e7-86b9-42a047a51b47.jpg)

On the front-end, Caldera Forms added 2 empty options in the dropdown as shown below:
![screenshot_062117_103917_am](https://user-images.githubusercontent.com/7876935/27398211-e17f6ed8-566d-11e7-9fbf-ef2d824eddf5.jpg)

Also, the default option feature using magic tag doesn't work properly as well. I was able to do it before but after upgrade WP core to 4.8, I ran to these issue.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No JS error in back and frond end.

Can you guys please take a look to see if this is the incompatible issue? Much appreciate!

Thanks,
Minh

**Comment by Shelob9** [comment] 2017-06-25 01:37
@ducminhn Thanks for usign Caldera Forms and reporting this. It is already fixed via #1699

**Comment by Shelob9** [comment] 2017-06-25 01:37
Close as duplicate of #1699

**Closed by Shelob9** 2017-06-25 01:37 UTC

**Comment by ducminhn** [comment] 2017-06-26 17:01
Awesome, thanks @Shelob9 ! I'm switching from Gravity Forms to Caldera Forms and very excited about this.
