### ISSUE TITLE
Label input css :checked code TRAP

### ISSUE THREAD

**Issue by qbax86** [CalderaWP/Caldera-Forms#1868] opened 2017-08-19 22:46 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
1.5.5 , php 5,6, wordpress 4.8.1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
yes

## What Is The Unexpected Behaviour?
I want to style label of radios and checkboxes, and for proper use it must be that:
```
<div>
<input>
<label for that input>
</div>


```
and in this version form builder doing that:

```
<div>
<label for that input> <input> Name_of_element </label>
```

which is impossible to do checked function by CSS for light version of form ( no JS, JQ etc.)

bad example.

```
<label class="radio-inline" data-label="Dzieci" for="fld_4863845_1_opt1400892">
<input type="radio" id="fld_4863845_1_opt1400892" data-field="fld_4863845" class="fld_4863845_1 option-required" name="fld_4863845" value="Dzieci" checked="checked" required="required" data-radio-field="fld_4863845_1" data-type="radio" data-calc-value="Dzieci">
			Dzieci		</label>
```

good example.
```

<input type="radio" id="fld_4863845_1_opt1499638" data-field="fld_4863845" class="fld_4863845_1 option-required" name="fld_4863845" value="Dorośli" required="required" data-radio-field="fld_4863845_1" data-type="radio" data-calc-value="Dorośli">
<label class="radio-inline" data-label="Dorośli" for="fld_4863845_1_opt1499638">
			Dorośli		</label>

```

And i don't know why it give to label that many spacers

i workaround that by putting in VC rawJS code replacer

```
var inp = jQuery('#fld_4863845_1_opt1499638');
inp.insertBefore(jQuery('#fld_4863845_1_opt1499638').parent());
```
and i must get all elements to array and loops that code by all occurences

but for you is to move element in form element builder   <input> above the <label>

If you wan't to repair that issue   label MUST be below in code hierarchie input otherwise css checker won't work

Let me know if my suggestion is worth a implementation

cheers

BTW   INCREDIBLE FORM BUILDER !!! HUGE REGARDS, on next production it will be 
element to buy for my clients

sorry for mistakes in text, not my native language ;/

## What PHP Errors Have You Logged While Reproducing This Bug?
no php error

## What JavaScript Errors Have You Seen While Reproducing This Bug?
no JS error

**Comment by Shelob9** [comment] 2017-08-25 01:24
Thanks for using Caldera Forms.

You are correct that the markup for checkboxes and radio fields is really not good. I'm trying to figure out a backwards compatible fix for this. 

I am closing this as a duplicate of #807 but not because I don't intend to fix it, just to keep things tidy.

**Closed by Shelob9** 2017-08-25 01:24 UTC
