### ISSUE TITLE
File required

### ISSUE THREAD

**Issue by labadiimi** [CalderaWP/Caldera-Forms#1433] opened 2017-03-23 14:32 UTC
Hello!

WordPress Version: 4.7.3
PHP Version: 5.6.23
MySQL Version: 5.6.35
Caldera Forms Version: 1.5.0.6
Testify: 1.0

I created a new form with File section. I not checked the "required check box", but it shows.

![form_builder](https://cloud.githubusercontent.com/assets/26627880/24252277/4c059ae8-0fdd-11e7-925f-36973998a666.jpg)
![in_web](https://cloud.githubusercontent.com/assets/26627880/24252284/50a16096-0fdd-11e7-8b4f-a2512463c130.jpg)

Could you help me?

Thank You!

**Comment by andrewlimaza** [comment] 2017-03-24 12:44
Thanks for the feedback.

I am unable to recreate this issue on my local environment - would you mind testing this using the Advanced File Upload and see if the issue persists?

If you leave this field blank and submit does the form submit or does it require a file to be uploaded to it?

**Comment by Shelob9** [comment] 2017-03-29 23:00
Is this file field linked to a processor. If so, it is required. This is hyper-annoying to me - #746 and wish it wasn't a major change to fix.

**Comment by Shelob9** [comment] 2017-04-03 15:42
@labadiimi Since we didn't here back I'm going to close this as a dupe of  #746 Please reopen with more details if my comment https://github.com/CalderaWP/Caldera-Forms/issues/1433#issuecomment-290252037 doesn't explain the issue.

**Closed by Shelob9** 2017-04-03 15:42 UTC
Labels: Needs Feedback From User
