### ISSUE TITLE
Checkbox populated with taxonomy not saving

### ISSUE THREAD

**Issue by kauaicreative** [CalderaWP/Caldera-Forms#1397] opened 2017-03-14 05:24 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
7.0

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Beahviour?
Create a Checkbox or Autocomplete and populate it with a taxonomy. set, value by ID. Submit Form > The form entry is saved but the taxonomy entry(s) are not saved. 
Note that using a drop down list works as expected and the single entry will be saved. It's only when using multi-select forms. 

## What PHP Errors Have You Logged While Reproducing This Bug?
no errors
![image 103](https://cloud.githubusercontent.com/assets/127033/23886909/8ac3c9b6-0822-11e7-8f65-479e9e04bb05.png)

**Comment by Shelob9** [comment] 2017-03-21 16:27
I am unable to reproduce this. I am testing with checkboxes auto-populated by categories and tags. In both cases single and multiple selections save just fine. I suspect this bug was fixed via 787fb9a758b4a5f9eaa8bac00c133ad67dec2ea3

**Closed by Shelob9** 2017-03-21 16:27 UTC
Labels: Bug
