### ISSUE TITLE
Glitchy v1.5v2?

### ISSUE THREAD

**Issue by aussit** [CalderaWP/Caldera-Forms#1183] opened 2017-01-31 12:54 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.2PHP Version: 7.0.13MySQL Version: 10.0.27Caldera Forms Version: 1.5.0-b-2WP_DEBUG: 1

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Using child theme, no modifications. Not a plugin clash problem, Caldera was working fine with no changes to plugins yesterday. Bug occurred two hours ago when I upgraded to v1.5b2

## What Is The Unexpected Beahviour?
Not sure if it was because of the upgrade but now whenever I create a new form, and save the form after adding one field, on the list of forms there are duplicates of the newly created form. I have attached a link for reference. Could there potentially be a bug on the v1.5b2?

See screenshot of duplication [here](http://imgur.com/PwLdEIT)
See screenshot of Error log [here](http://imgur.com/9u5GAuo)

**Comment by aussit** [comment] 2017-02-01 03:35
Hi. 

Can pls advise what is the next step that usually occurs when someone post on here?

Am keen to move on with building my forms. Would be good to be acknowledged whether if this is an error, can it be fixed easily, will it be fixed, when will it be fixed etc. I'm not understanding when you added a label, what does it mean to the ticket?

Thanks
Ben

**Comment by Shelob9** [comment] 2017-02-01 04:44
Thanks for using Caldera Forms. This a duplicate of #1182 that's why it has that label and should have been closed. It will get fixed in the next beta of 1.5, I'm not sure when that will happen. This isn't a bug in 1.4.8, so the easiest fix is to install that through WordPress.org.

I appreciate you beta testing, but I don't recommend you using the beta on a live site,  CalderaForms.com uses 1.4.8 for example. 

This is a bug tracker, not a support form. You should not expect that opening an issue here will lead to an immediate response or resolution.  If you need right away help, use https://calderaforms.com/support

**Closed by Shelob9** 2017-02-01 04:44 UTC
Labels: duplicate

**Comment by aussit** [comment] 2017-02-01 06:13
ok thanks for taking time to explain, now its alot clearer on the tags and the nature of posting here.

noted on the advice.

The core for Caldera forms plugin is free, but its a minimum $79 compulsory fee with three addons thrown in in order to gain support access for the "free" plugin which was the only thing that was needed. Sure ... my expectation fell short on the approach of your freemium pricing model but its good to get clarity from the developer at this stage, rather than spending the money on the unlimited bundle for multiple sites and have the developer manage expectations later.

Appreciate your time responding, I hope the bug gets fixed in future.
