### ISSUE TITLE
Button type "Previous Page" requires all required fields to be filled up

### ISSUE THREAD

**Issue by ghoseandco** [CalderaWP/Caldera-Forms#229] opened 2015-08-27 12:49 UTC
The "Previous Page" button reuires all required field to be filled up on the curren form page, that is little ridiculous, someone wants to go back to see if things are correct on the previous page, why she should fill-up the required feilds on current page?

**Comment by soumyabg** [comment] 2015-08-28 08:13
@Desertsnowman , I also request you to fix this silly issue in the next debugged version :)

**Comment by lynxlynxlynx** [comment] 2015-09-09 10:00
Yep, hit the same thing. It's simple to reproduce, but I can provide a json dump if you don't have any test forms handy.

**Comment by rawcat** [comment] 2015-12-11 13:34
Any idea when this is going to be fixed?

**Comment by Desertsnowman** [comment] 2015-12-11 13:44
I've been working on things within this area so should be pretty soon. I have a pretty simple schedule that includes a single item at a time, this is the next one on said queue.

**Comment by mattstockdale** [comment] 2016-03-02 13:04
Just adding my interest in this too. It'll be really great to be able to use the previous button on a form with required fields. Thanks for looking into it, David.

**Comment by mattstockdale** [comment] 2016-03-04 11:54
wpappdev's submission was really great to see, a week or so ago, but it doesn't seem to have made any difference for us when testing it on a new simple form - https://www.linkethiopia.org/caldera-back-button-testing/  I'm not sure where the problem is

**Comment by mattstockdale** [comment] 2016-03-05 22:38
Nice work, David - version 1.3.3.1 works perfectly!

**Comment by Desertsnowman** [comment] 2016-03-06 12:17
Yay! I'm useful.  I'm having a wonderful time!

**Comment by lynxlynxlynx** [comment] 2016-08-08 09:27
This was fixed, so it can just be closed.

**Comment by Shelob9** [comment] 2016-09-01 16:53
Closing as "was fixed awhile ago."

**Closed by Shelob9** 2016-09-01 16:53 UTC

**Comment by ghoseandco** [comment] 2016-09-04 11:36
Thanks @Desertsnowman , @Shelob9
