### ISSUE TITLE
File Upload: Files are always attached now

### ISSUE THREAD

**Issue by huntersbest** [CalderaWP/Caldera-Forms#1102] opened 2017-01-10 15:47 UTC
Regardless wether the appropriate box is checked or not, the uploaded file is always attached to the sent email.

**Comment by Shelob9** [comment] 2017-01-17 00:25
@huntersbest Thanks for using Caldera Forms. 

Have you reviewed this documention:
https://calderaforms.com/doc/how-caldera-forms-file-attachments-uploads-work/

If you can please explain what your settings are and how they differ from how it should work according to the doc, as well as provide WordPress and Caldera Forms version, I'd be happy to look in to this as a bug. Right now, i can't reproduce this so I am closing this. Please feel free to reopen if you want to make a case I am wrong.

BTW, if you need prompt support, always use https://calderaforms.com/support

**Closed by Shelob9** 2017-01-17 00:25 UTC

**Comment by huntersbest** [comment] 2017-01-17 08:25
Hi and thanks for the reply. 

Yes, I have read the documentation. The problem is the setting:
"Attach To Mailer – Select this option if you wish to attach the file to the mailer."
If I uncheck it, the file is still attached to the mail - the documentation suggests, that this happens only if you check this option.

I also tried all combinations of the 3 options (Attach To Mailer, Allow Multiple, Add To Media Library ) with the same result. The file is always been sent.

Did I get somwthing wrong?
