### ISSUE TITLE
Deprecated function call wp_uploads_bits()

### ISSUE THREAD

**Issue by robwilde** [CalderaWP/Caldera-Forms#1997] opened 2017-10-11 05:34 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.8.2PHP Version: 7.0.24-1+ubuntu16.04.1+deb.sury.org+1MySQL Version: 5.5.5Caldera Forms Version: 1.5.6.1WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
running on minimal site install, running Genesis theme starter template

## What Is The Unexpected Behaviour?
error on submit form related to save.php
`/var/www/paml.testing/htdocs/wp-content/plugins/caldera-forms/classes/save.php380`

second parameter, $file_type is deprecated
`$csvfile = wp_upload_bits( uniqid( '', true ) . '.', $file_type, null, $csv );`
also appears the bits parameter is missing and added to the last parameter for time.

*possible suggestion*
`$csvfile = wp_upload_bits( uniqid( '', true ) . '.', null, $csv, null );` 

## What PHP Errors Have You Logged While Reproducing This Bug?
Whoops \ Exception \ ErrorException (E_USER_NOTICE)
wp_upload_bits was called with an argument that is <strong>deprecated</strong> since version 2.0.0 with no alternative available.

**Comment by robwilde** [comment] 2017-10-11 05:40
Tested changes and form now submitting with no errors. Related to the use of *Send CSV* setting. Hope this helps

**Comment by Shelob9** [comment] 2017-10-12 01:31
Thanks for the report. This is a duplicate of #1978 

Did you test with latest master branch to see if this resolves your issue? If not please reopen, else closing as dupe.

**Closed by Shelob9** 2017-10-12 01:31 UTC
