### ISSUE TITLE
Email not sending and Resending issue

### ISSUE THREAD

**Issue by charls637** [CalderaWP/Caldera-Forms#1759] opened 2017-07-18 05:41 UTC
After the resend button is clicked, i got this issue:

Catchable fatal error: Argument 2 passed to Caldera_Forms_Field_Util::has_field_type() must be of the type array, null given, called in /nas/content/staging/firstvotenc/wp-content/plugins/caldera-forms/classes/magic.php on line 44 and defined in /nas/content/staging/firstvotenc/wp-content/plugins/caldera-forms/classes/field/util.php on line 361

i am using the latest plugin and wp framework

**Comment by nerdworker** [comment] 2017-07-24 20:45
I am also having this issue on a website. Latest release of WP and CF. This happens when you go to the admin list of entries and click on the Resend button. The error is almost identical:

Catchable fatal error: Argument 2 passed to Caldera_Forms_Field_Util::has_field_type() must be of the type array, null given, called in {PATH}/wp-content/plugins/caldera-forms/classes/magic.php on line 46 and defined in {PATH}/wp-content/plugins/caldera-forms/classes/field/util.php on line 361

**Comment by Shelob9** [comment] 2017-08-31 15:22
This issue is a duplicate of #1864 which is fixed.

**Closed by Shelob9** 2017-08-31 15:22 UTC
