### ISSUE TITLE
Incorrect Checkboxes when using values

### ISSUE THREAD

**Issue by tmeisky** [CalderaWP/Caldera-Forms#567] opened 2016-04-30 02:52 UTC
I created a checkbox with 4 events.  People can choose one or more.  Events A & B are $25 and events C & D are $35.  I have values set for each entry so I can calculate a total amount due on the screen.  I select events B & C and submit the form.  The mailer, using the [summary} field, and the Entries both incorrectly report Events B & D.  Similarly, choosing events A & C reports events B & D. Selecting A only reports event B.  The program seems to always pick the last entry with any given value when there are more than one with that value.

**Comment by Desertsnowman** [comment] 2016-07-13 10:23
This is not a bug, but improper use of the value field. Values in option fields should be unique. This is the whole point of the value as per the purpose of the value attribute on a select field; the value which is sent to the server.
If you have the same value for multiple options, there is no way to determine which option was selected. 

If using for a price of an option, you should be using hidden fields with the price relating to an option and have them conditionally removed. Then have a calculation adding all the hidden fields together.

To fix this, I'll make a check to notify the user that value fields should be unique.

**Comment by Desertsnowman** [comment] 2016-07-13 10:38
Closed via 1e5904a
added non breaking notice that allows duplicate values but warns of them.
![uniquevals](https://cloud.githubusercontent.com/assets/307466/16800621/73adc394-48f6-11e6-928c-cba87e350677.gif)

**Comment by Shelob9** [comment] 2016-07-13 12:20
Reopening. I am radically against breaking backwards compatibility for no good reason.

This is going to prevent people who need this to keep working the way it always did from saving their forms.

Also, valid use case:

I have 3 products, you can buy one selected by a checkbox. I pass checkbox value, which is price to calculation. Two products cost the same amount so have same value, different label. This used to work? Now they can't do that. 

That's bad.

Please revert.

In entry viewer make it show value and label. So much easier and without breaking backwards comaptibility.

**Comment by tmeisky** [comment] 2016-07-13 13:19
Certainly it isn't a bug if it's working the way it was designed.  It does seem, in my opinion, to be a non-standard way of implementing values in a multi-selection situation, at least compared to other implementations I've tested and used.  At the very least, it seems to be a rather convoluted way (from an end-user perspective) to total up a couple of dollar amounts from a list of options.  Creating hidden fields, variables and conditional evaluations to run a calculation on numbers that are already available in the checkbox values feels like a lot of extra steps to get a total.  But, it's your plug-in, not mine.  All I can do is give you a user perspective.

I can't speak the the backward compatibility issue as this was the behavior I observed from the beginning of my use of the plug-in.  I was surprised to find that it didn't do what seemed a rather straight forward and intuitive thing with available data.

**Comment by Desertsnowman** [comment] 2016-07-20 15:19
@Shelob9 - I didn't break backwards compatibility and wont affect anything from working the way it does. The warning is simply that, a warning., it will allow it and will continue to work. I'm just stating that the value is intended on being unique.

The way described has never worked properly because of not being able to track which option the value relates to since there are multiple options with the same value.

This issue is not about a bug or something not working, its about setting up a flawed process.
The form in question is essentially set to capture only the price and not the product.

**Closed by Desertsnowman** 2016-07-20 15:19 UTC
Labels: bug
