### ISSUE TITLE
Unexpected Result in Mailer using %slug:label%

### ISSUE THREAD

**Issue by byronyasgur** [CalderaWP/Caldera-Forms#1473] opened 2017-04-04 22:11 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.3PHP Version: 5.6.30MySQL Version: 5.6.35Caldera Forms Version: 1.5.0.6WP_DEBUG:

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Beahviour?
According to - https://calderaforms.com/doc/using-magic-tags-caldera-forms/ - I should be able to use a magic tag in the form of %slug:label% to display the results of a checkbox, but it gives an output similar to this example

`Functionality/Services Required 	"{"opt1277011":"Sales Chat","opt1543667":"Google Map","opt1725714":"test"}`

## What PHP Errors Have You Logged While Reproducing This Bug?
none

## What JavaScript Errors Have You Seen While Reproducing This Bug?
none

**Comment by Shelob9** [comment] 2017-04-04 22:26
@byronyasgur  Thanks for using Caldera Forms. This is a duplicate of #1410 which is fixed in Caldera Forms 1.5.0.7 

I'm going to close this as a duplicate. Please update to 1.5.0.7 and if that doesn't fix your issue re-open this and let us know, but it should.

**Closed by Shelob9** 2017-04-04 22:26 UTC
