### ISSUE TITLE
Using %slug_field:label% to display labels for checkbox not working correctly.

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1442] opened 2017-03-29 11:46 UTC
If you show the values of the checkbox field using the magictag:label method, it displays both the value and label inside the email message.

Please see screenshots below -

![email_message_show_label](https://cloud.githubusercontent.com/assets/12629136/24452903/e64770c0-1485-11e7-9d8b-ee9e02569747.png)

![email_received](https://cloud.githubusercontent.com/assets/12629136/24452932/0ecb17d6-1486-11e7-9afc-79d53f2ef4bb.png)

**Comment by Shelob9** [comment] 2017-03-29 18:52
@andrewlimaza isn't this a dupe of #1347 ?

**Comment by andrewlimaza** [comment] 2017-03-30 14:22
Yes it is @Shelob9 sorry saw it was closed and thought it was fixed.

**Comment by andrewlimaza** [comment] 2017-03-30 14:23
But it seems now it's not working again with latest update. Issue https://github.com/CalderaWP/Caldera-Forms/issues/1347 seemed to be a misunderstanding that %slug:label% was expected to work in HTML field.

**Comment by Shelob9** [comment] 2017-03-30 14:51
%slug:label% doesn't work in an HTML field. Modify the docs to make that clear.

**Closed by Shelob9** 2017-03-30 14:51 UTC

**Comment by andrewlimaza** [comment] 2017-03-30 16:21
This also isn't working 100% on certain fields (i.e. dropdown) inside email message. 

It shows `{"opt1987329","My Label"}`

**Comment by Shelob9** [comment] 2017-03-30 17:38
@andrewlimaza With which version?

**Comment by andrewlimaza** [comment] 2017-03-30 17:47
Version 1.5.0.6 will be testing master branch really soon!
