### ISSUE TITLE
Fields that are shown with conditions do not get saved to entry viewer

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1440] opened 2017-03-28 12:27 UTC
If a field is shown by using conditions, the data does not show under 'view entries' tab.

Screenshots below -
![front end](https://cloud.githubusercontent.com/assets/12629136/24404717/9766a91c-13c2-11e7-955c-718090635d00.png)

![entries viewer](https://cloud.githubusercontent.com/assets/12629136/24404718/97679750-13c2-11e7-87a2-13047efe9ba6.png)

**Comment by jalwan** [comment] 2017-03-29 01:47
I have the same problem.

**Comment by Shelob9** [comment] 2017-04-01 22:12
Pretty sure this is the same issue as  #1453 which is fixed. I can no longer reproduce. @andrewlimaza Can you please re-test against master?

**Comment by jalwan** [comment] 2017-04-01 22:20
I still have the problem.  Running Version 1.5.0.6

**Comment by Shelob9** [comment] 2017-04-01 22:22
@jalwan The fix is in the master branch here, if you want to test, please reinstall from master, 1.5.0.6 will still have this issue.

**Comment by jose-luis-garcia** [comment] 2017-04-03 16:04
I still hav the same problem. Installed the master branch. Cannot see the field values of conditional hidden fields and cannot export either.

**Comment by Shelob9** [comment] 2017-04-03 17:05
@jose-luis-garcia If a field is hidden by conditional logic it is not supposed to save. There was a bug in Caldera Forms 1.5.0 that caused them to save, but previous to 1.5.0 they did not. By design they should not save.

After the fix in #1453 if a field is hidden by conditional logic and then unhidden by conditional logic, its value should be restored.

**Comment by jose-luis-garcia** [comment] 2017-04-04 07:19
Sorry for my bad english: What I meant was, I have many fields in a form wich are hidden by conditional logic. Whenever a user unhides them and stores values in them the form saves the data in the database. The bad comes when I try to export the form. All fields that are under conditional logic have no values in the generated cvs-file.
Yesterday using the actual master, I found out that when I turn **off** the conditional logic the values are exported. When I turn **on** the logic, the values are not exported

**Comment by andrewlimaza** [comment] 2017-04-04 09:31
This works for me for entry viewer. Testing the export to CSV issue now.

**Comment by andrewlimaza** [comment] 2017-04-04 09:32
entries export (.CSV) @jose-luis-garcia 

The hidden field is a normal text field that is shown using conditional logic.

<img width="511" alt="csv export with a field shown with logic" src="https://cloud.githubusercontent.com/assets/12629136/24650418/641051f4-192a-11e7-9353-01ffa89f5695.png">

**Comment by andrewlimaza** [comment] 2017-04-04 12:00
@jose-luis-garcia which field type are not showing data? Is it a single line text field, dropdown, checkbox etc.?

**Comment by jose-luis-garcia** [comment] 2017-04-04 12:03
@andrewlimaza in my case all textfields. As soon as i disable the conditional logic, all fields apear in entry viewer and in cvs-export.

**Comment by Shelob9** [comment] 2017-04-05 14:26
I'm moving this to 1.5.0.8 for further discussion, but I'm not sure I see the bug. What we're calling "hiding" should be better described as "removing". If your conditional logic removes a field it doesn't save any value in database, therefore email, csv, entry viewer, etc has no value to display.

**Comment by jose-luis-garcia** [comment] 2017-04-05 14:51
@Shelob9 I try to explain it better:
The conditional logic is: "Display" if Value of Field "x" is "yz". 
Fields marked with that logic are shown in the form as soon as the user klicks on Field "x" and selects value "yx". User enters then the corresponding values. 
As soon as the user submits the form all values are stored in the database. So far so good. 
My Problem here comes after that process. 
The entry viewer does not show the values of that fields wich are marked with specified conditional logic and on export these values are not exported.

As soon as I disable the conditional logic all these values are displayd in entry viewer and also exported. Whenever I turn conditional logic on, the these values disapear again and are not exported but are in the database.

I hope you can see the point. Now that i found out, that I can export all values by disabling the conditional logic, I can live with that. It´s only a bit nasty to disable all logic before exporting the values.

**Comment by Shelob9** [comment] 2017-04-05 17:24
@jose-luis-garcia Thanks for these details. To clarify, you are  saying that you have a field that is initially hidden by conditional logic, when it is shown, the values are saving, but not being displayed in entry viewer. Correct?

If so, can you please answer the following questions to help me understand what is going on:

- How are you confirming the values are stored in the database?
- Do the field values show in the email with the {summary} magic tag?
- Do the field values show in the email with a %field_slug% magic tag?
- Is this still an issue in Caldera Forms 1.5.0.7?
- When you say "export values" how are you exporting the values? Is this a MySQL export, are you referring to the admin entry viewer's CSV export or the CSV attached to the email?

Thanks for answering these questions, sorry for being overly verbose, but I need to understand what steps you are taking and what the results are to understand what the bug might be.

**Comment by jose-luis-garcia** [comment] 2017-04-06 07:29
@Shelob9  Yes, that is correct. Fields are initially hidden by conditinal logic. values are saved but not displayed by entry viewer nor exported via cvs-export.

Here my answers:
I can see the entrys in the database via phpmyadmin
All fields are shown in the email with the {summary} tag
Field values are in the email with %field_slug% tag
I mean admin entry viewer's CSV export

Hope I can help solve the problem. In my opinion Caldera Forms is the best form plugin on the market. Next I will buy the Entry Limit extension.

**Comment by andrewlimaza** [comment] 2017-04-06 08:38
@shelob9 @jose-luis-garcia I have done further testing again with version 1.5.0.7 and I am unable to recreate this issue.

# Debug Information
WordPress Version: 4.7.3 PHP Version: 7.0.3 MySQL Version: 5.5.49 Caldera Forms Version: 1.5.0.7 WP_DEBUG: 1

# Summary
I have a 'removed' field according to dropdown selection. If the user selections 'Option 1' another dropdown field is shown. This data get's saved into Entry Viewer + CSV export. Please see screenshots below -

Entry Viewer -
<img width="699" alt="entry viewer" src="https://cloud.githubusercontent.com/assets/12629136/24745203/15398500-1ab5-11e7-895e-21a67d6b2e04.png">

.CSV -
<img width="487" alt="csv example" src="https://cloud.githubusercontent.com/assets/12629136/24745210/1a33ca02-1ab5-11e7-9669-bc96a736401a.png">

@jose-luis-garcia would you mind sending through debug information. You may retrieve this information by going to 'Caldera Forms' > 'Support' > 'Debug Information'

**Comment by andrewlimaza** [comment] 2017-04-06 08:39
I am going to do a test on different PHP versions to see if I can recreate @Shelob9

**Comment by andrewlimaza** [comment] 2017-04-06 08:44
This works on older versions of PHP - tested on 5.6.20

**Comment by jose-luis-garcia** [comment] 2017-04-06 09:01
@andrewlimaza Nothing hapens going to 'Caldera Forms' > 'Support' > 'Debug Information'
here screenshots of the form (form.png), the logic with fields (logic1.png) marked and entry viewer (entry-with-
![entry-with-logic](https://cloud.githubusercontent.com/assets/26877214/24746147/59e2bf16-1ab8-11e7-84bb-9e91dd85e878.png)
![entry-without-logic](https://cloud.githubusercontent.com/assets/26877214/24746148/59e32c12-1ab8-11e7-8c20-89a59739df99.png)
![form](https://cloud.githubusercontent.com/assets/26877214/24746149/59e3fe80-1ab8-11e7-9c52-9b6bcd7cfb84.png)
![logic1](https://cloud.githubusercontent.com/assets/26877214/24746150/59e5e95c-1ab8-11e7-8d82-41cf9995ba8e.png)
![logic2](https://cloud.githubusercontent.com/assets/26877214/24746151/59fd64c4-1ab8-11e7-9def-46e7b1f4aca9.png)




logic.png) then logic (logic2.png) with fields unchecked end corresponding entry viewer(entry-without-logic.png)

**Comment by Shelob9** [comment] 2017-04-06 15:28
@jose-luis-garcia Thanks for the additional information. Can you please tell us if this is based on testing with version 1.5.0.7 or not?

**Comment by jose-luis-garcia** [comment] 2017-04-06 15:33
@Shelob9 Yes sir, tested with version 1.5.0.7

**Comment by jalwan** [comment] 2017-04-10 05:14
I have 1.5.0.7 and I still have the problem.  When I view entries, all the fields completed by the user after the first field with conditional logic are not visible in the entry viewer.

**Comment by jose-luis-garcia** [comment] 2017-04-10 06:43
@jalwan : There is a small workaround on this: Disable the conditional logic and all entries are visible and exportable.

**Comment by Shelob9** [comment] 2017-04-10 21:41
The root issue of this is #1494 which is now fixed in 	9e60211 1.5.0.8 will be out shortly.

**Closed by Shelob9** 2017-04-10 21:41 UTC
Labels: bug:major, NEEDS TESTING
