### ISSUE TITLE
Using toggle field in calculation doesn't show total on front-end only

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1569] opened 2017-05-08 12:18 UTC
If you use a toggle switch directly in calculations, the form total doesn't appear or shows 0.

The values saved in the entries are correct however, the issue is a front-end issue only.

To recreate the issue do the following -

1. Create a toggle switch with the values of 1 through 5. (Show values and set the value to the numeric value).
2. Create a hidden field with a numeric value (i.e. 15)
3. In the total field, multiply the fields together.

Here is the result -

<img width="221" alt="screen shot 2017-05-08 at 2 16 21 pm" src="https://cloud.githubusercontent.com/assets/12629136/25803838/25d41e18-33f9-11e7-91a7-90b16a838081.png">

**Comment by Shelob9** [comment] 2017-05-08 14:34
Closing as dupe of #1563

**Closed by Shelob9** 2017-05-08 14:34 UTC
Labels: duplicate
