### ISSUE TITLE
Not able to edit created mailer templates

### ISSUE THREAD

**Issue by ignusvermaak** [CalderaWP/Caldera-Forms#663] opened 2016-06-29 08:39 UTC
Hello

https://elementz.feedmybeta.com/wp-admin/admin.php?page=mailer_templates

Not ab

**Comment by ignusvermaak** [comment] 2016-06-29 08:41
Sorry, accidently pushed shift return

Not able to edit past created mailer templates.

Haven't been able to test on a clean install yet, but I have noticed it on a few sites.

David has login details to all our development sites

**Comment by Shelob9** [comment] 2016-06-29 22:52
@ignusvermaak  I'm assuming you're looking for support for our Mail Templates add-on? https://calderawp.com/downloads/mail-templates-for-caldera-forms/

If so, please open a support request at https://CalderaWP.com/support

Happy to help, but I am closing this issue as it is not a bug in the core Caldera Forms plugin itself.

**Closed by Shelob9** 2016-06-29 22:52 UTC
