### ISSUE TITLE
Div id caldera_form_1 repeated for all forms.

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#1332] opened 2017-03-01 15:51 UTC
I am using the latest release.

Last night I styled the Div id caldera_form_1 for one form and did not check the other forms. This morning the client told me that all the forms had been affected.

Here are three forms using the same Div ID caldera_form_1.

Contact form
![screen shot 2017-03-01 at 16 47 07](https://cloud.githubusercontent.com/assets/5323259/23467674/f970ba64-fe9e-11e6-953e-f709a428aa29.png)

Order form
![screen shot 2017-03-01 at 16 47 40](https://cloud.githubusercontent.com/assets/5323259/23467675/f97241e0-fe9e-11e6-87bf-85e49fa00037.png)

Calculator
![screen shot 2017-03-01 at 16 50 29](https://cloud.githubusercontent.com/assets/5323259/23467788/427f7cc2-fe9f-11e6-81dd-2231c0dfa409.png)

**Comment by Shelob9** [comment] 2017-03-01 16:39
I can't reproduce. I have 4 forms on page, they each have unique ID
![screenshot from 2017-03-01 11-38-27](https://cloud.githubusercontent.com/assets/1994311/23470137/a11aabc0-fe73-11e6-9732-36b12ab0fc28.png)

**Comment by Shelob9** [comment] 2017-03-01 16:51
I am closing as this is how it has always worked, first form on page is #caldera_form_1 second is  #caldera_form_2 Targeting CSS based on this is problematic. That's why form has a class using the form ID.

This system is not ideal, but changing it would break so many things, so until/if we do a non-backwards comapt version 2, this is how it is.

**Closed by Shelob9** 2017-03-01 16:51 UTC
