### ISSUE TITLE
Uncaught TypeError: a(...).baldrick is not a function

### ISSUE THREAD

**Issue by dudemeister25** [CalderaWP/Caldera-Forms#3042] opened 2019-03-04 03:33 UTC
## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support
No

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab
Caldera 1.8.1 WP 5.1 PHP idk, sorry

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
I'm unable to attempt that right now

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.
After 1.8 rolled out we started having issues with our forms.  We have 1.8.1 and I read through the existing ticket about the JS isses, but it didn't help.  The slide/toggle fields do not work and since they are required, users cannot submit the form.  When I checked the console, it shows the following error.
Uncaught TypeError: a(...).baldrick is not a function
    at resBaldrickTriggers (caldera-forms-front.min.js?ver=1.8.1:1)
    at HTMLDocument.<anonymous> (caldera-forms-front.min.js?ver=1.8.1:1)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/
None

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers
Uncaught TypeError: a(...).baldrick is not a function
    at resBaldrickTriggers (caldera-forms-front.min.js?ver=1.8.1:1)
    at HTMLDocument.<anonymous> (caldera-forms-front.min.js?ver=1.8.1:1)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)

**Comment by sushmak02** [comment] 2019-03-04 05:11
I am facing the same issue.
Refer this URL - http://uael-sushma.sharkz.in/caldera-form/
Check console of the above page.

**Comment by New0** [comment] 2019-03-04 11:50
Thank you for reporting that issue @dudemeister25 , 
I opened a separated issue #3043  for the range slider field since I could confirm it, but didn't relate it to the error in the console. 
Let's keep investigating the console error here. Please share any other information related to the page the error shows, like other plugins, fields inserted in the form, etc

Thank you @sushmak02 for noticing you have the same error showing in your console. 
Could you also  detail what fields are inserted in the form ( maybe a Range slider field ? ), 
I saw elementor activated, did you use a shortcode block or the Caldera Forms elementor block to insert the form in the page ?

**Comment by sushmak02** [comment] 2019-03-04 12:50
@New0 I am a developer of Ultimate Addons for Elementor. We have created a widget for elementor to style the forms of Caldera forms plugin.
Since Caldera v1.8.0 the above issue persists all over the site except, on that page where the form is used.
I have used below code to enqueue all caldera forms fields - 

if ( class_exists( 'Caldera_Forms_Render_Assets' ) && class_exists( 'Caldera_Forms' ) ) {
	\Caldera_Forms_Render_Assets::register();
	\Caldera_Forms_Render_Assets::optional_style_includes();
	\Caldera_Forms_Render_Assets::enqueue_all_fields();
}

The JS error comes from this line - \Caldera_Forms_Render_Assets::enqueue_all_fields();
URL of JS error - http://tinyurl.com/y5fbakqa

Can you please help us with this issue. This has broken all our site.

**Comment by New0** [comment] 2019-03-04 14:35
@sushmak02 I'm sorry you're having this issue. 

Could you / did you test using `add_filter( 'caldera_forms_render_assets_minify', '__return_false' );` and share errors printed in the console ?

Are you still having this issue when all other plugins are deactivated ? Switching to default theme ?

If yes, could you share the plugins used and theme activated ?

**Comment by dudemeister25** [comment] 2019-03-04 21:01
Hi New0,

Thank you for taking a look at this.  I looked at the other ticket and that isn't the field I was thinking of.  Sorry I should have added a screenshot or more detail.  The field we are having issues with is the toggle switch.  Below is a screenshot for clarity.  Thank you again for your help!

![image](https://user-images.githubusercontent.com/8127831/53761934-fe52fc00-3e83-11e9-8686-5b68e38a80e8.png)

There aren't any other page errors that I can see.  We are using Divi to build our pages and have embedded the shortcode in the page builder.  Other fields include text fields (email/phone), datepicker, dropdown, an HTML field, radio buttons, checkboxes, and textarea.  We are using conditions to show/hide fields depending on responses.

Let me know if I can provide any other info.

**Comment by Shelob9** [comment] 2019-03-04 21:03
@dudemeister25 Does this issue persist if you disable Divi and all of your other plugins?

What if you switch from Divi to your staging site and keep your plugins active?

I would recommend doing this on a staging site?

**Comment by Shelob9** [comment] 2019-03-04 23:32
@dudemeister25 and @sushmak02 it would also be helpful if we could see the debug information that is in the Caldera Forms "Support" submenu for your sites to compare what is different.

**Comment by sushmak02** [comment] 2019-03-05 04:25
@New0 https://github.com/CalderaWP/Caldera-Forms/issues/3042#issuecomment-469274165 
After adding this to Functions.php it fixes the issue. There is no console error after adding it.

But this is not the permanent fix, right?

**Comment by LyleBennett** [comment] 2019-03-05 08:28
Using the Enfold theme and Avia Layout builder, we also get the same console error which breaks the site if a caldera form is loaded using a shortcode.

Adding `add_filter( 'caldera_forms_render_assets_minify', '__return_false' );` in the functions.php also fixed our site.

**Comment by LaurieY** [comment] 2019-03-06 19:59
I have hit this problem as well, using Toggle Switch and plugin V 1.8.1
The add_filter fix worked for me

**Comment by colbyalbo** [comment] 2019-03-09 15:25
Ran into this error as well, Fixed it with the add_filter mentioned above. 

From Console: Uncaught TypeError: a(...).baldrick is not a function
Short Debug info:
    WordPress Version: 5.1PHP Version: 7.2.10MySQL Version: 5.7.24Caldera Forms Version: 1.8.2WP_DEBUG: 

Full Debug Information

WordPress Version: 5.1

PHP Version: 7.2.10

MySQL Version: 5.7.24

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0

Session Save Path: C:\MAMP\bin\php\sessions\

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

    Apc: No
    Memcached: No
    Redis: No

Object Cache:

    Apc: No
    Apcu: No
    Memcache: No
    Memcached: No
    Redis: No

WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Currently Active Theme: GeneratePress Child: 0.1

Plugins:

    Advanced Custom Fields: 5.7.12 Active
    All-in-One WP Migration: 6.86 Active
    All In One SEO Pack: 2.12 Active
    Caldera Forms: 1.8.2 Active
    Classic Editor: 1.4 Active
    Custom Post Type UI: 1.6.1 Active
    Disable Comments: 1.9.0 Active
    Duplicate Post: 3.2.2 Active
    Elementor: 2.5.3 Active
    Elementor Pro: 2.4.7 Active
    GP Premium: 1.7.8 Active
    ManageWP - Worker: 4.7.5 Not Active
    SendGrid: 1.11.8 Active
    Ultimate Addons for Elementor: 1.9.2 Active
    Wordfence Security: 7.2.3 Not Active
    WP Rocket: 3.2.6 Active

**Comment by Shelob9** [comment] 2019-03-11 14:58
This is really two issues - one is a dupe of #3053 and the other (toggle switches do not work) is #3075

**Comment by Shelob9** [comment] 2019-03-11 15:29
#3075 has a PR and will be fixed in 1.8.3 I am working on setting up my test site according to instructions from @sushmak02 to get into the Elementor issues

**Comment by colbyalbo** [comment] 2019-03-21 21:33
I have updated to 1.8.3 and i am no longer experiencing this error

> (Uncaught TypeError: a(...).baldrick...

**Comment by themindsett** [comment] 2019-03-22 15:45
Hello, I was unable to adjust the slider - I use the nominify filter above, and now my forms will not do calculations. It's either the slider works with no calculations (nominify filter added to functions.php) or the slider doesn't work and calculations work. Any idea why this would be?

**Comment by themindsett** [comment] 2019-03-22 16:08
Here are my pages, the first is without the no-minify filter - so the totals work, but the toggle switches don't. The second is with the no-minify filter on,

http://www.sophiesucree.com/en/achetest/

http://www.sophiesucree.com/en/achetest-no-minify-filter-on/

**Comment by themindsett** [comment] 2019-03-22 16:37
Note: I disabled all plugins, I left only plugin-organizer (used to disable plugins) and caldera-forms (obviously).

**Comment by themindsett** [comment] 2019-03-22 17:28
It seems that turning on the CDN function fixes the problem.

**Comment by LaurieY** [comment] 2019-03-22 19:34
Using CDN did not resolve it for me (unless I use the caldera_forms_render_assets_minify  - false  filter)  
I have checked that the sources are indeed loaded from the CDN via cdn.jsdelivr.net

**Comment by themindsett** [comment] 2019-03-23 10:36
LaurieY, why don't you simply use the filter in that case?

**Comment by LaurieY** [comment] 2019-03-23 10:54
As I understood it the filter is a workaround that prevents minifying the caldera assets and so increases the load time (albeit slightly). The system is intended to work with minified files?
I'm quite happy to continue with the filter, the impact is fairly low for me.
I added the comment for information that using the CDN hadn't resolved the issue for me rather than as a complaint.
Laurie

**Comment by themindsett** [comment] 2019-03-23 11:34
Understood. :)

**Comment by MACscr** [comment] 2019-05-09 20:37
Im getting this with a default wordpress install (5.2), default theme (2019), and latest Caldera (1.8.4). No other plugins installed. =/

**Comment by ChadReitsma** [comment] 2019-05-28 19:16
Like most WP Weirdness - this is most likely a plugin conflict.  I can confirm that by using Caldera Forms Anti-Spam (v2 reCaptcha) creates this issue.  The filter is a good workaround for now but it would be really nice if you guys could bring back reCaptcha support so we don't have to use another plugin - your honeypot simply isn't enough as spam still gets through.

**Comment by MACscr** [comment] 2019-05-29 00:09
> Like most WP Weirdness - this is most likely a plugin conflict. I can confirm that by using Caldera Forms Anti-Spam (v2 reCaptcha) creates this issue. The filter is a good workaround for now but it would be really nice if you guys could bring back reCaptcha support so we don't have to use another plugin - your honeypot simply isn't enough as spam still gets through.

Yet its not. I stated that right above you. Only plugin installed.

**Comment by ChadReitsma** [comment] 2019-05-30 23:49
> Yet its not. I stated that right above you. Only plugin installed.
Right. You'll have to use the filter until Caldera provides the fix.

**Comment by lucashfreitas** [comment] 2019-06-07 02:58
+1. Facing the same issue using the latest caldera forms (1.8.5).

**Comment by Alkalurops** [comment] 2019-06-08 10:46
+1. Facing the same issue here as well. Also on 1.8.5.

**Comment by Alkalurops** [comment] 2019-06-19 20:46
Any news on this? Each update of our theme removes the changes in functions.php again and the "fix" does not work anymore and has to be reapplied.

**Comment by Pross** [comment] 2019-08-05 12:33
> Any news on this? Each update of our theme removes the changes in functions.php again and the "fix" does not work anymore and has to be reapplied.

That's what child themes are for.

**Comment by agileware-pengyi** [comment] 2019-11-08 02:16
+1 with 1.8.7

Agileware ref: SUP-12415

**Comment by jeanwainer** [comment] 2019-11-08 14:15
I'm having this javascript error after enabling the wp youtube lyte plugin.
Any ideas on how to fix that?
The problem persists even without the cache/optimization plugins. It happens right after I enable the wp youtube lyte plugin.

**Closed** 2019-12-04 19:37 UTC
Labels: duplicate

**Comment by scrobbleme** [comment] 2020-01-27 09:49
Same here, even with a (quite) minimal configuration:

- only Caldera Forms 
- Divi Theme

I wonder why Caldera Forms just can't use jQuery Ajax instead of another lib?

**Comment by thirdbrainsa** [comment] 2020-11-18 10:10
Put in line 157 in caldera-core.php , this :
add_filter( 'caldera_forms_render_assets_minify', '__return_false' );
It makes the things working for us ..after we can build additionnal JS on top of it.
