### ISSUE TITLE
jQuery error with select2 autocomeplete fields.

### ISSUE THREAD

**Issue by Shelob9** [CalderaWP/Caldera-Forms#3411] opened 2019-12-05 16:47 UTC
When I add an autocomplete field`Uncaught ReferenceError: jQuery is not defined
    at ?page_id=5&preview=1&cf_preview=CF5de933c306c47:130`

![jquery error](https://user-images.githubusercontent.com/1994311/70255489-e4b54c80-1754-11ea-9233-c51a9067b7ad.jpg)

Reproduced with WordPress 5.2 and 5.3. 2019 and 2020 themes.

WordPress Version: 5.2.3PHP Version: 7.3.12MySQL Version: 5.7.28Caldera Forms Version: 1.8.8WP_DEBUG: 1

WordPress Version: 5.3PHP Version: 7.1.33MySQL Version: 5.5.5Caldera Forms Version: 1.8.8WP_DEBUG:

**Comment by riverBanjo** [comment] 2019-12-05 21:15
This works fine for me. No JS console error.

**Comment by Shelob9** [comment] 2019-12-06 01:17
Thanks @riverBanjo

**Comment by New0** [comment] 2019-12-09 15:13
@Shelob9 I couldn't reproduce the issue, is there a support ticket linked?

**Comment by Shelob9** [comment] 2019-12-09 22:37
@New0 Can you please copy the short debug info for environment you are testing in? This is new ish, wondering how your environment compares to mine. I was testing with a Sandbox site and our docker environment.

**Comment by New0** [comment] 2019-12-17 13:45
Closed via https://github.com/CalderaWP/Caldera-Forms/commit/d0a0096712bb8dacd831e768852ac9d744cb9ab7

**Closed by New0** 2019-12-17 13:45 UTC
Labels: Bug
