### ISSUE TITLE
Phone number (basic) now not filtering input or blocking non-number input

### ISSUE THREAD

**Issue by qubez** [CalderaWP/Caldera-Forms#1508] opened 2017-04-15 16:08 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?

1.5.0.8
(problem started in 1.5.x.x updates with changing phone number field to "basic" phone.

## What Is The Unexpected Behavior?

The phone number field was previously filtered, allowing only numbers and adding the dashes of US format numbers. Selecting other options, including "custom" with the (999)999-9999 option still does not prevent input of any text of any length.

## What PHP Errors Have You Logged While Reproducing This Bug?
none

## What JavaScript Errors Have You Seen While Reproducing This Bug?
none

**Comment by Shelob9** [comment] 2017-04-17 17:49
Duplicate of #1271

**Closed by Shelob9** 2017-04-17 17:49 UTC
