### ISSUE TITLE
Require jquery when registering parsley.min.js

### ISSUE THREAD

**Issue by sushmak02** [CalderaWP/Caldera-Forms#2791] opened 2018-10-25 10:12 UTC
## Do You Need Immediate Help?
Yes

## Is This A Feature Request?
Bug Fix

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
1.7.2

## What JavaScript Errors Have You Seen While Reproducing This Bug?
http://tinyurl.com/ycmu65fy

Please add jquery dependency while registering parsley.min.js
Change below code on classes/render/assets.php file - 
if( 'validator' == $script_key ){
	wp_register_script( self::make_slug( $script_key ), $script_url, array( 'jquery' ), CFCORE_VER, false );
	continue;
}

**Comment by Shelob9** [comment] 2018-10-26 14:15
I do not see a reason not to do this. Can you please submit a pull request against the develop branch?

**Comment by sushmak02** [comment] 2018-10-29 04:52
@Shelob9 We are happy that you considered this request.
Here is a link to the pull request - https://github.com/CalderaWP/Caldera-Forms/pull/2796

**Comment by Shelob9** [comment] 2018-11-06 21:21
Duplicate of #2722 

Should be fixed via #2805

**Closed by Shelob9** 2018-11-06 21:21 UTC
Labels: Bug, duplicate
