### ISSUE TITLE
How to disable dates in cfdatepicker

### ISSUE THREAD

**Issue by igorkk** [CalderaWP/Caldera-Forms#590] opened 2016-05-12 11:01 UTC
How to disable specific dates in cfdatepicker field with JS?

Live site:
http://www.apartman-suni-murter.com/booking/
I need to disable some fields at "From:" field.

**Comment by Shelob9** [comment] 2016-05-13 00:57
@igorkk I am closing this as it is a support question, not a bug. Please use CalderaWP.com/support for support.

**Closed by Shelob9** 2016-05-13 00:57 UTC
