### ISSUE TITLE
Range Sliders moving together

### ISSUE THREAD

**Issue by windywelly** [CalderaWP/Caldera-Forms#545] opened 2016-04-13 04:13 UTC
My Caldera Form consists of 8 Range Sliders (as well as other items). Even though the range sliders have different IDs, the 3rd one and 4th move together (I slide one of them and the other one slides together with it). Same is with the 5th and 6th, as well as 7th and 8th one - each of the pairs also move together, even though they shouldn't and they aren't intended to.
Would you, please, lead me to a direction which would help me to prevent the unwanted pairs from moving together?

**Comment by Shelob9** [comment] 2016-05-01 00:47
This is a bug, and someone else was showing me this before. I'm pretty sure the issue is browser dependent, I think Chrome and similar. What browser are you testing on?

**Comment by windywelly** [comment] 2016-05-01 01:35
@Shelob9 Hi, thanks for confirmation. You are right, I am using Chrome - Version 49.0.2623.112

**Comment by Shelob9** [comment] 2016-05-01 16:50
@windywelly Thanks for the update. I am reopening just so we can remember to double check it before the next release.

**Comment by Desertsnowman** [comment] 2016-05-01 18:11
I did a change a while back that caused an issue with id's of fields.  Basically repeat versions of a similar field looked the sane making it internally the same. I'll take a look and see what I can find.

**Comment by windywelly** [comment] 2016-05-02 08:52
@Desertsnowman that is some very weird bug. I can not reproduce it consistently, sometimes it just works, sometime it does not... I still have that issue

**Comment by Shelob9** [comment] 2016-06-04 20:35
@Desertsnowman Didn't you already fix this?

**Comment by Shelob9** [comment] 2016-11-20 23:58
This is fixed in 1.4.x

**Closed by Shelob9** 2016-11-20 23:58 UTC
Labels: bug, ready
