### ISSUE TITLE
"Phone Number (Basic)" field type not validating

### ISSUE THREAD

**Issue by peter-at-houston-academy** [CalderaWP/Caldera-Forms#1511] opened 2017-04-17 15:25 UTC
## Do You Need Immediate Help?
No.

## Is This A Feature Request?
No.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.3
PHP Version: 7.1.3
MySQL Version: 5.6.28
Caldera Forms Version: 1.5.0.7

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
When filling out a form on my site, any character (for instance, "&") is accepted by the "Phone Number (Basic)" validation (field turns green / is accepted on submit). It seems like the only validation that works on this field is the "empty" check if it is a required field. The field style I have selected is the default "Local" one, but parentheses are not added nor required for it to submit. Thank you for your help.

## What PHP Errors Have You Logged While Reproducing This Bug?
None.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None.

**Comment by Shelob9** [comment] 2017-04-17 17:48
This is a duplicate of #1508 and #1271

Related: #1507

**Closed by Shelob9** 2017-04-17 17:48 UTC
Labels: duplicate
