### ISSUE TITLE
Internal error 500 after WordPress update?

### ISSUE THREAD

**Issue by megwft** [CalderaWP/Caldera-Forms#2217] opened 2018-01-09 18:41 UTC
Hi, 

I've been going back and forth between programmers, server support and I can't find the solution to my client's problem with her Caldera forms. It's been driving us nuts since Christmas. Maybe somebody came across this issue recently?

Her WordPress and everything else works unless Caldera forms is enabled. 

If you need specific info please let me know and I'll run this by the programmer I work with. 

## Do You Need Immediate Help?
Not immediate but we've been going back and forth on this for a while without success...

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
I'm asking on behalf of a client and can't log in to WordPress because the log in page displays Internal error so can't check that I believe WP is WordPress 4.7.8. Can provide server details securely. 

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
YES Caldera forms causes error when everything else is turned off - that much we were able to check but then the programmer gets stuck and her server support doesn't provide code support. 

## What Is The Unexpected Behaviour?
Yes. But as she doesn't have the IT knowledge she wasn't editing the plugin or WP etc. The latest thing installed was SSL. We suspect that recent WordPress update triggered this - can't log in now. 
https://dpsionline.co.uk/wp/wp-admin/

I don't know if this is the right place but I don't think she has the Pro version and we would like this to work first before she decides to go for this extra version. I honestly have no ideas on how to help her otherwise.  :(

**Comment by Shelob9** [comment] 2018-01-18 23:40
@megwft Thanks for using Caldera Forms. I'm sorry you're having this issue. If you need help right away, we can help -- https://calderaforms.com/support

I am closing this issue as it describes an indeterminate error on a specific site, not a bug.

"Internal error" most likely means a fatal error happened and you suppressed error reporting. If you can point to a specific error message, we can look at it as a bug or suggest a fix.  See: https://calderaforms.com/2016/05/wordpress-debug-logging/

Again, we're always happy to help. This is a tool for us to track bugs and features. If you need support, please use https://calderaforms.com/support

**Closed by Shelob9** 2018-01-18 23:40 UTC

**Comment by Michal0307** [comment] 2018-03-06 09:19
This happend to me too
