### ISSUE TITLE
Default value of stars

### ISSUE THREAD

**Issue by texas2607** [CalderaWP/Caldera-Forms#1566] opened 2017-05-06 23:43 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.4
PHP Version: 5.6.8
MySQL Version: 5.0.83
Caldera Forms Version: 1.5.0.9

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Beahviour?
The stars are not at 0 when launching the form, they are on a value of 2.
How to resolve this ?

Regards,
Fred

**Comment by Shelob9** [comment] 2017-05-08 14:37
Closing as a duplicate of #1520

**Closed by Shelob9** 2017-05-08 14:37 UTC
Labels: duplicate
