### ISSUE TITLE
Uncaught ReferenceError: wp is not defined - Error in Console 

### ISSUE THREAD

**Issue by toukira54** [CalderaWP/Caldera-Forms#3178] opened 2019-04-25 09:44 UTC
I am having Uncaught ReferenceError: wp is not defined error in console. Tried all the available resources but did not helped.

Full Debug Information
WordPress Version: 5.1.1

PHP Version: 7.3.1-1+0~20190113101844.25+jessie~1.gbp15aaa9

MySQL Version: 5.6.43

Server Software: Apache/2.4.10 (Debian)

Caldera Forms Version: 1.8.4

site is : https://www.wonderwardrobes.com 

What should i do to remove this error?
![image](https://user-images.githubusercontent.com/48694402/56726575-a8f0e800-676c-11e9-83ca-8fb0a74b8498.png)

**Comment by Shelob9** [comment] 2019-04-29 14:52
Duplicate of #3141

**Closed by Shelob9** 2019-04-29 14:52 UTC
Labels: Bug, duplicate

**Comment by haroldotiberio** [comment] 2019-06-18 14:40
Error in Wp Rocket, disabled option 
![WP Rocket ‹ Lifecheck — WordPress](https://user-images.githubusercontent.com/51961833/59693772-cdda6800-91bd-11e9-92ce-16b32322e311.png)

**Comment by dokicro** [comment] 2019-06-21 17:44
@haroldotiberio you just saved my life ! :)
