### ISSUE TITLE
Problem when use File Uploader after login

### ISSUE THREAD

**Issue by mjblackhorse** [CalderaWP/Caldera-Forms#3277] opened 2019-06-30 07:58 UTC
## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support
No

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab
1.8.5, 5.3.2, php7.3.6
## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
yes

## What Is The Unexpected Behaviour?
* Please explain what you did, what you expected to happen, and what happened instead.
I create a form to upload a file with Advanced File Uploader(2). It works fine at very begining, however it reports an "Cookie nonce invaild" error if I submit this form after login.

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/
There is nothing related

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

**Comment by New0** [comment] 2019-07-10 13:59
Hello @mjblackhorse , I'm sorry you are having an issue with your form. I understand that your issue happens when you want to submit files via the form as a logged in user, is that correct ?

I couldn't reproduce that issue, could you share more details of the precise process that leads to this issue ?

If you need help with your specific setup, please use the support channel at https://calderaforms.com/support/

**Comment by mjblackhorse** [comment] 2019-07-11 00:31
I create a form to upload a file with Advanced File Uploader(2). 
Iit reports a "Cookie nonce invaild" error when I select a file and then submit the form after LOGIN!

**Comment by mjblackhorse** [comment] 2019-07-11 00:32
I create a form to upload a file with Advanced File Uploader(2). It works fine at very begining, however it reports an "Cookie nonce invaild" error if I submit this form after login

> Hello @mjblackhorse , I'm sorry you are having an issue with your form. I understand that your issue happens when you want to submit files via the form as a logged in user, is that correct ?
> 
> I couldn't reproduce that issue, could you share more details of the precise process that leads to this issue ?
> 
> If you need help with your specific setup, please use the support channel at https://calderaforms.com/support/

**Comment by New0** [comment] 2019-07-11 07:50
Hello @mjblackhorse , please provide more information, details about the process. ( For example, a regular login redirects to admin, are you using a different login process ?

**Comment by mjblackhorse** [comment] 2019-07-11 08:37
well，
The following is the test form I built:

Then I built a test page with this form:



Next, I login in another browser and another account, open the "test" page:



 Then I got the problem:

 
------------------ Original ------------------

**Comment by New0** [comment] 2019-07-15 09:19
Hello @mjblackhorse the form and page were not loaded in the message content.

**Comment by mjblackhorse** [comment] 2019-07-17 06:19
how could I upload figures?

**Comment by New0** [comment] 2019-07-17 12:55
Hello @mjblackhorse , you can drag and drop the images in the Github comment editor

**Comment by mjblackhorse** [comment] 2019-07-21 01:32
@New0 I've update the prievious comment with lost figures. can you see them?

**Comment by New0** [comment] 2019-07-22 08:31
Hello @mjblackhorse , thanks you for sharing those screenshot. I can see a specific error message that says "Cookie nonce is invalid". That means that it needs to be fixed in your environment, if you need support tracking this error you can use the support channel at - https://calderaforms.com/support/ - 
I'm closing as this doesn't show a bug or a feature request.

**Closed by New0** 2019-07-22 08:31 UTC
