### ISSUE TITLE
1.5: german special characters do not display properly and the form has stopped submitting the entries

### ISSUE THREAD

**Issue by buwug** [CalderaWP/Caldera-Forms#1264] opened 2017-02-22 14:09 UTC
## Do You Need Immediate Help?
Yes

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
1.5; 4.7.2; 7

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
No
## What Is The Unexpected Beahviour?
Updated from 1.4.9.1 to 1.5 and the form stopped submitting the entries + the german special characters do not show properly anymore

**Comment by Shelob9** [comment] 2017-02-22 17:51
Thanks for using Caldera Forms and for reporting this issue. I will get it fixed in 1.5.0.1 

I am closing this as as a duplicate of #1260

**Closed by Shelob9** 2017-02-22 17:51 UTC
Labels: duplicate
