### ISSUE TITLE
Calculation fields no linger working

### ISSUE THREAD

**Issue by Gentain16** [CalderaWP/Caldera-Forms#1582] opened 2017-05-12 17:30 UTC
## Do You Need Immediate Help?
* If so, please open a support ticket at https://CalderaForms.com/support

## Is This A Feature Request?
* If so, that's fine, please describe your desired featured and delete the rest of this template.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
*You can copy the "Short Debug" line from the Caldera Forms support menu's debug tab

**1.5.0.9**

**PHP Version 7.0.18**

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?

Yes

## What Is The Unexpected Beahviour?
* Calculation fields in 2 forms no longer work. Used to work perfectly. 

• Toggle Switch values no longer show up in "Total" boxes. 
• Tried switching to radio buttons and checkboxes and those operators still don't feed into the Calculation fields. Got checkbox to work once for few secs then field went black.
• "Number" field values (like the "tax deductible donation" field) do seem to feed into Calc fields

## What PHP Errors Have You Logged While Reproducing This Bug?
* See: https://calderaforms.com/2016/05/wordpress-debug-logging/
Huh?

Screenshots of whats wrong:

![caldera_calculation-bug](https://cloud.githubusercontent.com/assets/23608890/26009379/8bd71e3e-3716-11e7-9c70-d01a7fa81d51.jpg)
![caldera_calculation-bug2](https://cloud.githubusercontent.com/assets/23608890/26009394/93d34324-3716-11e7-989c-5d0fb5b4ce70.jpg)

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* See: http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers

Huh? None that I know of.

**Comment by Gentain16** [comment] 2017-05-12 17:32
mean to add that in top screenshot you'll see that "Total: 0.00" when it should at least include $20 from selected Chapter Only or National Membership Toggle Switch button.

I am using Divi v. 3.0.44

**Comment by Shelob9** [comment] 2017-05-15 16:45
Thanks for using Caldera Forms. I'm sorry you are having this issue. It is already fixed via #1570

**Closed by Shelob9** 2017-05-15 16:45 UTC

**Comment by Gentain16** [comment] 2017-05-15 16:53
I downgraded Caldera on Friday to prior version and that fixed it immediately. Another Divi User in Divi themes User Facebook page had same problem and told me to downgrade.

 If you haven't issued a release since then then it's not fixed yet.

**Comment by Gentain16** [comment] 2017-05-15 17:27
Btw thank you for emailing anyway!!! Much thanks!!?

**Comment by Shelob9** [comment] 2017-05-15 18:02
Sorry if that was confusing when I said it was fixed. What I meant is we
don't need an issue for this bug as we already have an issue and a fix for
that issue.

The issue is new to 1.5.0.9 so downgrading or installing from GitHub will
solve your issue.
