### ISSUE TITLE
Wrong czech encoding

### ISSUE THREAD

**Issue by jakubkaderavek** [CalderaWP/Caldera-Forms#1262] opened 2017-02-22 13:49 UTC
Hi,

I have WP 4.7.2 - when I update Caldera form to 1.5. then I have on frontend error in html field - I have this value:

<span id="recipe__add__step" class="button button--grey">Přidat další krok</span>

In admin is ok, but on frontend there is a problem wit encoding. Other fields are ok.

**Comment by Shelob9** [comment] 2017-02-22 17:51
Thanks for using Caldera Forms and for reporting this issue. I will get it fixed in 1.5.0.1

I am closing this as as a duplicate of #1260

**Closed by Shelob9** 2017-02-22 17:51 UTC
