### ISSUE TITLE
Condicional fields don't let the form be sent 

### ISSUE THREAD

**Issue by dsn240** [CalderaWP/Caldera-Forms#1481] opened 2017-04-07 01:09 UTC
Hello
We use conditionals for display information, meaning just html
After last update we can't not be able to make the form send

This only appends on chrome 
No error logs in the server are display
But I get this error in chrome console

conditionals.js?ver=1.5.0.7:281 Uncaught ReferenceError: $field is not defined
    at calders_forms_check_conditions (conditionals.js?ver=1.5.0.7:281)
    at HTMLInputElement.<anonymous> (conditionals.js?ver=1.5.0.7:301)
    at later (conditionals.js?ver=1.5.0.7:39)

**Comment by Shelob9** [comment] 2017-04-07 03:15
Thanks for using Caldera Forms. I'm sorry you are having this issue.

This is a duplicate of #1479 which is already fixed.

**Closed by Shelob9** 2017-04-07 03:15 UTC

**Comment by dsn240** [comment] 2017-04-07 03:34
This is still happening and is failing the submition
If is already fix where i can download that fix?

**Comment by Shelob9** [comment] 2017-04-07 03:53
https://github.com/CalderaWP/Caldera-Forms/archive/master.zip

**Comment by dsn240** [comment] 2017-04-07 09:17
Ok it works no error in front-end but a get this in dashboard when I'm editing a form
![image](https://cloud.githubusercontent.com/assets/24656696/24793774/e32fc67a-1b48-11e7-9733-222b17992c48.png)

Still works anyways... Thanks
