### ISSUE TITLE
Clone only clones form / layout?

### ISSUE THREAD

**Issue by AlchemyUnited** [CalderaWP/Caldera-Forms#1056] opened 2016-12-20 21:37 UTC
Cloned a form. Expected the Email tab to have all the same details. It didn't. 

I'm not sure if that's intentional or a bug.

**Comment by Shelob9** [comment] 2016-12-20 21:41
No, it's a bug that I havn't had a chance to fix...

Closing as duplicate of #505

**Closed by Shelob9** 2016-12-20 21:41 UTC
Labels: duplicate
