### ISSUE TITLE
jsconfig.php error on clean install

### ISSUE THREAD

**Issue by dimbak** [CalderaWP/Caldera-Forms#2631] opened 2018-06-22 09:54 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.6PHP Version: 7.0.30MySQL Version: 10.1.34Caldera Forms Version: 1.7.1.4WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
yes
## What Is The Unexpected Behaviour?
None, this is a clean WP install with only the CF plugin enabled and connected to CF Pro.

## What PHP Errors Have You Logged While Reproducing This Bug?
from the logger

[2018-06-22 09:46:39] 1296.INFO: Undefined index: ID {"location":{"file":"/home/dbtestgr/public_html/caldera/wp-content/plugins/caldera-forms/classes/api/jsconfig.php","line":82},"wp":{"doing_cron":false,"doing_ajax":false,"is_admin":false,"doing_rest":false,"user_id":1},"missing_tables":[],"versions":{"php":"7.0.30","client":"1.7.1.4","cf":"1.7.1.4","wp":"4.9.6","url":"https://dbtest.gr/caldera"}} []

## What JavaScript Errors Have You Seen While Reproducing This Bug?

inject.preload.js:373 GET blob:https://dbtest.gr/9f714e22-1ad6-4984-9632-999ffebf152c 0 ()
(anonymous) @ inject.preload.js:373
__webpack_require__ @ bootstrap a58e717ca664391e8660:19
splitSelector.splitSelector @ common.js:103
__webpack_require__ @ bootstrap a58e717ca664391e8660:19
exports.textToRegExp @ bootstrap a58e717ca664391e8660:62
(anonymous) @ bootstrap a58e717ca664391e8660:62
vue.min.js?ver=1.7.1.4:3 Download the Vue Devtools for a better development experience:
https://github.com/vuejs/vue-devtools
jquery.js?ver=1.12.4:4 GET https://dbtest.gr/caldera/wp-json/cf-api/v2/forms/null 500 ()
send @ jquery.js?ver=1.12.4:4
ajax @ jquery.js?ver=1.12.4:4
getForm @ entry-viewer-2.min.js?ver=1.7.1.4:1
(anonymous) @ entry-viewer-2.min.js?ver=1.7.1.4:1
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2
entry-viewer-2.min.js?ver=1.7.1.4:1 {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
jquery.js?ver=1.12.4:4 GET https://dbtest.gr/caldera/wp-json/cf-api/v2/entries/null?page=1&per_page=20 500 ()
send @ jquery.js?ver=1.12.4:4
ajax @ jquery.js?ver=1.12.4:4
getEntries @ entry-viewer-2.min.js?ver=1.7.1.4:1
(anonymous) @ entry-viewer-2.min.js?ver=1.7.1.4:1
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2
entry-viewer-2.min.js?ver=1.7.1.4:1 {readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}

**Comment by dimbak** [comment] 2018-06-22 10:09
Just switched from WP twentyseventeen and the errors JS errors are there, i tried different themes and i can see the errors only with twentyseventeen.

**Comment by Shelob9** [comment] 2018-06-22 13:06
Is this happening when outputting the Entry Viewer?

Please provide steps to reproduce.

**Comment by Shelob9** [comment] 2018-06-22 18:32
@dimbak What Helpscout ticket is this for and what are the steps for reproducing this issue?

**Comment by Shelob9** [comment] 2018-06-26 18:13
I tested this with just Caldera Forms and was unable to reproduce the problem. This suggests it is a site-specific issue, not a bug with Caldera Forms.  I am closing this issue.

**Closed by Shelob9** 2018-06-26 18:13 UTC
