### ISSUE TITLE
File upload passes slugname instead of URL of file when saving to a post

### ISSUE THREAD

**Issue by AmbitiousOkie** [CalderaWP/Caldera-Forms#2056] opened 2017-11-08 19:12 UTC
## Do You Need Immediate Help?
* No.

## Is This A Feature Request?
* No.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
* WordPress Version: 4.8.3 PHP Version: 7.1.11 MySQL Version: 5.6.36 Caldera Forms Version: 1.5.6.2

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
* Yes

## What Is The Unexpected Behaviour?
* File upload/Adv file upload passes the slugname back rather the URL of the file when saving to a post.

## Specifics
* Could be a bug or just a poor understanding of your article here: https://calderaforms.com/doc/caldera_forms_magic_file_use_link/
* Requirement: Need the URL of an uploaded file
* Field: Advanced File Uploader | Slug: "image"
![image](https://user-images.githubusercontent.com/11624558/32569040-98c24eaa-c485-11e7-83c7-8f0b951f6414.png)
* Variable: "var_image" set to equal %image%
![image](https://user-images.githubusercontent.com/11624558/32568736-c3d2878c-c484-11e7-8d43-42b17afce8cd.png)
* Save as Post Type | Everything works fine except "Post Content" which is currently set to "variable:var_image"
![image](https://user-images.githubusercontent.com/11624558/32568834-0f186f22-c485-11e7-911c-e6628f9bb027.png)
* Submitting the form works | The content of the post simply reads %image%
![image](https://user-images.githubusercontent.com/11624558/32568892-33b04a6c-c485-11e7-962c-aa9237cbbabe.png)
* It should be the URL of the image uploaded, not the slugname | CF Entries picked it up just fine
![image](https://user-images.githubusercontent.com/11624558/32569179-f9635150-c485-11e7-90b5-ae5672b3d474.png)

## What PHP Errors Have You Logged While Reproducing This Bug?
* Probably unrelated, but these are seen:
* fopen(http://adomain.com/wp-content/plugins/verify-email-for-caldera-forms/icon.png): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
* fopen(http://adomain.com/wp-content/plugins/caldera-form-metabox//metabox-icon.png): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
* fopen(http://adomain.com/wp-content/plugins/caldera-form-metabox//post-type.png): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
* Those are not typos

## What JavaScript Errors Have You Seen While Reproducing This Bug?
* Failed to load /wp-json/cf-api/v2/forms/CF5a02024d075ce/revisions?_wpnonce=2a49270dac resource: the server responded with a status of 404 (Not Found)

**Comment by New0** [comment] 2017-11-28 14:16
I understand how we could expect the image url to be printed in the content as this scenario uses a variable, but the image field is not supported in the Post content.

Not all field types can be saved in Post content and we are trying to set the limits using a dropdown select field to set the field used as Post content.

NOTE that Caldera custom fields allows images to be saved as featured image and/or media custom fields, if you have one of those in the post, that makes the image url available.

**Comment by Shelob9** [comment] 2017-12-13 22:00
@AmbitiousOkie Thanks for using Caldera Forms. I'm closing this as it's not a bug. It is not possible to use variables or magic tags to use a field's value as the post content. I'd recommend using `the_content` filter to get the saved image (use `get_post_meta()` and show it in the post.

**Closed by Shelob9** 2017-12-13 22:00 UTC
Labels: Support Request
