### ISSUE TITLE
JavaScript Error when submitting forms in Firefox (possibly Chrome)

### ISSUE THREAD

**Issue by ahinerfeld** [CalderaWP/Caldera-Forms#3021] opened 2019-02-27 14:34 UTC
## Do You Need Immediate Help?
No, I am testing on my Staging Site before Upgrading

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
    WordPress Version: 5.1PHP Version: 7.1.26MySQL Version: 5.6.40Caldera Forms Version: 1.8.0WP_DEBUG: 

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
I am unable to answer this, my site will fall apart if i disable everything.

## What Is The Unexpected Behavior?
If I use a mouse to click on the Form Submit button the button will not work but if I tab to the button and press enter the form submits correctly.

## What PHP Errors Have You Logged While Reproducing This Bug?
Unknown

## What JavaScript Errors Have You Seen While Reproducing This Bug?
Unknown

I have also enclosed an export of the form as a zip file:

I have tested this in FireFox and Safari and I get the same results.  The form workes perfectly prior to the upgrade to 1.80

Thanks,

Alex

**Comment by ahinerfeld** [comment] 2019-02-27 16:07
I see that the form was tested and was curious if you see the same result.

**Comment by swapnilmanjrekar** [comment] 2019-02-27 16:29
**I checked this bug using the following steps:**

- I created a  WordPress test site on my desktop locally using Lando.
- I installed Caldera Forms plugin on my test site.
- Using the Caldera Forms plugin, I created a blank form.
- I added a single text field "Name" & "Submit" button to my created blank form.
- I saved and loaded my form.
- I expected to see that I can click the "Submit" button through my mouse  and form to be submitted successfully
-  Next, I entered a name in the Name field of my form and clicked the submit button through the click of my mouse by pointing it towards the "Submit" button and the form was submitted successfully.
![clicking submit button through mouse](https://user-images.githubusercontent.com/43219826/53505857-bb0f1c80-3a82-11e9-9f46-428e16be5e20.gif)




**Javascript Errors:**

- When I checked the console of my web browser I didn’t see any javascript errors.


**PHP Errors:**

- When I checked the debug.log file of my WordPress test site I did not see any PHP errors.



- So according to my testing & findings, I think this is a not a bug as I was able to click the submit button by pointing my mouse towards "Submit" button and clicking the submit button, the form was submitted successfully and it was as per my expectations.


WordPress Version: 5.1PHP Version: 7.1.26MySQL Version: 5.7.25Caldera Forms Version: 1.8.0WP_DEBUG: 1

**Comment by Shelob9** [comment] 2019-02-27 17:00
@swapnilmanjrekar Thanks for testing. Which browsers did you test in? @ahinerfeld mentioned Safari and Firefox. I did a quick test in Chrome for Mac and it works. I wonder if this is a Safari or Firefox issue...

Can you please test in Firefox and Edge for Windows and I'll test Firefox and Safari for mac?

**Comment by swapnilmanjrekar** [comment] 2019-02-27 17:09
@Shelob9 I tested this on Google Chrome, Mozilla Firefox and Microsoft Edge Browsers in Windows 10.

**Comment by ahinerfeld** [comment] 2019-02-27 17:17
Thank for the update and the testing on a new form but did you try importing the form that was provided with the bug report?

I will also try deleting the submit button and then add it back to see if that helps to resolve the issue on my site.

**Comment by Shelob9** [comment] 2019-02-27 17:30
I imported the form and put it on a page here. http://dev-caldera-testing.pantheonsite.io/issue-3021/

@ahinerfeld Have you disabled other plugins and switched to the default theme?

**Comment by ahinerfeld** [comment] 2019-02-27 17:51
I just tried the form from the link in your reply. I filled in the field but I am not able to click on the button to to submit the form.  So I am seeing the exact same results as my staging site form.  
I am running Firefox Quantum 65.0.1 (64-bit).  I also tried it on Safari 12.0.3 with no joy.

I assume that you are not running any plugins on this test site.

**Comment by ahinerfeld** [comment] 2019-02-27 18:10
Thank you for confirming that this is a bug, I will wait for 1.8.1 to test the form again.

**Comment by Shelob9** [comment] 2019-02-27 18:11
In Firefox for mac -> `TypeError: e.currentTarget.activeElement.form is undefined[Learn More] index.min.js:7935` line is `if (e.currentTarget.activeElement.form.id === l) {`

![screen shot 2019-02-27 at 1 11 09 pm](https://user-images.githubusercontent.com/1994311/53512626-38da2480-3a91-11e9-8cc0-4895d8835b9b.png)

**Comment by mdee4** [comment] 2019-02-28 03:02
This is happening for me as well. I can confirm the issue happens on Safari and Firefox on my Mac.

**Comment by Shelob9** [comment] 2019-02-28 03:15
Will be fixed via #3028

**Comment by Shelob9** [comment] 2019-02-28 12:29
If anyone wants to test a fix for this issue, please download this ZIP and test on your staging site
[caldera-forms-1.8.1-beta.1.zip](https://github.com/CalderaWP/Caldera-Forms/files/2914907/caldera-forms-1.8.1-beta.1.zip)

**Comment by Shelob9** [comment] 2019-02-28 15:54
https://calderaforms.com/updates/caldera-forms-1-8-1/

**Comment by teljair** [comment] 2019-02-28 20:27
It's still broken for me on 1.8.1.

**Comment by Shelob9** [comment] 2019-02-28 21:08
@teljair I'm sorry to hear that. Can you please elaborate? I'd love to help, but I can't fix "still broken". Can you please provide the error you are having or a URL to your staging site where I can see this error? If you could provide all of the information that we request when opening a new ticket, that would be even more helpful.

**Comment by teljair** [comment] 2019-02-28 21:35
TypeError: window.cf2 is undefined[Learn More] caldera-forms-front.min.js:1:14979

When updated to 1.8.0 and 1.8.1.

I'm in the processing of rolling back 18 sites to 1.7.6.

**Comment by bk10000** [comment] 2019-03-01 02:15
This is occurring for me as well after upgrading to 1.8.1 the error above can be seen here on simple form https://forum-2019.aabat.org.au/get-in-touch/ and on a complicated connected form here https://aabat.org.au/survey-of-the-field/

**Comment by sushmak02** [comment] 2019-03-01 05:38
I am still facing the same issue after updating to the latest version.
Refer this screenshot - http://tinyurl.com/y5fbakqa

**Comment by Shelob9** [comment] 2019-03-01 13:14
@New0 take a look at the error in the screenshot that @sushmak02 sent, that's a different error. Did 1.8.1 fix the original issue and then create a new one?

**Comment by paaljoachim** [comment] 2019-03-01 13:20
I tested: https://www.staging1.crnra.vip/forms/hours/ on a Mac.
It works in Chrome.

No reaction with clicking Submit Hours button in Firefox. 

Error that shows up in the Console is:
TypeError: e.currentTarget.activeElement.form is undefined[Learn More] index.min.js:30:13624 
689 https://www.staging1.crnra.vip/wp-content/plugins/caldera-forms/clients/render/build/index.min.js?ver=1.8.0:30 dispatch8jQuery
init https://www.staging1.crnra.vip/wp-content/plugins/caldera-forms/assets/build/js/caldera-forms-front.min.js?ver=1.8.0:1 baldrick3jQuery

No reaction with clicking Submit Hours button in Safari.
Errors that shows up in the Console is:

<input class="btn btn-default" data-field="fld_5450836" id="fld_5450836_1" name="fld_5450836" type="submit" value="Submit Hours">

[Error] TypeError: undefined is not an object (evaluating 'e.currentTarget.activeElement.form.id')
	(anonymous function) (index.min.js:30:13662)
	dispatch (jquery.js:3:12450)
	handle (jquery.js:3:9179)
	trigger (jquery.js:3:11579)
	trigger (jquery-migrate.min.js:2:8280)
	(anonymous function) (jquery.js:3:18999)
	each (jquery.js:2:2886)
	each (jquery.js:2:851)
	trigger (jquery.js:3:18972)
	init (caldera-forms-front.min.js:1:14821)
	(anonymous function) (jquery-baldrick.min.js:1:4132)
	dispatch (jquery.js:3:12450)
	handle (jquery.js:3:9179)

**Comment by Shelob9** [comment] 2019-03-01 13:22
@paaljoachim thanks for testing. I can see you are still on 1.8.0. does this continue with 1.8.1?

**Comment by ahinerfeld** [comment] 2019-03-01 13:23
Please note that I have not had a chance to load 1.8.1 on this staging site yet.  I will download and update the plugin today. 3-1-19

**Comment by New0** [comment] 2019-03-01 13:30
Hello @sushmak02 , could you describe what's happening on the form when you get this error printed in the browser's console ?

**Comment by paaljoachim** [comment] 2019-03-01 13:37
I downloaded and imported the volunteer-hours json file here: https://paaljoachimromdahl.com/test/
Then updated Caldera Forms to 1.8.1. 

I got the form to work using 1.8.1 on a Mac using Firefox and Safari.

**Comment by ahinerfeld** [comment] 2019-03-01 13:41
I am also able to use the form from his site using Safari on my IPhone.  Thanks For uploading it and testing it.

**Comment by Shelob9** [comment] 2019-03-01 14:23
This is probably a new issue.

**Comment by paaljoachim** [comment] 2019-03-01 14:42
@sushmak02
Please open a new issue for your case.
Thanks.

**Comment by ahinerfeld** [comment] 2019-03-01 14:48
I have tested 1.8.1 and this seems to resolve the issue on both the Mac desktop and the iPhone.  Thank you.

**Closed** 2019-03-01 15:05 UTC
Labels: Bug, Has PR

**Comment by paaljoachim** [comment] 2019-03-01 15:07
The original issue has been fixed. Anyone with other issues need to open their own issue and follow the guide lines listed. Thanks.

**Comment by jonathantolentino** [comment] 2019-11-07 01:17
I have encountered this error while submitting the form. After I clicked the submit button, it always load. And have this error below.
Uncaught TypeError: Cannot read property 'data' of undefined
    at Object.error (caldera-forms-front.min.js?ver=1.8.7:7)
    at Object.request_error (jquery-baldrick.min.js?ver=1.8.7:7)
    at c (jquery-baldrick.min.js?ver=1.8.7:7)
    at Object.error (jquery-baldrick.min.js?ver=1.8.7:7)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as rejectWith] (jquery.js?ver=1.12.4-wp:2)
    at x (jquery.js?ver=1.12.4-wp:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4-wp:4)

**Comment by paaljoachim** [comment] 2019-11-07 01:23
Hey Jonathan
@jonathantolentino 

Please open a new issue. As this issue has been closed. Go through the steps in a new issue and answer each the best you can. It will help the developer fix the issue in a more efficient way. 

Thanks.
