### ISSUE TITLE
Random values from magic tags

### ISSUE THREAD

**Issue by doublebondweb** [CalderaWP/Caldera-Forms#3195] opened 2019-05-12 18:22 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.2PHP Version: 7.1.29MySQL Version: 5.6.40Caldera Forms Version: 1.8.4WP_DEBUG:

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes.

## What Is The Unexpected Behaviour?
Magical tags used in the emails that are sent after form submission retrieve random values. It happens if magical tags are included as hidden fields in the form to show up in the summary or if the tags are included in the automatic email (independent of the summary tag).
So, if I use the magical tag to get the URL I will get a random URL of the website everytime I submit that form. If I use 2 magical tags, one for title and one for URL, the title will match the URL but are not from the page where the form was submitted, instead they form another random page of the website. 

## What PHP Errors Have You Logged While Reproducing This Bug?
none

## What JavaScript Errors Have You Seen While Reproducing This Bug?
none

**Comment by New0** [comment] 2019-06-03 12:28
Hello @doublebondweb , I couldn't reproduce, are you using {embed_post:post_title} and {embed_post:permalink} tags? https://calderaforms.com/doc/using-magic-tags-caldera-forms/

I used them in a hidden field and they were correctly included to {summary} content. I also tested them directly in email content and they also worked as expected.

I'm closing the issue as there is not enough data that would help reproduce an issue. If your issue persists please reopen this issue completing the issue template and sharing a zip of a form export.

**Closed by New0** 2019-06-03 12:28 UTC
