### ISSUE TITLE
Clone Email Notification Settings when cloning form. Feature request

### ISSUE THREAD

**Issue by oldrup** [CalderaWP/Caldera-Forms#2690] opened 2018-08-05 19:02 UTC
Hi and thank you so much for a wonderful form creation tool. About to convert all our CF7 forms to Caldera – much easier for my not so tech savy colleagues to maintain.

In that process, I’m cloning forms a lot. And it puzzles me, that the settings under the “Email”, “Form settings” tab isn’t copied, but replaced with the defeault caldera information. That includes the fields

From Name
From E-mail
Reply To Email
Email Type
Email Recipients
BCC
Email Subject
Email Message
Success Message
… so I’m copying/pasting those fields by hand, one by one.

Luckily, the “Processors” tab is cloned automatically.

It would be cool, if the listed fields also would be cloned, or if it was possible to define the default values somewhere.

Kind regards,
Bjarne Oldrup

**Comment by Shelob9** [comment] 2018-08-07 17:53
Duplicate of #1282 fixed via 5fe42b8650696ce1852070482debce08c174bdec

**Closed by Shelob9** 2018-08-07 17:53 UTC
