### ISSUE TITLE
Admin nags are rendering in form editor.

### ISSUE THREAD

**Issue by paaljoachim** [CalderaWP/Caldera-Forms#808] opened 2016-09-08 09:56 UTC
Yeah I know this is a duplicate but I want to share the following just to show some of the things going on with the notifications. I believe this is an issue that will very likely be taken care of soon.

![screen shot 2016-09-08 at 11 51 23](https://cloud.githubusercontent.com/assets/5323259/18345185/a7c2e628-75ba-11e6-8116-b4347f8acae6.png)

Z-index. The form is in front of the notification message so that I can not click the X to close the warning message that says site blocked from being visible in search engines. 

I will go back to the Forms screen..

![screen shot 2016-09-08 at 11 53 37](https://cloud.githubusercontent.com/assets/5323259/18345233/e9c4d5a4-75ba-11e6-9928-190ded79dcf6.png)

Here I can Dismiss the WordFence notification and I can also close the warning that the site is not visible in search engines.

What about just blocking notifications from showing in any of the Caldera Forms screens...?

**Comment by Shelob9** [comment] 2016-12-01 02:01
This is a duplicate of #312 which is about to get closed.

**Closed by Shelob9** 2016-12-01 02:01 UTC
Labels: bug, Puntable
