### ISSUE TITLE
Don't show text of placeholder

### ISSUE THREAD

**Issue by maix4648** [CalderaWP/Caldera-Forms#641] opened 2016-06-16 13:35 UTC
Configuration: Linux Ubuntu 16.04 LTS, Firefox 47, Caldera Forms 1.3.5.3

In form builder is everything fine, but in preview i can't see text of placeholder. This problem applies to the element input, textarea is ok.

**Comment by Shelob9** [comment] 2016-06-17 17:53
Can you please tell me what theme you are using and if this occurs when you switch to the default theme?

**Comment by maix4648** [comment] 2016-06-18 14:30
Is not a problem with theme. Problem is with render on the Firefox. There are a possible code lines, which makes bug on Firefox. If disable this code, then show placeholder, but style of input element is horrible :)

Possible code:
-webkit-box-sizing: border-box; -moz-box-sizing: border-box;  box-sizing: border-box;

Problem found on css: caldera-grid.css
Lines: 178 and 478

**Comment by Shelob9** [comment] 2016-09-27 22:53
I can't reproduce this in Firefox for Ubuntu. When i enter a placeholder value for a text, textarea or email field, it shows in the editor and in the front-end. Will seek additional testing from others.

**Comment by maix4648** [comment] 2016-09-29 09:52
OK issues #87 . I confirm for windows. Sorry about this my mistake, but maybe on ubuntu got a problem.

**Comment by Shelob9** [comment] 2016-10-01 17:42
@maix4648 We have tested this in Firefox for Windows, Mac and Ubutnu and can can not reproduce the issue. I am closing this. If you have a fix you want to submit as a pull request (against 1.4.x) branch I'm happy to reopen for 1.4.4.

**Closed by Shelob9** 2016-10-01 17:42 UTC
Labels: bug, Needs Feedback From User, Needs Research
