### ISSUE TITLE
Only last advanced upload field in a form uploads a file

### ISSUE THREAD

**Issue by sportsnapper** [CalderaWP/Caldera-Forms#1267] opened 2017-02-22 15:21 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.7.2PHP Version: 5.6.30-0+deb8u1MySQL Version: 5.5.53 
Caldera Forms Version: 1.5.0 ( and the previous version)
WP_DEBUG: 1

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
YEs

## What Is The Unexpected Behaviour?
i created a form with multiple 'advanced file upload' fields. Each uploaded file will have data associated with them (category, caption), so I require fields such as file1, caption1, file2, caption2

When the form is submitted, only the last field uploads a file. 

If I change the fields in the form to a simple 'file upload' field, then all the files upload.

Whilst testing I also changed the 'advanced file upload' field to multiple files. In this case the first 'advanced file upload' field uploaded as well as the second field, with multiple files.

## What PHP Errors Have You Logged While Reproducing This Bug?
none
## What JavaScript Errors Have You Seen While Reproducing This Bug?
none

**Comment by Shelob9** [comment] 2017-02-22 17:45
Thanks for using Caldera Forms and for reporting this issue. I will get this fixed as soon as possible.

**Comment by Shelob9** [comment] 2017-02-22 19:00
@sportsnapper I'm testing this now with a form that has three advanced file fields, all three accept multiple files.

I have tested by uploading one file to each and uploading multiple files to each and can not reproduce this. Here is my test form:
https://www.dropbox.com/s/57loy54xbodlwim/adv-file-export.json?dl=0

I suspect that what is actually happening is to you is that the first file submits, this causes a PHP error and so the AJAX submission can't continue

Can you please test with PHP debug logging on and see if a PHP error is happening?

How to use the WordPress debug log to find hidden errors - https://calderaforms.com/2016/05/wordpress-debug-logging/

**Comment by sportsnapper** [comment] 2017-02-22 19:16
@Shelob9 Thanks for getting on to this so quickly.

I've loaded your test form, and it appears to only have one advanced file field.

This is my test form https://dl.dropboxusercontent.com/u/17766973/test-upload-export.json

I get no errors in the debug.log when I use this form. 

Reading your comment, I'm not sure I explained the problem well. 
Both my fields _do not_ accept multiple files - there's two distinct fields for two files, which will have associated data. 

When pressing submit, the green line starts for the second file field, and the first file field is ignored.

This is a preview version of what I'm trying to achieve (this has simple field upload) http://sports-alive.co.uk/?page_id=819&preview=true&cf_preview=CF58ab24e893986 to try to put this into context

**Comment by Shelob9** [comment] 2017-02-22 21:14
@sportsnapper You're welcome. I'm trying to get a quick update turned around today for issues that came up in this major release.

I can't see your form, since it is a preview. Is it possible to get a copy of your form export?

**Comment by sportsnapper** [comment] 2017-02-22 21:18
Zip of the form attached. Though this is the version that I've got to work using the simple file upload field. If you change the file upload fields to the advanced version then the issues can be reproduced.
[photo-comp-entry-export.json.zip](https://github.com/CalderaWP/Caldera-Forms/files/794813/photo-comp-entry-export.json.zip)

**Comment by Shelob9** [comment] 2017-02-22 23:14
@sportsnapper Thanks for sending that, I see the difference -- I had attach to mailer checked, you do not, and I can confirm that's the difference, works fine if attach to mailer is set. Now to figure out why...

**Comment by Shelob9** [comment] 2017-02-23 02:34
Moving to 1.5.0.2 as I'm out of brain power for the day and want to get 1.5.0.1 out, will try again tomorrow.

**Comment by sportsnapper** [comment] 2017-02-23 11:29
Thanks - I'm happy with the work around and I'm not going live with it for a week or so. I've spent rather too long already on this single form - but it's my first ;-)

**Comment by Shelob9** [comment] 2017-02-28 23:23
@sportsnapper Any chance you had a chance to test the latest?

**Comment by Shelob9** [comment] 2017-03-01 03:55
@andrewlimaza Can you please test? Make sure that if multiple advanced file fields are in form, they all upload, also that if multiple files are accepted by advanced file field, all those files upload.

**Comment by sportsnapper** [comment] 2017-03-01 09:55
@andrewlimaza @Shelob9 Just tested this morning using 1.5.0.3 and still doesn't upload anything but the last file.
Hadn't tested before as I thought you were targeting this for 1.5.0.4 - and been struggling trying to get Mailchimp processor working too!

**Comment by andrewlimaza** [comment] 2017-03-01 17:14
@Shelob9 tested this and works as expected. 

I tested with attach to mailer selected and deselected. All files upload inserted into WordPress media library and email.

Set to allow multiple + file restrictions.

One minor issue was that the files weren't showing up in Grid view but they do show up in List view. Screenshots below:

![default media library view](https://cloud.githubusercontent.com/assets/12629136/23471808/3fd6f586-feb3-11e6-9b6a-b51e0f185c9a.png)

![list view shows uploaded fields from advanced fields](https://cloud.githubusercontent.com/assets/12629136/23471825/543cdf2c-feb3-11e6-8d6f-14b41a1b7608.png)

**Comment by sportsnapper** [comment] 2017-03-01 18:48
I've attached the form I was testing with this morning, and the output csv. As you can see, there's only one file being uploaded, and it's a different field each time. I've also attached a copy of the form. There's also something pretty odd happening with a couple of the fields.

[Twyford-Together-advanced-fields.csv.zip](https://github.com/CalderaWP/Caldera-Forms/files/811732/Twyford-Together-advanced-fields.csv.zip)
[twyford-together-advanced-fields-export.json.zip](https://github.com/CalderaWP/Caldera-Forms/files/811731/twyford-together-advanced-fields-export.json.zip)

I am using a filter - 
`
add_filter( 'caldera_forms_upload_directory', function(){
	return 'form-uploads';
}) ;`

I'm just using add to media library as an option - I don't want big files in the mail system

**Comment by Shelob9** [comment] 2017-03-01 19:11
@sportsnapper I see from your export that you are still on 1.5.0.3, so it makes sense that you are only getting one file uploaded, this is fixed in 1.5.0.4

**Comment by sportsnapper** [comment] 2017-03-01 19:19
Ok - is 1.5.0.4 released or should I have been trying a different version from GitHub. When I checked this am 1.5.0.3 was the latest!

**Comment by Shelob9** [comment] 2017-03-01 20:05
1.5.0.4 should be out soon.

**Closed by Shelob9** 2017-03-01 20:05 UTC
Labels: Bug, Needs Feedback From User, NEEDS TESTING

**Comment by sportsnapper** [comment] 2017-03-01 22:41
I’ve just updated to 1.5.0.4 to quickly test this out.

My conditional fields appear to have stopped working. In the test form I sent you, if I now choose 2, 3, 4 or five files then the new fields don’t display. I ahvn’t changed anything else except update to 1.5.0.4

:-(

Gareth Jones


e: gareth@jonestheweb.com <x-msg://33/info@sports-alive.com> | t: 07870 667671 | w: www.sports-alive.com <x-msg://33/www.sports-alive.com> www.smart-pictures.co.uk
