### ISSUE TITLE
Payment Fields Break "Next Page" Buttons

### ISSUE THREAD

**Issue by blunket** [CalderaWP/Caldera-Forms#2095] opened 2017-11-22 17:48 UTC
## What Is The Unexpected Behaviour?
I have purchased and configured Paypal Express Checkout add-on. After adding credit card fields to my multi-page form, the "Next Page" buttons are disabled immediately after page load.

I've found where the problem occurs:
in the file   [assets/js/caldera-forms-front.js,  in the `setupLink()` function](https://github.com/CalderaWP/Caldera-Forms/blob/master/assets/js/caldera-forms-front.js#L6712)

```
function setupLink(){
    disableAdvance();
    // ...
}
```

**Comment by Shelob9** [comment] 2017-11-22 18:16
@blunket I'm sorry you're having this issue. Can you send a support request to us at https://calderaforms.com/support so we can help you out as efficiently and quickly as possible? That's what you're paying for :)

**Comment by Shelob9** [comment] 2017-11-29 19:20
Retoractive dupe of #2107

**Closed by Shelob9** 2017-11-29 19:20 UTC
Labels: duplicate
