### ISSUE TITLE
Breaks WooCommerce order details page

### ISSUE THREAD

**Issue by gurbyz** [CalderaWP/Caldera-Forms#2463] opened 2018-04-28 14:50 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 4.9.5PHP Version: 7.0.29MySQL Version: 5.5.5Caldera Forms Version: 1.6.1WP_DEBUG:
WooCommerce: 3.3.5

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Not able to do that.

## What Is The Unexpected Behaviour?
Caldera Forms 1.6.1 breaks WooCommerce. (Version 1.6.0 does not. I reinstalled it, to check.) On the detailed order page (admin area) you can press buttons but nothing will happen. (No call to backend is done at least). E.g. make a private note on the order doesn't work. E.g. change the amount of items in the order. All these buttons don't respond any more.

## What PHP Errors Have You Logged While Reproducing This Bug?
None.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
On page load console already says:
Uncaught TypeError: Cannot read property 'views' of undefined
    at HTMLDocument.<anonymous> (shortcode-insert.min.js:1)
    at i (load-scripts.php:2)
    at Object.fireWith [as resolveWith] (load-scripts.php:2)
    at Function.ready (load-scripts.php:2)
    at HTMLDocument.K (load-scripts.php:2)

This refers to this line of code:
        "function" == typeof wp.mce.views.register && wp.mce.views.register("caldera_form", {

Hope this helps. Success!

**Comment by Shelob9** [comment] 2018-05-09 17:19
Thanks for using Caldera Forms.

I tested this with just Caldera Forms and WooCommerce, no add-ons and was unable to reproduce the problem. This suggests it is a site-specific issue, not a bug with Caldera Forms.  I am closing this issue.

Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support

**Closed by Shelob9** 2018-05-09 17:19 UTC

**Comment by andrastudio** [comment] 2018-05-14 12:10
I'm also having the same issue, the issue breaks other javascript functions in the wp-admin section. Even after I disabled all plugins the issue still exist.

WP 4.95, Caldera Forms 1.6.11, PHP 7.2, WP_DEBUG: TRUE

**Comment by gurbyz** [comment] 2018-06-27 08:46
My issue disappeared with version 1.7.1.4. :-) Didn't do further investigation, so the fix could also have been in WooCommerce 3.4.3. But I'm happy again. :-)

WordPress Version: 4.9.6PHP Version: 7.0.30MySQL Version: 5.5.5Caldera Forms Version: 1.7.1.4
WooCommerce: 3.4.3
