### ISSUE TITLE
Attachements are not saved to server : 404 not found

### ISSUE THREAD

**Issue by shirokoweb** [CalderaWP/Caldera-Forms#3275] opened 2019-06-27 18:01 UTC
## Do You Need Immediate Help?
No, but a fast answer would be nice since issue is present on 100+ websites

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
WordPress Version: 5.2.2
PHP Version: 7.3.6
MySQL Version: 5.5.5
Caldera Forms Version: 1.8.5

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
YES

## What Is The Unexpected Behaviour?
According to saved entries; a file should be uploaded to a folder :
https://domain.tld/wp-content/uploads/a09dd32721a3c361af76e9712dd99696/uploaded-file-name.pdf

On FTP, there is no folder called /a09dd32721a3c361af76e9712dd99696/ inside /wp-content/uploads/ only standard WP folders organized by year.

## What PHP Errors Have You Logged While Reproducing This Bug?
No error.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
No error.

## Additional informations :
![image](https://user-images.githubusercontent.com/6638982/60289224-3b9d3700-9916-11e9-8067-cb054ae19f90.png)

**Comment by Shelob9** [comment] 2019-07-09 14:30
Thanks for using Caldera Forms. This is likely caused by the directory not being writtable. If you click add to media library, presuming your server can write PDF files there (check with your host) would resolve this.

I am closing this as it is site-specific not a bug. Please feel free to open a support request if you have a support subscription.

**Closed by Shelob9** 2019-07-09 14:30 UTC
