### ISSUE TITLE
Error PHP 7.4

### ISSUE THREAD

**Issue by wesleyas92** [CalderaWP/Caldera-Forms#3536] opened 2020-05-08 19:40 UTC
Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in C:\laragon\www\vinu-wp\wp-content\plugins\caldera-forms\classes\core.php on line 3732

**Comment by New0** [comment] 2020-05-13 13:54
Thanks for reporting this issue, this is a duplicate of #3476 
A PR was opened to address this and be reviewed for 1.9.0 milestone.

**Comment by Shelob9** [comment] 2020-06-12 22:51
This issue should be fixed in CF 1.9. a release candidate build, not fully tested can be downloaded here:

https://github.com/CalderaWP/Caldera-Forms/files/4766861/1.9.0-RC.1.zip

We welcome any testing, please let us know if this fixes your issue.

**Comment by New0** [comment] 2020-06-18 07:20
Closed via - https://github.com/CalderaWP/Caldera-Forms/commit/4cacd21dedbeb6db283d3785e500c34d9ba33d1f -

**Closed by New0** 2020-06-18 07:20 UTC
Labels: duplicate
