### ISSUE TITLE
Number field always returns 'Number Invalid'

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1405] opened 2017-03-15 13:38 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Tested on 1.5.0.6, 1.5.0.5

## Does Your Issue Presist When You Disable All Other Plugins and Switch To The Default Theme?
yes

## What Is The Unexpected Beahviour?
When a number field shows 'This value seems to be invalid.'
![image](https://cloud.githubusercontent.com/assets/12629136/23950289/2f455448-0993-11e7-8444-86e1b0a6aa8f.png)

## What Errors Have You Seen While Reproducing This Bug?
No PHP/JS errors

**Comment by andrewlimaza** [comment] 2017-03-15 14:11
This happens if field is required or not required.

**Comment by Shelob9** [comment] 2017-03-15 18:18
@andrewlimaza this is a dupe of #1376

**Comment by andrewlimaza** [comment] 2017-03-16 11:13
@Shelob9 this issue occurs on single page forms too.

**Comment by Shelob9** [comment] 2017-03-22 00:01
Removing the additional attributes min/max/step resolves this. #clue

**Comment by Shelob9** [comment] 2017-03-22 00:14
Almost fixed via 		d9cbe5b by removing empty values for min/max/step but min="0" which must be supported is making a invalid notice

**Comment by Shelob9** [comment] 2017-03-22 00:44
So to summarize issue/fix as note to self/ FYI to anyone:
Issue was the following:

-  Caldera Forms was outputting an empty attribute for min/max/step without a value led to markup like `<input type="text" min max step />` which parsely doesn't like.
- `min="0"` was causing validation error with an input value greater than 0, which sucks.

Fixed by:
- not outputting anything for min/max/step when they were not needed d9cbe5b 
- Adding manual validation when parsely says invalid and min is 0, and it is valid 	73dc166

**Closed by Shelob9** 2017-03-22 00:44 UTC
Labels: Blocker For Next Release, Bug, bug:major
