### ISSUE TITLE
Multisite issues break the form submission process for non-root sites on the network.

### ISSUE THREAD

**Issue by gornycreative** [CalderaWP/Caldera-Forms#540] opened 2016-04-10 16:48 UTC
Multisite installs break the system as far as I can tell for non-root sites.

If you try to network activate the plugin, the forms on all the non-root sites looks for site-specific caldera forms tables that the plugin itself doesn't create. e.g. prefix_12_cf_form_entries.

Furthermore, I have tried individually activating the plugin on single sites within a multisite network, and there are bugs that prevent the system from processing forms normally for all sites except the root site. The correct tables are made and used.

AJAX hangs endlessly on form submission and non-AJAX submissions time out eventually with a 504.

The form data itself does get through to the mailer - and gets saved as entries - but the user experience is poor.

**Comment by Shelob9** [comment] 2016-07-12 01:02
I am closing this after doing the following tests:

1) Make a new site in network
2) Network activate plugin
3) Go to that site's CF admin
4) Confirm that tables for that site were generated.
5) Make submission
6) Confirm that email was sent, and entry was recorded.
7) Repeat the above with the plugin already network activated.

@gornycreative  I'm not sure if you are still having this issue, but I can't see any logical way, besides inability to add tables due to a SQL setup issue, that would cause this. I'm happy to re-open if you can provide more info, but I can't reproduce and I have no other reports on this issue.

**Closed by Shelob9** 2016-07-12 01:02 UTC
Labels: bug, ready
