### ISSUE TITLE
Fatal Error When Re-sending Entry

### ISSUE THREAD

**Issue by StanfordAlan** [CalderaWP/Caldera-Forms#1894] opened 2017-08-31 05:12 UTC
Form in question can be seen on bottom of https://ontherisecreative.com.

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
1.5.5

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Yes

## What Is The Unexpected Behaviour?
1. Go to form entries.
2. Click Resend button next to entry.
3. Get error message below. (Folder with name changed to XXX.)

Fatal error: Uncaught TypeError: Argument 2 passed to Caldera_Forms_Field_Util::has_field_type() must be of the type array, null given, called in /home/XXX/public_html/otrc/wp-content/plugins/caldera-forms/classes/magic.php on line 46 and defined in /home/XXX/public_html/otrc/wp-content/plugins/caldera-forms/classes/field/util.php:361 Stack trace: #0 /home/XXX/public_html/otrc/wp-content/plugins/caldera-forms/classes/magic.php(46): Caldera_Forms_Field_Util::has_field_type('credit_card_exp', NULL) #1 /home/XXX/public_html/otrc/wp-includes/class-wp-hook.php(298): Caldera_Forms_Magic->field_magic(NULL, '%submit% from %...', Array, NULL, NULL) #2 /home/XXX/public_html/otrc/wp-includes/plugin.php(203): WP_Hook->apply_filters(NULL, Array) #3 /home/XXX/public_html/otrc/wp-content/plugins/caldera-forms/classes/magic/doer.php(57): apply_filters('caldera_forms_p...', NULL, '%submit% from %...', Array, NULL, NULL) #4 /home/XXX/public_html/otrc/wp-content/plugins/caldera-forms/classes/core.php(1958) in /home/XXX/public_html/otrc/wp-content/plugins/caldera-forms/classes/field/util.php on line 361

While I don't understand what most of this code is, I don't know why it's wanting something like credit card expiration date on a simple contact form. 

## What PHP Errors Have You Logged While Reproducing This Bug?
None are generated.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
None are generated.

**Comment by Shelob9** [comment] 2017-08-31 15:23
@StanfordAlan Thanks for using Caldera Forms. I'm sorry you are having this bug.

This issue is a duplicate of #1864 which is already fixed. You can download the latest version from Github or wait until 1.5.6 is released on WordPress.org in a week or two.

**Closed by Shelob9** 2017-08-31 15:23 UTC

**Comment by StanfordAlan** [comment] 2017-09-03 11:08
Thank you. I was apparently searching under the wrong keywords somehow. I very much appreciate your help!
