### ISSUE TITLE
Set an example for GDPR privacy Policies acceptance

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#2521] opened 2018-05-18 18:24 UTC
**Feature request** : 

Create an always required checkbox field with a label linked to Private Policy content page.

**Comment by Shelob9** [comment] 2018-05-21 13:20
Duplicate of #2428 but the PR and commits are tagging this so, leaving open.

**Comment by Shelob9** [comment] 2018-05-23 18:56
Close via 6af22b4

**Closed by Shelob9** 2018-05-23 18:56 UTC
Labels: enhancement
