### ISSUE TITLE
Default value doesn't work, sets option that has 0 as the value to default

### ISSUE THREAD

**Issue by andrewlimaza** [CalderaWP/Caldera-Forms#1294] opened 2017-02-24 12:20 UTC
If you create a radio field with 3 options with the value/label -

25 - $25
50 - $50 (this field is set as default selected)
0 - Other

When you view this field on the frontend, 'Other' will be selected by default.

**Comment by Shelob9** [comment] 2017-02-25 03:33
@andrewlimaza I can't reproduce this.

Check the last two fields in this test form (should default to Zero) and tell me if its resolved or my test is invalid: https://www.dropbox.com/s/lq4d4co3mq3jlf9/select-defaults-export%20%281%29.json?dl=0

**Comment by andrewlimaza** [comment] 2017-02-27 20:12
@shelob9 this issue still persists with radio fields.

In your form example, the very last radio box. Set a default to the value of 'One' and when you load the form on the frontend the 'Zero' will load as the default.

**Comment by andrewlimaza** [comment] 2017-02-27 20:16
This issue persists with Toggle Switches and Radio buttons. 

Other fields that have options seem to work as expected.

Issue only occurs if you set the value to `0`

**Comment by Shelob9** [comment] 2017-02-28 00:55
@andrewlimaza Please retest after eeea2e8

FYI Problem was that if 0 was value then `0==$field_value` evaluated true, eeea2e8 switches to `===`

**Comment by andrewlimaza** [comment] 2017-02-28 16:06
@Shelob9 this now works.

It makes sense :)

**Comment by Shelob9** [comment] 2017-02-28 23:24
Closing, but that makes sense to you? Please explain I'm confused AF.

**Closed by Shelob9** 2017-02-28 23:24 UTC
Labels: Bug, Needs Feedback From User, Needs Research
