### ISSUE TITLE
Error on Activating plugin

### ISSUE THREAD

**Issue by LynneMN** [CalderaWP/Caldera-Forms#3259] opened 2019-06-10 16:54 UTC
I have tried on 2 different sites to install Caldera Forms, both by installing directly through WP and also downloading the plugin and uploading to the sites. 

The plugin installs but when I try to activate it, an error message pops up **"The plugin does not have a valid header."**

**Comment by Sunglow** [comment] 2019-06-13 07:46
I have the same problem. Could anyone help, please?

**Comment by LynneMN** [comment] 2019-06-17 18:45
Come on guys it has been a week and there is a huge bug in Caldera forms 1.85 it will not activate once installed. Your lack of response is a huge indication of your professionalism or lack thereof!! I will be installing another form provider, and in light of your lack of response, removing Caldera from over all the sites that presently use it, and changing to the new form provider.
Totally disgusted with your lack of support.

**Comment by gitdrift** [comment] 2019-06-20 13:45
I can't reproduce it.

Debug information:
WordPress Version: 5.2.2PHP Version: 7.2.16MySQL Version: 5.5.5Caldera Forms Version: 1.8.5WP_DEBUG:

### Installing
![1-installing-cf](https://user-images.githubusercontent.com/49948173/59853834-fc00a900-9371-11e9-925f-f57b1c292063.PNG)

### Before activating
![2-installing-cf](https://user-images.githubusercontent.com/49948173/59853951-39fdcd00-9372-11e9-9b0c-7c295dadb22c.PNG)

### After activation
![3-installing-cf](https://user-images.githubusercontent.com/49948173/59853970-4124db00-9372-11e9-8b40-ac4a8cf489ba.PNG)

Working fine here. Please be respectful. Thanks.

**Comment by sburlot** [comment] 2019-06-21 22:20
I have the same problem when installing the 1.8.5, via zip file or via the wordpress plugin selector.
When this message appear, going to plugins and activating the CalderaForm plugin works.

I think the problem is because the archive contains a "trunk" folder, which also contains the plugin code. Removing the trunk folder and uploading the zip makes no error.
When WordPress sees 2 files with the mandatory plugin header, it makes an error.

![Screenshot 2019-06-22 at 00 18 20](https://user-images.githubusercontent.com/47066/59954075-445bbc00-9483-11e9-9d62-2422379748c2.png)

**Comment by netzih** [comment] 2019-06-30 20:53
> Come on guys it has been a week and there is a huge bug in Caldera forms 1.85 it will not activate once installed. Your lack of response is a huge indication of your professionalism or lack thereof!! I will be installing another form provider, and in light of your lack of response, removing Caldera from over all the sites that presently use it, and changing to the new form provider.
> Totally disgusted with your lack of support.

I had it too.
Had to log out of WP-Admin and log back in and I was able to activate..

**Comment by New0** [comment] 2019-07-10 12:08
Thank you for sharing your issue @LynneMN . In case you need help, please report to our support channel https://calderaforms.com/support/

Thank you @gitdrift , @sburlot , @netzih for your proactiv help, we deleted the trunk folder from tagged 1.8.5 in WordPress.org repo. Could those experiencing the issue try again please ?

**Comment by New0** [comment] 2019-07-22 08:39
I'm closing as this issue was not commented or reported again since we removed the extra trunk folder within tags/1.8.5.
Thanks again.

**Closed by New0** 2019-07-22 08:39 UTC
