### ISSUE TITLE
Pods template textarea style is overriden when Caldera Forms activated

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#2132] opened 2017-12-11 12:10 UTC
The main textarea field used to write template code for PODS ( #pods-form .postbox-container-2 #view_template .inside textarea#content )  is overriden by Caldera Forms when activated, making it hardly usable

**Comment by Shelob9** [comment] 2017-12-12 19:07
Duplicate of #2124

**Closed by Shelob9** 2017-12-12 19:07 UTC
Labels: duplicate
