### ISSUE TITLE
Warning: Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by ericakawasaki** [CalderaWP/Caldera-Forms#1963] opened 2017-09-21 11:58 UTC
Estou tendo este erro, como arrumar?

Warning: Invalid argument supplied for foreach() in public_html/wp-content/plugins/caldera-forms/classes/sync/calc.php on line 218

**Comment by Shelob9** [comment] 2017-09-26 21:10
Thanks for using Caldera Forms. This is a duplicate of #1959 there is an explanation of how to avoid this in that issue's discussion.

**Closed by Shelob9** 2017-09-26 21:10 UTC
