### ISSUE TITLE
Call to undefined function get_home_path

### ISSUE THREAD

**Issue by murashkin17** [CalderaWP/Caldera-Forms#2586] opened 2018-06-06 00:52 UTC
After updating plugin to 1.7.0 version, Wordpress crashes with  **Uncaught Error: Call to undefined function get_home_path()** 

Downgrading to 1.6.3 "fixed" the issue.

## Do You Need Immediate Help?
No

## Is This A Feature Request?
No

## What Version Of Caldera Forms, WordPress and PHP Are You Using?
    WordPress Version: 4.9.6 PHP Version: 7.2.5 MySQL Version: 5.5.60 Caldera Forms Version: 1.7.0 WP_DEBUG: 1

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
Do not know about the theme. The issue persists if all other plugins are disabled.

## What Is The Unexpected Behaviour?
After updating plugin to 1.7.0 version, Wordpress crashes.

## What PHP Errors Have You Logged While Reproducing This Bug?

<br /><b>Fatal error</b>: Uncaught Error: Call to undefined function get_home_path() in .../AIMKWordpress/wp-admin/includes/misc.php:204
Stack trace:
#0 .../AIMKWordpress/wp-includes/class-wp-rewrite.php(1775): save_mod_rewrite_rules()
#1 .../AIMKWordpress/wp-includes/class-wp-hook.php(286): WP_Rewrite-&gt;flush_rules(true)
#2 .../AIMKWordpress/wp-includes/class-wp-hook.php(310): WP_Hook-&gt;apply_filters(NULL, Array)
#3 .../AIMKWordpress/wp-includes/plugin.php(453): WP_Hook-&gt;do_action(Array)
#4 .../AIMKWordpress/wp-settings.php(471): do_action('wp_loaded')
#5 .../AIMKWordpress/wp-config.php(89): require_once('/homepages/26/d...')
#6 in <b>.../AIMKWordpress/wp-admin/includes/misc.php</b> on line <b>204</b><br />

## What JavaScript Errors Have You Seen While Reproducing This Bug?
Do not know.

**Comment by Shelob9** [comment] 2018-06-06 14:52
This is a duplicate of #2574

Can you please leave a list of plugins you have active and your theme as comment on that issue?

**Closed** 2018-06-07 18:10 UTC
Labels: duplicate
