### ISSUE TITLE
Email delivery issues when Forms setting sub-menu entry viewer is enabled

### ISSUE THREAD

**Issue by New0** [CalderaWP/Caldera-Forms#2220] opened 2018-01-11 20:28 UTC
Reproduced https://secure.helpscout.net/conversation/501405216/6943

The Sub-menu entry viewer cause issues with Email recipients and email attachments

**Comment by Shelob9** [comment] 2018-01-12 18:55
I;m seeing errors like this associated with this issue: 
`unserialize(): Error at offset 82 of 402 bytes /wp-includes/functions.php line 330`

https://secure.helpscout.net/conversation/464263361/6026/

**Comment by Shelob9** [comment] 2018-01-12 21:57
@New0 I created form `2220 CF Field: Adv File` in test forms sheet. I can't reproduce this using PHP7 or PHP5.6 against develop.

What am I doing wrong to recreate this?

FORM: https://pastebin.com/NEhcidZY


![screen shot 2018-01-12 at 4 55 50 pm](https://user-images.githubusercontent.com/1994311/34896908-94b0db58-f7b9-11e7-8012-ef2debd50744.png)

![screen shot 2018-01-12 at 4 55 40 pm](https://user-images.githubusercontent.com/1994311/34896909-94c27282-f7b9-11e7-82fa-18177d928e5d.png)

**Comment by Shelob9** [comment] 2018-01-12 22:19
I'm testing Gil's form (https://secure.helpscout.net/conversation/501405216/6943) if i turn on sub-menu entry viewer, no errors, but nothing is attached. With it off, email is attached.

**Comment by Shelob9** [comment] 2018-01-15 17:32
Form `2220 CF Field: Adv File create@x dev@1.5.9` reproduces this. `76c2e10` resolves this. I will run tests.

@New0 Please do a manual test (ensuring email is attached) of these three situations:
1) This form
2) This form with a 2nd file field that also has the add to media library setting checked.
3) This form, but with paypal express (want to make sure file field is still there properly after redirect.)

**Comment by Shelob9** [comment] 2018-01-16 19:40
This is being moved to 1.6.0 because while this probably fixes the issue and has no side effects, I don't have confidence in our ability to test it and I'm otherwise comfortable with moving to final testing of 1.5.9.

**Comment by Shelob9** [comment] 2018-01-18 18:08
I'm putting this back on 1.5.9 as it will not be released today. I will merge the PR and include in rc1 tag on dot org.

**Comment by Shelob9** [comment] 2018-01-18 22:03
Close via 
3157125

**Closed by Shelob9** 2018-01-18 22:03 UTC
Labels: Bug, Has Patch
