### ISSUE TITLE
Conditional hidden required fields still trigger a server-side validation.

### ISSUE THREAD

**Issue by juan-quiver** [CalderaWP/Caldera-Forms#1450] opened 2017-03-30 20:53 UTC
A hidden field (by conditionals) is removed from the DOM, but if it is required (and not used on processors [746](https://github.com/CalderaWP/Caldera-Forms/issues/746)), the server validation is still triggered and a message is shown on top of the form as per [#1246](https://github.com/CalderaWP/Caldera-Forms/issues/1246)

**Use case:**

A Dropdown triggers a condition to hide a required field. When hitting submit, a message on top of the form saying "X field is required" is shown, this prevents the submission from completing, even though the required field is hidden (removed from DOM).

WordPress Version: 4.7.3PHP Version: 5.6.30-1+wpengine8MySQL Version: 5.6.35Caldera Forms Version: 1.5.0.6WP_DEBUG: 1

**Comment by juan-quiver** [comment] 2017-03-30 21:28
My workaround is leaving the fields as non-required by default and change them to required using jQuery according to the dropdown selection. Same for the field visibility.

**Comment by Shelob9** [comment] 2017-03-31 21:51
Help scout 1071

**Comment by Shelob9** [comment] 2017-03-31 21:52
Possibly related: #1433

Related: #1246
Pretty much a dupe of #746

**Comment by Shelob9** [comment] 2017-04-01 21:01
Good news is that is this caused by the fact that this form is setting a hidden field's value with jQuery.val() doesn't seem to be possible to reproduce when setting field values with CF logic. That said should be supported, but isn't beacuse of bug that just got its own issue #1454 . Therefore closing since that's actual issue, and is about to get closed and I will follow up in HelpScout shortly.

**Closed by Shelob9** 2017-04-01 21:01 UTC
Labels: Bug, Puntable
