### ISSUE TITLE
No Mail-Content from single text flied when having a condition

### ISSUE THREAD

**Issue by AshenKeen** [CalderaWP/Caldera-Forms#2065] opened 2017-11-09 15:50 UTC
I have used the registration form and set up a "toggle switch" with three options. Then I have added two "single line text" flieds with a condition on the switcher. This works fine (single line text fields appear and disappear). The problem is, that the insertet text from these single line text fields is not included in the mail which is sent. 

E-Mail Message Content: {summary}

**Comment by Shelob9** [comment] 2017-11-09 22:07
Thanks for using Caldera Forms, I'm sorry you are having this issue.

This is probably a duplicate of #2071 Can you please test with Caldera Forms 1.5.7.1 and if you still have the issue, please open a new message that answers all of the questions in the template?

I hope you understand that the information that we ask for would explain if this is a bug or a site-specific issue or even how to test this issue -- we need to know what versions are involved or we can't test your issue proopp


Please note, this is not a support channel.  If you need immediate help with your site or help troubleshooting Caldera Forms on your site, please open a support ticket at https://CalderaForms.com/support

**Closed** 2017-11-09 22:07 UTC

**Comment by AshenKeen** [comment] 2017-11-10 06:40
Hi Shelob9

Thank you for your answer! Yes #2071 is exactly the same issue. I've updated the plugin to 1.5.7.1 and the bug is fixed! You guys rock! Thank you very much!

Best regards
Ashen
