### ISSUE TITLE
Caldera Forms Entries not showing properly on Website. 

### ISSUE THREAD

**Issue by NicolasJeannette** [CalderaWP/Caldera-Forms#3280] opened 2019-07-07 22:29 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?

WordPress Version: 5.2.2
PHP Version: 7.2.19
MySQL Version: 5.5.5
Caldera Version 1.8.5
## What Is The Unexpected Behaviour?

Hello, I've got a problem with showing entries on the website.
In the first picture there is three data from the Caldera Form Entries of the wp-admin.
![github results wanted](https://user-images.githubusercontent.com/44873578/60774619-f26b9500-a116-11e9-95b7-616bd823d0fb.png)

And in the second picture there is the results on the website.
![github problems](https://user-images.githubusercontent.com/44873578/60774623-031c0b00-a117-11e9-9a2d-3a3b64cd0fa6.png)

Not every entries have the same problems some entries works,showing correctly and others
don't works. I don't know why this keep happening and showing the same thing : "opt1832607".
 
Thanks for you help.

**Comment by New0** [comment] 2019-07-10 14:48
Hello @NicolasJeannette , thank you for sharing this issue.
Could you let us know which type of field is showing this extra data on frontend ? 
And what method do you use to display entries on frontend ?

**Comment by NicolasJeannette** [comment] 2019-07-10 16:33
Hello, @New0 I use the Check Box field for this form and for how i show the entries on the website, I use the entry shortcode given by your website. The shortcode is like "[caldera_forms_entry_viewer id="CF5d2083c65333b" with_toolbar="true"]".

I would like to say the first entries set was good and has no bug and more i added entries more entries ended with this problem.

**Comment by New0** [comment] 2019-07-23 12:01
Closed via 72cfbcc

**Closed by New0** 2019-07-23 12:01 UTC
Labels: Bug, Has PR

**Comment by NicolasJeannette** [comment] 2019-07-23 17:39
Hi, I'm sorry but your update doesn't affect our problem, we try to create a new form or use another check box but it doesn't work. Anything to add on the shortcode ? Or a parameter to add ?

**Comment by New0** [comment] 2019-07-24 08:44
Hello @NicolasJeannette , did you make sure all caches were flushed (even browser's ctrl + F5) during tests ? The assets need to be reloaded.

**Comment by NicolasJeannette** [comment] 2019-07-24 19:36
Hi @New0 , I try to flushed all the caches and my browser too. I also try to use the default theme of Wordpress, deactivated plugins and use the text option propose by Wordpress.  

To how I show the entries I just use this following shortcode "[caldera_forms_entry_viewer id="CF5d2083c65333b" with_toolbar="true"]" to show on the front-end.

The same problem is here with Divi theme and default theme.

**Comment by New0** [comment] 2019-07-25 07:55
Hello @NicolasJeannette , I can't reproduce your issue, could you share a link where I can see the entries ?
