### ISSUE TITLE
customer request: ability to custom label / rename the processors on your form 

### ISSUE THREAD

**Issue by cicichirinos** [CalderaWP/Caldera-Forms#1583] opened 2017-05-14 20:20 UTC
from user: If you're taking requests, I'd like to suggest that you allow processors to be labelled. I'm working on a site for a company that has quite a number of divisions; many of the divisions have a number of branches so I'm setting up conditional recipients for each branch. The trouble is that some divisions have over ten branches which makes it tedious when updates need to be made.

**Comment by Shelob9** [comment] 2017-05-15 16:38
Strong agreement. But closing as a duplicate of #1478

**Closed by Shelob9** 2017-05-15 16:38 UTC
Labels: duplicate
