### ISSUE TITLE
Plugin conflict: Caldera Forms & Yoast

### ISSUE THREAD

**Issue by MikeSmir** [CalderaWP/Caldera-Forms#3033] opened 2019-02-28 13:14 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Caldera Forms 1.8.0
WordPress 5.1
Yoast 9.7

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
No

## What Is The Unexpected Behaviour?

When I opening edit page that has Caldera Forms attached to it I am getting this error: 
```
The editor has encountered an unexpected error.

Attempt Recovery
Copy Post Text
Copy Error
```

The exact error:

```
TypeError: (0 , o.createPortal) is not a function
    at t.default (/wp-content/plugins/wordpress-seo/js/dist/wp-seo-post-scraper-970.min.js?ver=9.7:5:63916)
    at ph (/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:97:88)
    at eg (/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:125:307)
    at fg (/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:126:168)
    at wc (/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:138:237)
    at fa (/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:137:115)
    at gg (/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:135:196)
    at Ca (/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:133:365)
    at Object.enqueueSetState (/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:191:324)
    at r.q.setState (/wp-includes/js/dist/vendor/react.min.js?ver=16.6.3:20:304)
```

**The error happening only with the contact us page with Caldera Forms.**

**Comment by dnusca** [comment] 2019-02-28 18:19
Can also confirm this is an issue with 1.8.0 and 1.8.1

Reproduced on a fresh install, appears to originate from wp-polyfill so could be related to changes in Caldera or Yoast babel config?

```
TypeError: "o.createPortal is not a function"

    default http://testfresh.local/wp-content/plugins/wordpress-seo/js/dist/wp-seo-post-scraper-970.min.js?ver=9.7:5 ph http://testfresh.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:97 eg http://testfresh.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:125 fg http://testfresh.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:126 wc http://testfresh.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:138 fa http://testfresh.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:137 gg http://testfresh.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:135 Ca http://testfresh.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:133 enqueueSetState http://testfresh.local/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:191 setState http://testfresh.local/wp-includes/js/dist/vendor/react.min.js?ver=16.6.3:20 value http://testfresh.local/wp-includes/js/dist/data.min.js?ver=4.2.1:1 n http://testfresh.local/wp-includes/js/dist/data.min.js?ver=4.2.1:1 n http://testfresh.local/wp-includes/js/dist/data.min.js?ver=4.2.1:1 h http://testfresh.local/wp-includes/js/dist/data.min.js?ver=4.2.1:1 b http://testfresh.local/wp-includes/js/dist/data.min.js?ver=4.2.1:1 e http://testfresh.local/wp-admin/post.php?post=6&action=edit:1 y http://testfresh.local/wp-includes/js/dist/data.min.js?ver=4.2.1:1 v http://testfresh.local/wp-includes/js/dist/data.min.js?ver=4.2.1:1 l Redux dispatch http://testfresh.local/wp-includes/js/dist/data.min.js?ver=4.2.1:1 a4Redux
    j http://testfresh.local/wp-includes/js/dist/vendor/wp-polyfill.min.js?ver=7.0.0:2 j http://testfresh.local/wp-includes/js/dist/vendor/wp-polyfill.min.js?ver=7.0.0:2 f http://testfresh.local/wp-includes/js/dist/vendor/wp-polyfill.min.js?ver=7.0.0:1 
```

**Comment by Shelob9** [comment] 2019-02-28 19:04
Quick notes on this issue -

This is where we use ReactDom.createPortal https://github.com/CalderaWP/Caldera-Forms/blob/master/clients/render/components/RenderComponentViaPortal.js#L18 

I do not think babel is the issue, we are using @wordpress/default https://github.com/CalderaWP/Caldera-Forms/blob/master/.babelrc

BUT I think that instead of importing React and ReactDOM, and importing WordPress' export of those imports is probably the solution.

**Comment by New0** [comment] 2019-03-01 13:50
Hello @MikeSmir @dnusca @Shelob9 this is a build including the PR for this issue, could you use it for tests and let me know if that fixes the issue for you please ?
[1.8.2-beta.1.zip](https://github.com/CalderaWP/Caldera-Forms/files/2919650/1.8.2-beta.1.zip)

**Comment by vaka2vaka** [comment] 2019-03-01 15:00
1.8.2-beta.1.zip - The page opens The form is not sent.

**Comment by dnusca** [comment] 2019-03-01 15:58
@New0 Works in Gutenberg Editor. But I get the following errors on the frontend:

1. On page load
```
TypeError: wp.element is undefined[Learn More] index.min.js:30:14409

    689 http://testfresh.local/wp-content/plugins/1.8.2-beta.1/clients/render/build/index.min.js?ver=1.8.1:30 dispatch8jQuery

<anonymous> http://testfresh.local/wp-content/plugins/1.8.2-beta.1/assets/build/js/caldera-forms-front.min.js?ver=1.8.1:5 each2jQuery
<anonymous> http://testfresh.local/wp-content/plugins/1.8.2-beta.1/assets/build/js/caldera-forms-front.min.js?ver=1.8.1:5 <anonymous> http://testfresh.local/wp-content/plugins/1.8.2-beta.1/assets/build/js/caldera-forms-front.min.js?ver=1.8.1:5 
```

2. On failed form submission
```
TypeError: h.getAllFieldValues is not a function[Learn More] index.min.js:30:13586

    689 http://testfresh.local/wp-content/plugins/1.8.2-beta.1/clients/render/build/index.min.js?ver=1.8.1:30 dispatch8jQuery

init http://testfresh.local/wp-content/plugins/1.8.2-beta.1/assets/build/js/caldera-forms-front.min.js?ver=1.8.1:1 baldrick3jQuery
```

**Comment by New0** [comment] 2019-03-01 16:18
@dnusca @vaka2vaka  Thank you for the feedback, I couldn't reproduce the errors, I suspect the build failed to bundle all assets, could you test this new build and make sure the browser's cache is cleared ?
[1.8.2-beta.2.zip](https://github.com/CalderaWP/Caldera-Forms/files/2920233/1.8.2-beta.2.zip)

**Comment by vaka2vaka** [comment] 2019-03-01 16:29
form not submitted

Uncaught TypeError: Cannot read property 'render' of undefined
    at HTMLDocument.<anonymous> (index.min.js?ver=1.8.2-beta.2:30)
    at HTMLDocument.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLDocument.r.handle (jquery.js?ver=1.12.4:3)
    at Object.trigger (jquery.js?ver=1.12.4:3)
    at Object.a.event.trigger (jquery-migrate.min.js?ver=1.4.1:2)
    at HTMLDocument.<anonymous> (jquery.js?ver=1.12.4:3)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.trigger (jquery.js?ver=1.12.4:3)
    at HTMLFormElement.<anonymous> (caldera-forms-front.min.js?ver=1.8.2-beta.2:5)



index.min.js?ver=1.8.2-beta.2:30 Uncaught TypeError: h.getAllFieldValues is not a function
    at HTMLDocument.<anonymous> (index.min.js?ver=1.8.2-beta.2:30)
    at HTMLDocument.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLDocument.r.handle (jquery.js?ver=1.12.4:3)
    at Object.trigger (jquery.js?ver=1.12.4:3)
    at Object.a.event.trigger (jquery-migrate.min.js?ver=1.4.1:2)
    at HTMLDocument.<anonymous> (jquery.js?ver=1.12.4:3)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.trigger (jquery.js?ver=1.12.4:3)
    at Object.init (caldera-forms-front.min.js?ver=1.8.2-beta.2:1)

**Comment by swapnilmanjrekar** [comment] 2019-03-01 20:03
**According to my testing & findings, I see this as a bug as I was not able to submit my Contact form  in Contact us page**


**I checked this bug using the following steps:**

- I created a  WordPress test site on my desktop locally using Lando.
- I installed Caldera Forms plugin on my test site.
- I installed the Yoast SEO plugin on my local WordPress test site
- I created a contact us form from the available form templates.
- I saved the created contact us form.
- In my WordPress Test Site, Under Pages Section, I created a Page.
- In that page, I gave it name Contact Us.
- Using the block editor, I added the already created Contact Form from Caldera Forms plugin into the page
- I Saved and loaded the page.
- I expected to see Contact Form on the page while previewing the page.
- I was  able to see the contact form on the Contact Us page 
- Next, I entered all details in the Contact Form in Contact Us Page.
- I expected the Contact us page to be submitted successfully.
- But I was not able to submit the Contact Form in Contact Us Page and it was not as per my expectations.
- I tested this issue on Google Chrome, Mozilla Firefox & Microsoft Edge Browser in Windows 10


**PHP Errors:**
- When I checked the debug.log file of local WordPress test site I didn't see any PHP errors.

**JavaScript Errors:**
- When I checked the console of my browser,  I saw the following error: 
   "index.min.js?ver=1.8.2-beta.2:30 Uncaught TypeError: h.getAllFieldValues is not a function
    at HTMLDocument.<anonymous> (index.min.js?ver=1.8.2-beta.2:30)
    at HTMLDocument.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLDocument.r.handle (jquery.js?ver=1.12.4:3)
    at Object.trigger (jquery.js?ver=1.12.4:3)
    at Object.a.event.trigger (jquery-migrate.min.js?ver=1.4.1:2)
    at HTMLDocument.<anonymous> (jquery.js?ver=1.12.4:3)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.trigger (jquery.js?ver=1.12.4:3)
    at Object.init (caldera-forms-front.min.js?ver=1.8.2-beta.2:1)"

WordPress Version: 5.1PHP Version: 7.1.26MySQL Version: 5.7.25Caldera Forms Version: 1.8.2-beta.2WP_DEBUG: 1

**Comment by Shelob9** [comment] 2019-03-01 20:36
@New0 are we enqueuing wp-element?

**Comment by vaka2vaka** [comment] 2019-03-02 00:21
Version 1.7.6 works
1.8.0 - 1.7.6 = Problem

**Comment by vaka2vaka** [comment] 2019-03-02 07:43
Debug Bar plugin
Uncaught TypeError: Cannot read property 'render' of undefined
http://==============/wp-content/plugins/1.8.2-beta.2/clients/render/build/index.min.js?ver=1.8.2-beta.2 line 30

**Comment by New0** [comment] 2019-03-02 10:55
@vaka2vaka @swapnilmanjrekar Thank you for your feedback, I had a false positive that hid the error in both environments I was testing it and resulted in correct submission. I enqueued render/blocks on frontend using wp-blocks as a dependency. 
That fixes the issue but I'm not sure it's the final solution. 

I'm sharing a new build of the stage I'm at, your involvement and help is really appreciated
[1.8.2-beta.2.1.zip](https://github.com/CalderaWP/Caldera-Forms/files/2922014/1.8.2-beta.2.1.zip)

**Comment by vaka2vaka** [comment] 2019-03-02 11:16
It seems to me that everything works
From Google Chrome page is being edited

Successful sending - Google Chrome, Mozilla Firefox, Opera, Internet Explorer, browser.yandex.ru ....

I hope that the test of the other participants will also be successful.

**Comment by dnusca** [comment] 2019-03-02 13:47
1.8.2-beta.2.1.zip

Firefox 65 - doesn't crash the editor and submits successfully on the frontend.

**Comment by New0** [comment] 2019-03-05 16:53
Thank you all for contributing , this is fixed via https://github.com/CalderaWP/Caldera-Forms/commit/ee341d0051727c31faadb56c99cb0bf0e7156fa5 and will be in next update

**Closed by New0** 2019-03-05 16:53 UTC
Labels: Bug, Has PR

**Comment by Shelob9** [comment] 2019-03-06 19:23
This also caused an issue with Jetpack maps module. It is reported here that this beta solved the issue: https://wordpress.org/support/topic/maps-not-working-any-more/#post-11281545

**Comment by vaka2vaka** [comment] 2019-03-07 17:08
error 1.8.2

Advanced File Uploader (2.0)

index.min.js?ver=1.8.2:30 Uncaught TypeError: Cannot read property 'fields' of undefined
    at index.min.js?ver=1.8.2:30
    at NodeList.forEach (&lt;anonymous&gt;)
    at HTMLDocument.&lt;anonymous&gt; (index.min.js?ver=1.8.2:30)
    at HTMLDocument.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLDocument.r.handle (jquery.js?ver=1.12.4:3)
    at Object.trigger (jquery.js?ver=1.12.4:3)
    at Object.a.event.trigger (jquery-migrate.min.js?ver=1.4.1:2)
    at HTMLDocument.&lt;anonymous&gt; (jquery.js?ver=1.12.4:3)
    at Function.each (jquery.js?ver=1.12.4:2)
    at a.fn.init.each (jquery.js?ver=1.12.4:2)
(anonymous) @ index.min.js?ver=1.8.2:30
(anonymous) @ index.min.js?ver=1.8.2:30
dispatch @ jquery.js?ver=1.12.4:3
r.handle @ jquery.js?ver=1.12.4:3
trigger @ jquery.js?ver=1.12.4:3
a.event.trigger @ jquery-migrate.min.js?ver=1.4.1:2
(anonymous) @ jquery.js?ver=1.12.4:3
each @ jquery.js?ver=1.12.4:2
each @ jquery.js?ver=1.12.4:2
trigger @ jquery.js?ver=1.12.4:3
(anonymous) @ caldera-forms-front.min.js?ver=1.8.2:5
each @ jquery.js?ver=1.12.4:2
each @ jquery.js?ver=1.12.4:2
(anonymous) @ caldera-forms-front.min.js?ver=1.8.2:5
(anonymous) @ caldera-forms-front.min.js?ver=1.8.2:5
load (async)
(anonymous) @ caldera-forms-front.min.js?ver=1.8.2:5


Files pass Letter is sent

**Comment by Shelob9** [comment] 2019-03-07 17:12
@vaka2vaka can you please open a new issue?

Please try rolling back to 1.7.7 and see if that resolves your issue.

**Comment by vaka2vaka** [comment] 2019-03-07 17:22
olling back to 1.7.7  -  the problem disappeared
Advanced File Uploader (2.0)  not supported in version

**Comment by vaka2vaka** [comment] 2019-03-07 18:29
Checked on two sites Changed themes. The error remains. When adding the "Advanced File Uploader (2.0)" field
Files pass Letter is sent

ndex.min.js? ver = 1.8.2: 30 Uncaught TypeError: Cannot read property ‘fields’ of undefined
at index.min.js? ver = 1.8.2: 30
at NodeList.forEach (<anonymous>)
at HTMLDocument. <anonymous> (index.min.js? ver = 1.8.2: 30)
at HTMLDocument.dispatch (jquery.js? ver = 1.12.4: 3)
at HTMLDocument.r.handle (jquery.js? ver = 1.12.4: 3)
at Object.trigger (jquery.js? ver = 1.12.4: 3)
at Object.a.event.trigger (jquery-migrate.min.js? ver = 1.4.1: 2)
at HTMLDocument. <anonymous> (jquery.js? ver = 1.12.4: 3)
at Function.each (jquery.js? ver = 1.12.4: 2)
at a.fn.init.each (jquery.js? ver = 1.12.4: 2)
(anonymous) @ index.min.js? ver = 1.8.2: 30
(anonymous) @ index.min.js? ver = 1.8.2: 30
dispatch @ jquery.js? ver = 1.12.4: 3
r.handle @ jquery.js? ver = 1.12.4: 3
trigger @ jquery.js? ver = 1.12.4: 3
a.event.trigger @ jquery-migrate.min.js? ver = 1.4.1: 2
(anonymous) @ jquery.js? ver = 1.12.4: 3
each @ jquery.js? ver = 1.12.4: 2
each @ jquery.js? ver = 1.12.4: 2
trigger @ jquery.js? ver = 1.12.4: 3
(anonymous) @ caldera-forms-front.min.js? ver = 1.8.2: 5
each @ jquery.js? ver = 1.12.4: 2
each @ jquery.js? ver = 1.12.4: 2
(anonymous) @ caldera-forms-front.min.js? ver = 1.8.2: 5
(anonymous) @ caldera-forms-front.min.js? ver = 1.8.2: 5
load (async)
(anonymous) @ caldera-forms-front.min.js? ver = 1.8.2: 5
