### ISSUE TITLE
Conditionals From Auto-Responder Do Not Save If There Are Variables In Use

### ISSUE THREAD

**Issue by black-eye** [CalderaWP/Caldera-Forms#2512] opened 2018-05-17 08:44 UTC
## What Version Of Caldera Forms, WordPress and PHP Are You Using?
Version 1.6.2 (but WP says 1.6.3)

## Does Your Issue Persist When You Disable All Other Plugins and Switch To The Default Theme?
YES, but disapears when I rollback to previous version

## What Is The Unexpected Behaviour?
After Update, the Conditions in Auto Responder are Blank!

After rollback to v 1.6.1.1 everything is back to normal. But you've lost most of the settings if you saved the form in the meantime. If you haven't saved the template in v 1.6.2, the settings seems to be back completely.

Not sure, wheather the condition actualy worked on fontend (until saving the form, it might be just UI problem). Didn't have the nerve to test it more, it happened to me on live site.

BTW: not sure, what version it actually is: the changelog says 1.6.2, WP says 1.6.3.

## What PHP Errors Have You Logged While Reproducing This Bug?
No PHP error as far as I remember.

## What JavaScript Errors Have You Seen While Reproducing This Bug?
Unfortuately I rolled back to previous version, can't tell now.

**Comment by JacopoPatrocloMartinelli** [comment] 2018-06-06 15:45
Same issue here

**Comment by neovinter** [comment] 2018-06-15 03:16
I have the same issue with condition. One time it was happened with processor logic and another time with condition fields (show/hide). Only the DB recovery helped. To reproduce this issue just open conditions of two different forms in two different browser tabs at the same time.

**Comment by black-eye** [comment] 2018-07-15 00:13
Hi, any progress here?
In version 1.7.2 the problem is still present.

This is what I get after the update:
![obrazek](https://user-images.githubusercontent.com/5634870/42729010-9f45acbe-87ca-11e8-9a50-4f18b2ffff17.png)

And this is the screenshot from version 1.6.1.1 (how it should be):
![obrazek](https://user-images.githubusercontent.com/5634870/42729027-2fced94a-87cb-11e8-84bd-214aa99acd3d.png)

When I fill up the items again, it seems, that the form is remembering some of the data (after selecting the first field the second part is filled automatically).

But after saving the form and opening it again, the fields are empty again.

**Comment by Shelob9** [comment] 2018-07-18 13:45
@black-eye Thanks for the detail. Removing the variable from the form 

The only good reason for using variables is passback variables for the redicrect processor. Passback variables get added to the redirect url. You can reproduce that using magic tags in the redirect URL settings.

**Comment by nathanhere** [comment] 2018-08-10 04:01
Same issue here. I've got tons of passback variables saved on a form (for redirect purposes), as well as many redirect rules, which have been absolutely essential to the functionality of our site. I need to slightly modify the behavior of this form now, but I'm not quite sure how to go about that, seeing that all the redirect logic is gone, and it's difficult to remember exactly what was there before.

**Comment by Shelob9** [comment] 2018-09-26 14:35
@New0 I'm assigning to you, please reproduce and let me know if you need more help figuring out what is up. 

Once fixed, please confirm this is really a duplicate of #2658 Also, check out the info in that ticket.

**Comment by New0** [comment] 2018-10-04 20:31
- The value of the first select option of a condition line in a processor is set via assets/js/edit.js l885
- When a variable is set, this precise jQuery function ( assets/js/edit.js l885 ) is not called
I found that the rebind_field_bindings(); function, set l96 of ui/panels/variables is the function that prevents the value to be set.
The function rebind_field_bindings is declared l1334 in assets/js/edit.js
I still need to find what in this function is causing the issue, @Shelob9 do you have an idea of why the function is called there ?

**Comment by Shelob9** [comment] 2018-10-05 16:46
Fixed via #2753 5404d54

**Closed by Shelob9** 2018-10-05 16:46 UTC
Labels: Bug, Has Patch, bug:major
